const fs = require('fs');
const path = require('path');
const { quizzes, setQ, q } = require('./make_quiz_dataset.cjs');

// 5. Zootopia (A1-A2)
setQ("zootopia", [
  q("zt_1", "Thành phố Zootopia có khẩu hiệu nổi tiếng là gì?", "In Zootopia, anyone can be _______.", ["anything", "rich", "safe", "lazy"], "anything", "'Anyone can be anything' (Bất kỳ ai cũng có thể trở thành bất cứ điều gì)."),
  q("zt_2", "Judy Hopps là loài động vật đầu tiên làm cảnh sát Zootopia, đó là loài gì?", "Judy Hopps là một chú:", ["Rabbit / Bunny (Thỏ)", "Fox (Cáo)", "Bear (Gấu)", "Cheetah (Báo)"], "Rabbit / Bunny (Thỏ)", "Judy Hopps là cô thỏ đầu tiên trở thành sĩ quan cảnh sát tại Zootopia."),
  q("zt_3", "Nick Wilde kiếm sống bằng nghề lừa đảo bán lại kem que, được gọi là:", "Nick Wilde was running a _______.", ["popsicle hustle", "car wash", "bank", "restaurant"], "popsicle hustle", "Nick mua kem que Jumbo rồi làm tan ra thành những que nhỏ (pawpsicles) bán lại kiếm lời."),
  q("zt_4", "Chú lười Flash làm việc ở cơ quan nào khiến Judy sốt ruột phát điên?", "Flash làm việc ở đâu?", ["DMV (Department of Motor Vehicles)", "Post office", "Police station", "Hospital"], "DMV (Department of Motor Vehicles)", "Cục Đăng kiểm Xe DMV là nơi các chú lười làm việc với tốc độ siêu chậm."),
  q("zt_5", "Nick kể câu chuyện cười cho Flash nghe về con lạc đà có mấy bướu?", "What do you call a three-humped camel?", ["Pregnant!", "Fast!", "Tired!", "Hungry!"], "Pregnant!", "Câu đố chữ: Con lạc đà ba bướu là gì? - Là lạc đà đang mang thai (pregnant)."),
  q("zt_6", "Loại hoa độc làm cho động vật ăn thịt trở nên hung dữ điên loạn tên là gì?", "Tên của loài hoa gây ảo giác dại là gì?", ["Night Howlers", "Red Roses", "Sunflowers", "Tulips"], "Night Howlers", "Loài hoa 'Night Howlers' chứa độc tố khiến thú trở nên hoang dã cắn xé."),
  q("zt_7", "Thị trưởng đầu tiên của Zootopia là một chú sư tử dũng mãnh tên là gì?", "Tên của ngài thị trưởng sư tử là gì?", ["Mayor Lionheart", "Mayor Wolf", "Mayor Tiger", "Mayor Fox"], "Mayor Lionheart", "Mayor Lionheart (Thị trưởng Trái Tim Sư Tử)."),
  q("zt_8", "Phó thị trưởng cừu Bellwether thực chất là ai trong vụ án Night Howlers?", "Vai trò thực sự của cừu Bellwether là:", ["The mastermind behind the conspiracy", "An innocent victim", "A doctor", "A pilot"], "The mastermind behind the conspiracy", "Cừu Bellwether là kẻ chủ mưu giật dây chia rẽ muôn loài."),
  q("zt_9", "Bố mẹ Judy muốn cô ở lại quê nhà Bunnyburrow làm nghề gì an toàn hơn?", "Bố mẹ Judy muốn cô làm nghề gì?", ["Carrot farming (Trồng cà rốt)", "Singing", "Fighting", "Cooking"], "Carrot farming (Trồng cà rốt)", "Gia đình Hopps có truyền thống làm nông trại trồng cà rốt an lành."),
  q("zt_10", "Cảnh sát trưởng Bogo ban đầu giao cho Judy nhiệm vụ gì để làm cô nản lòng?", "Nhiệm vụ đầu tiên của Judy là gì?", ["Parking duty (Ghi vé phạt đỗ xe)", "Undercover spy", "Detective work", "Catching robbers"], "Parking duty (Ghi vé phạt đỗ xe)", "Trưởng đồn Bogo coi thường Judy và chỉ phân công cô đi phạt đỗ xe."),
  q("zt_11", "Judy dùng thiết bị bí mật nào hình củ cà rốt để ghi lại lời thú tội của Nick?", "Thiết bị đó là gì?", ["Carrot voice recorder pen", "Laser watch", "Mini camera", "Smartphone"], "Carrot voice recorder pen", "Chiếc bút ghi âm hình củ cà rốt có phát lại tiếng nói."),
  q("zt_12", "Trùm xã hội đen chuột chù lừng lẫy tại Tundratown tên là gì?", "Tên ông trùm chuột chù tí hon là gì?", ["Mr. Big", "The Godfather", "King Rat", "Don Mouse"], "Mr. Big", "Mr. Big là chú chuột chù Bắc cực nói giọng khàn kiểu Bố Già."),
  q("zt_13", "Ca sĩ linh dương nổi tiếng toàn cầu trong phim biểu diễn bài 'Try Everything' tên là gì?", "Tên ca sĩ thần tượng là gì?", ["Gazelle (do Shakira lồng tiếng)", "Lioness", "Peacock", "Zebra"], "Gazelle (do Shakira lồng tiếng)", "Ca sĩ Gazelle với bài hát bất hủ 'Try Everything'."),
  q("zt_14", "Khi Judy nói: 'I won't let you down', câu này có nghĩa là gì?", "Nghĩa của câu nói là gì?", ["Tôi sẽ không làm bạn thất vọng", "Tôi sẽ không đánh rơi bạn", "Tôi sẽ bỏ cuộc", "Tôi không thích bạn"], "Tôi sẽ không làm bạn thất vọng", "'Let someone down' nghĩa là làm ai đó thất vọng."),
  q("zt_15", "Từ tiếng Anh nào chỉ 'loài săn mồi ăn thịt'?", "Từ vựng tiếng Anh là:", ["Predator", "Prey", "Herbivore", "Plant"], "Predator", "'Predator' là loài thú ăn thịt săn mồi."),
  q("zt_16", "Từ đối lập với 'predator' chỉ 'con mồi bị săn đuổi' là gì?", "Từ vựng tiếng Anh là:", ["Prey", "Hunter", "Leader", "Monster"], "Prey", "'Prey' là con mồi."),
  q("zt_17", "Nick khuyên Judy: 'Never let them see that they _______ to you.'", "Điền từ vào chỗ trống:", ["get", "talk", "run", "call"], "get", "'Get to someone' nghĩa là làm ai đó tổn thương, nhụt chí."),
  q("zt_18", "Khu vực băng tuyết lạnh giá ở Zootopia được gọi là gì?", "Tên khu vực khí hậu tuyết trắng là gì?", ["Tundratown", "Sahara Square", "Rainforest District", "Little Rodentia"], "Tundratown", "Tundratown là khu đô thị vùng đài nguyên băng giá."),
  q("zt_19", "Khu rừng mưa nhiệt đới ẩm ướt với nhiều cây cổ thụ tên là gì?", "Tên khu vực rừng mưa là gì?", ["Rainforest District", "Desert Zone", "Ice Land", "Ocean Park"], "Rainforest District", "Rainforest District là khu rừng mưa nhiệt đới của Zootopia."),
  q("zt_20", "Bài học sâu sắc nhất của bộ phim Zootopia về mặt xã hội là gì?", "Bài học lớn nhất là gì?", ["Xóa bỏ định kiến và không phán xét ai qua vẻ bề ngoài hoặc giống loài", "Chỉ người mạnh mới thắng", "Đừng tin bất kỳ ai", "Trốn tránh trách nhiệm"], "Xóa bỏ định kiến và không phán xét ai qua vẻ bề ngoài hoặc giống loài", "Phim phê phán sâu sắc định kiến xã hội (prejudice) và ca ngợi sự hòa hợp.")
]);

// 6. The Lion King (A1-A2)
setQ("lion-king", [
  q("lk_1", "Bài hát chủ đề mở màn bộ phim miêu tả quy luật sinh tồn của tự nhiên tên là gì?", "Tên bài hát mở đầu là gì?", ["Circle of Life", "Let It Go", "Try Everything", "You've Got a Friend in Me"], "Circle of Life", "'Circle of Life' (Vòng Quay Cuộc Sống) là bản nhạc kinh điển của Elton John."),
  q("lk_2", "Mỏm đá sừng sững nơi các vị vua sư tử trị vì vương quốc tên là gì?", "Tên mỏm đá hoàng gia là gì?", ["Pride Rock", "Kings Hill", "Lion Mountain", "Sun Rock"], "Pride Rock", "Pride Rock là Mỏm Đá Vua biểu tượng."),
  q("lk_3", "Vua Mufasa dạy Simba: 'Everything the light touches is our _______.'", "Điền từ vào chỗ trống:", ["kingdom", "playground", "bedroom", "secret"], "kingdom", "'Kingdom' nghĩa là vương quốc bờ cõi."),
  q("lk_4", "Người chú mưu mô phản nghịch của Simba tên là gì?", "Tên của nhân vật phản diện là gì?", ["Scar", "Rafiki", "Zazu", "Pumbaa"], "Scar", "Scar là người em trai ghen ghét và âm mưu cướp ngai vàng của Mufasa."),
  q("lk_5", "Chú chim quản gia trung thành của hoàng tộc sư tử tên là gì?", "Tên chú chim mỏ sừng là gì?", ["Zazu", "Iago", "Hedwig", "Nigel"], "Zazu", "Zazu là viên cận thần lông xanh mỏ vàng tận tụy."),
  q("lk_6", "Khỉ đầu chó thông thái đóng vai trò pháp sư hoàng gia tên là gì?", "Tên của vị pháp sư khỉ là gì?", ["Rafiki", "Timon", "Shenzi", "Banzai"], "Rafiki", "Rafiki là vị pháp sư khỉ đầu chó thông thái."),
  q("lk_7", "Đôi bạn thân hài hước đã cứu sống Simba giữa sa mạc nắng cháy là ai?", "Hai người bạn đó là loài vật nào?", ["Meerkat and Warthog (Chồn đất và Lợn rừng)", "Dog and Cat", "Bear and Tiger", "Elephant and Giraffe"], "Meerkat and Warthog (Chồn đất và Lợn rừng)", "Timon là chú chồn meerkat còn Pumbaa là chú lợn lồi warthog."),
  q("lk_8", "Phương châm sống vô lo vô nghĩ của Timon và Pumbaa là gì?", "Câu khẩu hiệu tiếng Swahili là gì?", ["Hakuna Matata", "Carpe Diem", "Bazinga", "Alohomora"], "Hakuna Matata", "'Hakuna Matata' nghĩa là 'không có gì phải bận lòng'."),
  q("lk_9", "Vùng đất cấm địa âm u đầy xương sọ voi nơi linh cẩu ẩn nấp tên là gì?", "Vùng đất nguy hiểm đó là gì?", ["Elephant Graveyard", "Dark Forest", "Shadow Valley", "Haunted Swamp"], "Elephant Graveyard", "Nghĩa địa Voi (Elephant Graveyard) là nơi Scar lừa Simba đến."),
  q("lk_10", "Ba con linh cẩu tay sai của Scar tên là gì?", "Tên của ba con linh cẩu là gì?", ["Shenzi, Banzai, and Ed", "Tom, Dick, and Harry", "Huey, Dewey, and Louie", "Alvin, Simon, and Theodore"], "Shenzi, Banzai, and Ed", "Bộ ba linh cẩu tinh ranh và ngốc nghếch phục vụ dưới trướng Scar."),
  q("lk_11", "Cô bạn thanh mai trúc mã và sau này là hoàng hậu của Simba tên là gì?", "Tên của cô sư tử cái là gì?", ["Nala", "Sarabi", "Kiara", "Kopa"], "Nala", "Nala là bạn thân từ nhỏ và là người đi tìm Simba về cứu vương quốc."),
  q("lk_12", "Món ăn kỳ lạ mà Timon và Pumbaa dạy Simba ăn thay vì thịt là gì?", "Simba ăn món gì để sống sót?", ["Slimy, yet satisfying grubs (Sâu bọ nhớp nháp)", "Pizza", "Fish", "Raw grass"], "Slimy, yet satisfying grubs (Sâu bọ nhớp nháp)", "Timon dạy Simba ăn ấu trùng sâu bọ 'ngon ngọt béo ngậy'."),
  q("lk_13", "Mufasa xuất hiện trên bầu trời mây và nhắc nhở Simba điều gì?", "Mufasa dặn Simba: 'Remember who you _______.'", ["are", "were", "like", "meet"], "are", "'Remember who you are' (Hãy nhớ lấy con là ai)."),
  q("lk_14", "Vua Mufasa nói: 'Being brave doesn't mean you go looking for _______.'", "Dũng cảm không có nghĩa là đi tìm kiếm:", ["trouble", "food", "friends", "water"], "trouble", "'Looking for trouble' là cụm từ nghĩa là tự chuốc lấy rắc rối phiền toái."),
  q("lk_15", "Rafiki dùng gậy gõ vào đầu Simba và dạy cậu bài học gì về quá khứ?", "Bài học của Rafiki là:", ["Quá khứ đau đớn, nhưng bạn có thể trốn chạy hoặc học hỏi từ nó", "Quá khứ không có thật", "Hãy quên hết mọi thứ", "Đừng bao giờ quay về"], "Quá khứ đau đớn, nhưng bạn có thể trốn chạy hoặc học hỏi từ nó", "'The past can hurt. But you can either run from it or learn from it.'"),
  q("lk_16", "Scar vu khống cho Simba phải chịu trách nhiệm về cái chết của ai?", "Simba nghĩ mình đã gián tiếp gây ra cái chết của ai?", ["His father Mufasa", "His mother Sarabi", "Zazu", "Nala"], "His father Mufasa", "Scar đã lừa Simba tin rằng cậu chính là kẻ hại chết cha mình."),
  q("lk_17", "Từ tiếng Anh chỉ 'sự dũng cảm, lòng can đảm' là gì?", "Từ vựng tiếng Anh là:", ["Courage", "Fear", "Doubt", "Laziness"], "Courage", "'Courage' là lòng dũng cảm, dũng khí."),
  q("lk_18", "Từ tiếng Anh chỉ 'kẻ phản bội, kẻ bội phản' là gì?", "Từ chỉ kẻ phản bội là:", ["Traitor", "Hero", "Leader", "Friend"], "Traitor", "'Traitor' là kẻ phản bội đồng loại."),
  q("lk_19", "Cảnh cuối phim, Simba bước lên đỉnh Mỏm Đá Vua và làm gì dưới trời mưa?", "Simba đã làm hành động gì?", ["Roared loudly to reclaim his throne", "Fell asleep", "Ran away", "Swam in the river"], "Roared loudly to reclaim his throne", "Simba gầm vang chấn động để khẳng định lại vị thế chúa tể muôn loài."),
  q("lk_20", "Bài học lớn nhất về vai trò của người lãnh đạo trong The Lion King là gì?", "Người lãnh đạo đích thực cần có phẩm chất gì?", ["Trách nhiệm, lòng nhân từ và tôn trọng sự cân bằng tự nhiên", "Chỉ biết hưởng thụ và bóc lột kẻ yếu", "Sợ hãi và bỏ trốn", "Kiêu căng tự phụ"], "Trách nhiệm, lòng nhân từ và tôn trọng sự cân bằng tự nhiên", "Mufasa dạy rằng một vị vua đích thực là người biết phụng sự và bảo tồn sự sống.")
]);

console.log("Saving full question banks 5-6...");
module.exports = { quizzes, setQ, q };
