const { setQ, q } = require('./make_quiz_dataset');

// 13. How I Met Your Mother (B1-B2)
setQ("how-i-met-your-mother", [
  q("himym_1", "Khẩu hiệu nổi tiếng nhất của Barney Stinson khi rủ bạn bè ra ngoài là:", "Suit up! It's going to be _______!", ["legendary", "ordinary", "boring", "quiet"], "legendary", "'It's going to be legend... wait for it... dary!'"),
  q("himym_2", "Quán bar quen thuộc ở tầng dưới căn hộ nơi nhóm bạn tụ tập suốt 9 năm tên là gì?", "Tên quán bar là gì?", ["MacLaren's Pub", "Central Perk", "The Rusty Anchor", "Paddy's Pub"], "MacLaren's Pub", "MacLaren's Pub là quán bar ruột của nhóm."),
  q("himym_3", "Ted Mosby đã đánh cắp vật phẩm màu xanh nào từ nhà hàng trong buổi hẹn đầu với Robin?", "Món đồ đó là gì?", ["Blue French Horn (Chiếc kèn Pháp màu xanh)", "Blue painting", "Blue umbrella", "Blue guitar"], "Blue French Horn (Chiếc kèn Pháp màu xanh)", "Chiếc kèn đồng màu xanh (Blue French Horn) biểu tượng cho sự lãng mạn cuồng nhiệt của Ted."),
  q("himym_4", "Vật dụng biểu tượng của người Mẹ (The Mother - Tracy McConnell) mà Ted tìm kiếm là gì?", "Vật dụng màu vàng đó là gì?", ["Yellow umbrella (Chiếc ô màu vàng)", "Yellow dress", "Yellow hat", "Yellow car"], "Yellow umbrella (Chiếc ô màu vàng)", "Chiếc ô màu vàng huyền thoại kết nối định mệnh của Ted và Tracy."),
  q("himym_5", "Nghề nghiệp chính của Ted Mosby là gì?", "Ted làm nghề gì?", ["Architect (Kiến trúc sư)", "Doctor", "Lawyer", "Journalist"], "Architect (Kiến trúc sư)", "Ted là kiến trúc sư và sau này giảng dạy tại đại học Columbia."),
  q("himym_6", "Marshall Eriksen và Lily Aldrin có chuyện tình bắt đầu từ thời điểm nào?", "Họ quen nhau từ khi nào?", ["First day of college at Wesleyan University", "High school", "At work", "On a blind date"], "First day of college at Wesleyan University", "Marshall và Lily yêu nhau từ ngày đầu tiên bước chân vào đại học."),
  q("himym_7", "Quá khứ bí mật thời thiếu niên tại Canada của Robin Scherbatsky là gì?", "Robin từng là ai?", ["Robin Sparkles - ngôi sao ca nhạc tuổi teen", "Vận động viên trượt băng", "Đầu bếp", "Người mẫu"], "Robin Sparkles - ngôi sao ca nhạc tuổi teen", "Robin từng nổi tiếng với bài hát 'Let's Go to the Mall'."),
  q("himym_8", "Cuộc cá cược kéo dài suốt nhiều năm giữa Marshall và Barney tên là gì?", "Tên cuộc cá cược là gì?", ["The Slap Bet (Vụ cá cược ăn tát)", "The Money Bet", "The Car Bet", "The Hair Bet"], "The Slap Bet (Vụ cá cược ăn tát)", "Slap Bet cho phép Marshall tát Barney 5 lần bất ngờ vào những thời điểm ngẫu nhiên."),
  q("himym_9", "Cuốn sách cẩm nang chứa các chiến thuật tán tỉnh điên rồ của Barney tên là gì?", "Tên cuốn sách là gì?", ["The Playbook", "The Rulebook", "The Bible", "The Guide"], "The Playbook", "The Playbook chứa các chiêu trò nổi tiếng như 'The Lorenzo Von Matterhorn', 'The Scuba Diver'."),
  q("himym_10", "Robin Scherbatsky chuyển từ Canada sang New York để theo đuổi sự nghiệp gì?", "Robin làm nghề gì?", ["Television news anchor (Phát thanh viên truyền hình)", "Singer", "Lawyer", "Teacher"], "Television news anchor (Phát thanh viên truyền hình)", "Robin là phóng viên tin tức và dẫn chương trình thời sự tài năng."),
  q("himym_11", "Barney luôn trả lời bằng một từ bí ẩn nào mỗi khi ai đó hỏi về công việc thực sự của anh?", "Barney luôn đáp trả thế nào?", ["Please. (Làm ơn đi.)", "No.", "Secret.", "Never."], "Please.", "Viết tắt của: P.L.E.A.S.E. (Provide Legal Exculpation And Sign Everything)."),
  q("himym_12", "Cặp đôi nào đã tổ chức đám cưới hoành tráng ở mùa 9 sau nhiều biến cố tình cảm?", "Đám cưới đó là của ai?", ["Barney and Robin", "Ted and Robin", "Marshall and Lily", "Ted and Stella"], "Barney and Robin", "Mùa 9 diễn ra xuyên suốt cuối tuần tổ chức đám cưới của Barney và Robin tại Farhampton."),
  q("himym_13", "Món quà mà Ted mang đến tặng Robin ở ban công trong tập đầu tiên là gì?", "Ted đã mang đến gì?", ["The blue French horn", "Chocolates", "Flowers", "A ring"], "The blue French horn", "Ted mang chiếc kèn Pháp xanh quay lại tỏ tình với Robin."),
  q("himym_14", "Quy tắc 'Nothing good happens after 2:00 AM' do mẹ Ted dạy mang ý nghĩa gì?", "Quy tắc 2 giờ sáng nghĩa là:", ["Sau 2 giờ sáng nếu có chuyện gì xảy ra thì chỉ toàn là điều tồi tệ, hãy đi ngủ", "Sau 2 giờ sáng là lúc vui nhất", "Cứ thức trắng đêm", "Sau 2 giờ sáng nên gọi điện cho người yêu cũ"], "Sau 2 giờ sáng nếu có chuyện gì xảy ra thì chỉ toàn là điều tồi tệ, hãy đi ngủ", "Lời khuyên thực tế: 'When it's 2 AM, just go to sleep.'"),
  q("himym_15", "Chiếc áo bơi thợ lặn trong kế hoạch cuối cùng của Barney dùng để làm gì?", "Chiêu cuối 'The Robin' trong Playbook nhằm mục đích gì?", ["To propose to Robin (Cầu hôn Robin)", "To win a race", "To swim in the ocean", "To prank Ted"], "To propose to Robin (Cầu hôn Robin)", "Barney dùng chiêu 'The Robin' để cầu hôn cô trên sân thượng phủ đầy tuyết rơi."),
  q("himym_16", "Nhạc cụ mà người Mẹ (Tracy McConnell) chơi trong ban nhạc là gì?", "Tracy chơi nhạc cụ nào?", ["Bass guitar (Đàn guitar bass)", "Drums", "Piano", "Violin"], "Bass guitar (Đàn guitar bass)", "Tracy là tay chơi bass cừ khôi trong ban nhạc biểu diễn tại đám cưới."),
  q("himym_17", "Từ tiếng Anh 'wingman' dùng để chỉ ai trong văn hóa hẹn hò phương Tây?", "'Wingman' là người như thế nào?", ["Bạn thân hỗ trợ làm cầu nối giúp bạn tán tỉnh người khác", "Kẻ cướp người yêu", "Người phục vụ bàn", "Tài xế taxi"], "Bạn thân hỗ trợ làm cầu nối giúp bạn tán tỉnh người khác", "Barney luôn coi Ted là 'best wingman' số 1 của mình."),
  q("himym_18", "Quán bánh burger ngon nhất New York mà Marshall mất nhiều năm tìm kiếm có đặc điểm gì?", "Marshall miêu tả chiếc burger ngon nhất thành phố như:", ["Một tác phẩm nghệ thuật vị giác tuyệt đỉnh", "Một cái bánh bình thường", "Bánh mì chay", "Bánh ngọt"], "Một tác phẩm nghệ thuật vị giác tuyệt đỉnh", "Marshall miêu tả miếng thịt bò burger bằng bài văn trữ tình xúc động như thơ."),
  q("himym_19", "Cụm từ tiếng Anh 'have you met Ted?' là câu cửa miệng của ai?", "Ai thường dùng câu này để mai mối?", ["Barney Stinson", "Marshall", "Lily", "Robin"], "Barney Stinson", "Chiêu giới thiệu làm quen nhanh kinh điển của Barney tại quán bar."),
  q("himym_20", "Bài học cảm xúc sâu sắc nhất về tình yêu xuyên suốt cuộc hành trình của Ted Mosby là gì?", "Ted dạy chúng ta điều gì về tình yêu?", ["Tình yêu đích thực đáng để kiên nhẫn chờ đợi, không bao giờ từ bỏ hy vọng và sống hết mình vì người mình yêu", "Tình yêu chỉ đem lại đau khổ", "Càng tính toán càng dễ thắng", "Đừng tin vào số phận"], "Tình yêu đích thực đáng để kiên nhẫn chờ đợi, không bao giờ từ bỏ hy vọng và sống hết mình vì người mình yêu", "Ted là kẻ lãng mạn kiên cường nhất luôn tin vào số phận và tình yêu chân thành.")
]);

// 14. The Big Bang Theory (B1-B2)
setQ("the-big-bang-theory", [
  q("tbbt_1", "Từ cửa miệng nổi tiếng nhất của Sheldon Cooper sau mỗi trò đùa châm chọc là gì?", "Sheldon exclaims:", ["Bazinga!", "Bingo!", "Boom!", "Bravo!"], "Bazinga!", "'Bazinga!' là thương hiệu độc quyền của tiến sĩ Sheldon Cooper."),
  q("tbbt_2", "Sheldon có vị trí bất khả xâm phạm nào trên chiếc ghế sofa phòng khách?", "Chỗ ngồi của Sheldon được gọi là gì?", ["My spot (Vị trí đắc địa bất biến của tôi)", "The corner", "The throne", "The bed"], "My spot (Vị trí đắc địa bất biến của tôi)", "Sheldon chứng minh khoa học vị trí đó đón gió hoàn hảo và góc nhìn TV lý tưởng."),
  q("tbbt_3", "Thói quen gõ cửa kỳ quặc của Sheldon khi gọi Penny luôn lặp lại bao nhiêu lần?", "Sheldon gõ cửa và gọi tên thế nào?", ["Knocks 3 times: 'Penny! Penny! Penny!'", "Knocks once", "Rings the bell", "Kicks the door"], "Knocks 3 times: 'Penny! Penny! Penny!'", "Sheldon mắc hội chứng ám ảnh cưỡng chế gõ cửa 3 lần liên tiếp."),
  q("tbbt_4", "Bài hát ru mà Sheldon luôn bắt mọi người hát cho nghe mỗi khi bị ốm là gì?", "Tên bài hát ru mèo con là gì?", ["Soft Kitty", "Warm Puppy", "Little Star", "Sleepy Bear"], "Soft Kitty", "'Soft kitty, warm kitty, little ball of fur... happy kitty, sleepy kitty, purr purr purr.'"),
  q("tbbt_5", "Penny chuyển từ bang Nebraska tới California với ước mơ ban đầu là làm nghề gì?", "Ước mơ của Penny là gì?", ["Actress (Nữ diễn viên)", "Doctor", "Scientist", "Lawyer"], "Actress (Nữ diễn viên)", "Penny khao khát làm diễn viên và làm bồi bàn tạm thời tại The Cheesecake Factory."),
  q("tbbt_6", "Trong nhóm 4 nhà khoa học, ai là người duy nhất không có bằng tiến sĩ (Ph.D.)?", "Ai chỉ có bằng Thạc sĩ?", ["Howard Wolowitz (Master's degree from MIT)", "Leonard", "Sheldon", "Rajesh"], "Howard Wolowitz (Master's degree from MIT)", "Sheldon luôn đem chuyện Howard chỉ có bằng Thạc sĩ ra trêu chọc."),
  q("tbbt_7", "Căn bệnh tâm lý đặc biệt mà Rajesh Koothrappali mắc phải suốt những mùa đầu là gì?", "Rajesh bị làm sao khi gặp phụ nữ?", ["Selective mutism (Câm có chọn lọc khi ở cạnh phụ nữ tỉnh táo)", "Cannot see", "Cannot walk", "Sleepwalking"], "Selective mutism (Câm có chọn lọc khi ở cạnh phụ nữ tỉnh táo)", "Raj chỉ có thể nói chuyện với phụ nữ sau khi đã uống một chút cồn."),
  q("tbbt_8", "Tiến sĩ Leonard Hofstadter mắc chứng không dung nạp loại chất nào trong thực phẩm?", "Leonard bị dị ứng với chất gì?", ["Lactose intolerance (Không tiêu hóa được sữa/đường lactose)", "Gluten", "Peanuts", "Sugar"], "Lactose intolerance (Không tiêu hóa được sữa/đường lactose)", "Leonard bị đầy hơi đau bụng dữ dội nếu ăn phải phô mai hoặc sữa bò."),
  q("tbbt_9", "Người mẹ sùng đạo Baptist nghiêm khắc của Sheldon sống ở tiểu bang nào?", "Mẹ Sheldon sống ở đâu?", ["Texas", "New York", "Florida", "California"], "Texas", "Bà Mary Cooper là người mẹ Texas giàu lòng sùng đạo và yêu thương con trai."),
  q("tbbt_10", "Cô bạn gái nhà sinh học thần kinh đầy thông minh và kiên nhẫn của Sheldon là ai?", "Tên của nhân vật nữ là gì?", ["Dr. Amy Farrah Fowler", "Bernadette", "Phoebe", "Leslie"], "Dr. Amy Farrah Fowler", "Amy và Sheldon tạo thành cặp đôi 'Shamy' đoạt giải Nobel vật lý."),
  q("tbbt_11", "Cô vợ nhỏ nhắn nhưng có giọng nói the thé đầy uy lực của Howard tên là gì?", "Tên người vợ làm tiến sĩ vi sinh vật học là gì?", ["Bernadette Rostenkowski", "Penny", "Emily", "Priya"], "Bernadette Rostenkowski", "Bernadette kiếm được rất nhiều tiền từ ngành công nghiệp dược phẩm."),
  q("tbbt_12", "Trò chơi mở rộng của 'Oẳn tù tì' mà Sheldon thường xuyên chơi có thêm hai yếu tố nào?", "Trò chơi đó tên là gì?", ["Rock, Paper, Scissors, Lizard, Spock", "Rock, Paper, Fire", "Coin toss", "Card game"], "Rock, Paper, Scissors, Lizard, Spock", "Trò chơi mang tính toán xác suất do Sam Kass và Karen Bryla sáng tạo."),
  q("tbbt_13", "Chiếc thang máy trong khu chung cư của Leonard và Sheldon bị hỏng do nguyên nhân gì?", "Tại sao thang máy bị hỏng?", ["Vụ nổ thí nghiệm nhiên liệu tên lửa của Leonard", "Do sét đánh", "Do chập điện tự nhiên", "Do động đất"], "Vụ nổ thí nghiệm nhiên liệu tên lửa của Leonard", "Sheldon cứu mạng Leonard bằng cách ném thùng nhiên liệu đang bốc cháy vào buồng thang máy."),
  q("tbbt_14", "Sheldon tốt nghiệp đại học năm bao nhiêu tuổi và nhận bằng tiến sĩ đầu tiên năm mấy tuổi?", "Sheldon lấy bằng tiến sĩ năm bao nhiêu tuổi?", ["16 years old", "25 years old", "30 years old", "12 years old"], "16 years old", "Sheldon là thần đồng hoàn thành luận án tiến sĩ ở tuổi 16."),
  q("tbbt_15", "Món quà giáng sinh của Penny tặng Sheldon khiến anh sung sướng tột cùng đến mức ôm cô là gì?", "Món quà đó là gì?", ["A napkin signed and used by Leonard Nimoy (Spock trong Star Trek)", "A comic book", "A laptop", "A train set"], "A napkin signed and used by Leonard Nimoy (Spock trong Star Trek)", "Sheldon mừng rỡ vì sở hữu ADN của thần tượng Spock: 'I possess the DNA of Leonard Nimoy!'"),
  q("tbbt_16", "Nhân vật giáo sư thần tượng thời thơ ấu dạy khoa học trên TV của Sheldon tên là gì?", "Tên nhân vật là gì?", ["Professor Proton (Arthur Jeffries)", "Bill Nye", "Stephen Hawking", "Albert Einstein"], "Professor Proton (Arthur Jeffries)", "Giáo sư Proton do diễn viên gạo cội Bob Newhart thủ vai."),
  q("tbbt_17", "Howard Wolowitz từng có trải nghiệm đặc biệt nào trên Trạm Vũ trụ Quốc tế (ISS)?", "Howard đã bay lên đâu?", ["International Space Station (ISS) as an astronaut", "The Moon", "Mars", "The Sun"], "International Space Station (ISS) as an astronaut", "Howard tự hào mang danh hiệu nhà du hành vũ trụ 'Froot Loops'."),
  q("tbbt_18", "Tập cuối cùng của The Big Bang Theory, Sheldon và Amy đã vinh dự nhận giải thưởng gì tại Thụy Điển?", "Giải thưởng danh giá nhất là gì?", ["The Nobel Prize in Physics (Giải Nobel Vật lý)", "Oscar", "Grammy", "Pulitzer"], "The Nobel Prize in Physics (Giải Nobel Vật lý)", "Họ đoạt giải Nobel nhờ công trình nghiên cứu Siêu Bất Đối Xứng (Super-Asymmetry)."),
  q("tbbt_19", "Trong bài phát biểu nhận giải Nobel, Sheldon đã làm điều bất ngờ xúc động nào?", "Sheldon đã phát biểu điều gì?", ["Bỏ qua bài diễn văn dài dòng để cảm ơn và tri ân những người bạn thân thiết nhất", "Tự khen bản thân", "Kể chuyện cười", "Không nói lời nào"], "Bỏ qua bài diễn văn dài dòng để cảm ơn và tri ân những người bạn thân thiết nhất", "Sheldon công nhận rằng thành công của mình có được là nhờ tình yêu thương của bạn bè."),
  q("tbbt_20", "Sự hấp dẫn lớn nhất của The Big Bang Theory đối với người học tiếng Anh là:", "Lợi ích học tiếng Anh từ phim là:", ["Vừa học từ vựng khoa học công nghệ, vừa rèn luyện phản xạ đối thoại hài hước tốc độ cao", "Học tiếng Anh thời trung cổ", "Học từ ngữ nông nghiệp", "Không có lời thoại"], "Vừa học từ vựng khoa học công nghệ, vừa rèn luyện phản xạ đối thoại hài hước tốc độ cao", "Phim cung cấp vốn từ vựng học thuật phong phú và các cấu trúc châm biếm thông minh.")
]);

// 15. The Intern (B1-B2)
setQ("the-intern", [
  q("in_1", "Ben Whittaker (do Robert De Niro thủ vai) ứng tuyển vị trí gì ở tuổi 70?", "What role does Ben apply for?", ["Senior intern (Thực tập sinh cao tuổi)", "CEO", "Security guard", "Janitor"], "Senior intern (Thực tập sinh cao tuổi)", "Ben tham gia chương trình thực tập sinh dành cho người cao tuổi của công ty."),
  q("in_2", "Công ty About The Fit của Jules Ostin (Anne Hathaway) kinh doanh lĩnh vực nào?", "The company About The Fit is an:", ["Online fashion e-commerce site (Thương mại điện tử thời trang online)", "Auto repair shop", "Hospital", "Law firm"], "Online fashion e-commerce site (Thương mại điện tử thời trang online)", "Một công ty khởi nghiệp thời trang trực tuyến tăng trưởng thần tốc tại Brooklyn."),
  q("in_3", "Trước khi nghỉ hưu, Ben Whittaker đã từng làm việc 40 năm tại nhà máy sản xuất sản phẩm gì?", "Ben từng làm cho công ty sản xuất gì?", ["Phone directories / Yellow pages (Niên giám danh bạ điện thoại)", "Textiles", "Computers", "Cars"], "Phone directories / Yellow pages (Niên giám danh bạ điện thoại)", "Tòa nhà trụ sở About The Fit chính là nhà máy in danh bạ điện thoại cũ nơi Ben từng làm giám đốc."),
  q("in_4", "Vật dụng bất ly thân mà Ben luôn mang theo trong túi áo vest và sẵn sàng cho mượn là gì?", "Vật dụng đó là gì?", ["A handkerchief (Chiếc khăn tay sạch)", "A lighter", "A pen", "A knife"], "A handkerchief (Chiếc khăn tay sạch)", "Ben giải thích: 'The best reason to carry a handkerchief is to lend it.' (Lý do tuyệt vời nhất để mang khăn tay là để cho phụ nữ mượn khi họ khóc)."),
  q("in_5", "Phương tiện di chuyển độc đáo mà Jules Ostin sử dụng để đi lại trong khuôn viên văn phòng là gì?", "Jules đi lại bằng gì trong văn phòng?", ["Rides a bicycle (Đạp xe đạp)", "Roller skates", "Electric scooter", "Skateboard"], "Rides a bicycle (Đạp xe đạp)", "Jules đạp xe đạp quanh sàn văn phòng rộng lớn để tiết kiệm thời gian."),
  q("in_6", "Ben luôn đến văn phòng trong trang phục lịch sự nào khác biệt hoàn toàn với giới trẻ?", "Ben mặc trang phục gì?", ["A tailored suit and tie with polished shoes", "T-shirt and jeans", "Hoodie and sneakers", "Sportswear"], "A tailored suit and tie with polished shoes", "Phong thái quý ông lịch lãm với bộ vest chỉn chu và cà vạt thắt nghiêm túc."),
  q("in_7", "Người đồng nghiệp trẻ tuổi vụng về được Ben cưu mang cho ở nhờ nhà tên là gì?", "Tên anh chàng thực tập sinh trẻ là gì?", ["Davis", "Jason", "Lewis", "Cameron"], "Davis", "Davis bị bố mẹ đuổi khỏi nhà và được bác Ben hào phóng cho ở chung biệt thự."),
  q("in_8", "Nhân viên mát-xa trị liệu văn phòng quyến rũ có cảm tình với Ben tên là gì?", "Tên quý cô mát-xa là gì?", ["Fiona", "Becky", "Mia", "Sarah"], "Fiona", "Fiona (do Rene Russo thủ vai) dành nhiều tình cảm ngọt ngào cho Ben."),
  q("in_9", "Ben nhận thấy người lái xe riêng của Jules có biểu hiện say rượu, ông đã cư xử thế nào?", "Hành động lịch thiệp và tinh tế của Ben là:", ["Kín đáo khuyên người tài xế nghỉ ngơi và tự nguyện cầm lái thay để đảm bảo an toàn cho Jules", "Quát tháo ầm ĩ", "Báo cảnh sát bắt giữ", "Mặc kệ không quan tâm"], "Kín đáo khuyên người tài xế nghỉ ngơi và tự nguyện cầm lái thay để đảm bảo an toàn cho Jules", "Ben giải quyết vấn đề một cách cực kỳ tế nhị không làm ai bị bẽ mặt."),
  q("in_10", "Ban cố vấn và các nhà đầu tư khuyên Jules nên thuê một nhân sự cấp cao nào?", "Họ muốn Jules tuyển ai?", ["An experienced outside CEO (Tổng giám đốc điều hành thuê ngoài)", "A new accountant", "A new designer", "A lawyer"], "An experienced outside CEO (Tổng giám đốc điều hành thuê ngoài)", "Các nhà đầu tư lo ngại công ty lớn quá nhanh và muốn tìm một CEO giàu kinh nghiệm gánh vác thay Jules."),
  q("in_11", "Khi Jules vô tình gửi nhầm một email nói xấu mẹ ruột của mình, Ben và nhóm bạn đã làm gì?", "Họ đã lên kế hoạch gì?", ["Đột nhập vào nhà mẹ Jules để xóa bức email trên máy tính trước khi bà đọc được", "Gọi điện xin lỗi", "Đốt nhà", "Nghỉ việc"], "Đột nhập vào nhà mẹ Jules để xóa bức email trên máy tính trước khi bà đọc được", "Một phân đoạn hài hước kiểu 'Mission: Impossible' thu nhỏ."),
  q("in_12", "Chồng của Jules tên là Matt đã từ bỏ sự nghiệp cá nhân để làm công việc gì ở nhà?", "Matt làm gì?", ["Stay-at-home dad taking care of their daughter Paige", "Painter", "Musician", "Writer"], "Stay-at-home dad taking care of their daughter Paige", "Matt chấp nhận làm ông bố nội trợ chăm lo cho cô con gái nhỏ Paige."),
  q("in_13", "Bi kịch hôn nhân mà Jules phải đối mặt trong lúc công ty gặp áp lực lớn là gì?", "Sự việc đau lòng đó là gì?", ["Matt ngoại tình với một phụ huynh khác", "Matt phá sản", "Matt đòi ly hôn vì tiền", "Matt chuyển đi xa"], "Matt ngoại tình với một phụ huynh khác", "Jules phát hiện chồng lừa dối nhưng cố nén nỗi đau vì muốn giữ mái ấm gia đình."),
  q("in_14", "Ben an ủi và khuyên nhủ Jules điều gì về quyết định thuê CEO ngoài?", "Lời khuyên sáng suốt của Ben là:", ["Jules không nên từ bỏ quyền lực công ty mình sáng lập vì đứa con tinh thần này thuộc về đam mê của chính cô", "Nên bán công ty ngay", "Nên nghỉ hưu", "Nên nhường hết cho người khác"], "Jules không nên từ bỏ quyền lực công ty mình sáng lập vì đứa con tinh thần này thuộc về đam mê của chính cô", "Ben nhắc nhở Jules rằng không ai hiểu và yêu About The Fit bằng chính cô."),
  q("in_15", "Matt đến văn phòng và xin lỗi Jules, anh mong muốn điều gì?", "Mong muốn của Matt là gì?", ["Xin cô tha thứ và mong cô tiếp tục làm CEO theo đúng ước mơ và năng lực của mình", "Đòi chia tài sản", "Đòi quyền nuôi con", "Ép cô nghỉ việc"], "Xin cô tha thứ và mong cô tiếp tục làm CEO theo đúng ước mơ và năng lực của mình", "Matt nhận ra sai lầm và thật lòng hối hận trước sự vị tha của vợ."),
  q("in_16", "Cảnh cuối phim, Jules tìm thấy Ben đang tập luyện môn thể dục dưỡng sinh nào trong công viên?", "Môn dưỡng sinh đó là gì?", ["Tai Chi (Thái Cực Quyền)", "Yoga", "Jogging", "Pilates"], "Tai Chi (Thái Cực Quyền)", "Ben đang thư thái tập Thái Cực Quyền cùng mọi người và rủ Jules tham gia cùng."),
  q("in_17", "Thành ngữ tiếng Anh 'You're never wrong to do the right thing' bắt nguồn từ danh ngôn của ai?", "Câu nói này của danh nhân nào?", ["Mark Twain", "Abraham Lincoln", "Benjamin Franklin", "George Washington"], "Mark Twain", "Ben trích dẫn câu nói bất hủ của đại văn hào Mark Twain."),
  q("in_18", "Từ tiếng Anh nào chỉ 'sự giao tiếp lịch thiệp, phong nhã của một quý ông'?", "Từ vựng tiếng Anh là:", ["Chivalry / Gentlemanly manners", "Rudeness", "Arrogance", "Selfishness"], "Chivalry / Gentlemanly manners", "Phim ca ngợi vẻ đẹp của phong thái lịch thiệp quý ông cổ điển."),
  q("in_19", "Cụm từ tiếng Anh 'freak out' dùng rất nhiều trong phim mang nghĩa là gì?", "What does 'freak out' mean?", ["Hoảng loạn, mất bình tĩnh, phát hoảng", "Vui sướng nhảy múa", "Đi ngủ say", "Ăn uống no nê"], "Hoảng loạn, mất bình tĩnh, phát hoảng", "'Freak out' là cụm từ khẩu ngữ chỉ phản ứng hoảng sợ lo âu."),
  q("in_20", "Bài học sâu sắc nhất mà The Intern gửi gắm về khoảng cách thế hệ là gì?", "Thông điệp lớn nhất của phim là:", ["Kinh nghiệm sống của người già và sự năng động của giới trẻ khi kết hợp sẽ tạo nên sức mạnh tuyệt vời", "Người già nên ở nhà không nên đi làm", "Giới trẻ không cần học hỏi người đi trước", "Chỉ công nghệ mới giải quyết được mọi việc"], "Kinh nghiệm sống của người già và sự năng động của giới trẻ khi kết hợp sẽ tạo nên sức mạnh tuyệt vời", "'Experience never gets old' - Sự từng trải và lòng chân thành luôn trường tồn theo thời gian.")
]);

console.log("Saving full question banks 13-15...");
module.exports = { setQ, q };
