const { setQ, q } = require('./make_quiz_dataset');

// 10. Inside Out (B1-B2)
setQ("inside-out", [
  q("io_1", "Bộ não của cô bé Riley được chỉ huy bởi 5 cảm xúc cốt lõi nào?", "5 cảm xúc đó là:", ["Joy, Sadness, Anger, Fear, Disgust", "Love, Hate, Envy, Greed, Pride", "Sleep, Hunger, Thirst, Pain, Joy", "Hope, Courage, Doubt, Trust, Fear"], "Joy, Sadness, Anger, Fear, Disgust", "5 cảm xúc: Niềm Vui, Nỗi Buồn, Giận Dữ, Sợ Hãi, Chảnh Chọe (Ghê Tởm)."),
  q("io_2", "Trụ sở đầu não nơi 5 cảm xúc điều khiển bảng điều khiển tâm trí gọi là:", "What is the command center called?", ["Headquarters", "Pentagon", "Control Tower", "Space Station"], "Headquarters", "Headquarters (Trụ sở đầu não) của tâm trí."),
  q("io_3", "Những ký ức quan trọng nhất phát sáng rực rỡ nuôi dưỡng các hòn đảo nhân cách gọi là:", "Những viên ngọc ký ức đó là:", ["Core memories", "Faded memories", "Daily memories", "Nightmares"], "Core memories", "'Core memories' (Ký ức cốt lõi) định hình các mặt tính cách."),
  q("io_4", "Món rau củ trên bánh pizza ở San Francisco mà Disgust ghê sợ nhất là gì?", "Món rau củ đó là gì?", ["Broccoli (Bông cải xanh)", "Carrot", "Potato", "Tomato"], "Broccoli (Bông cải xanh)", "Disgust nổi cáu khi thấy pizza phủ đầy bông cải xanh."),
  q("io_5", "Người bạn tưởng tượng thời thơ ấu bằng kẹo bông gòn của Riley tên là gì?", "Tên người bạn là gì?", ["Bing Bong", "Frosty", "Olaf", "Casper"], "Bing Bong", "Bing Bong là sinh vật lai voi, mèo và cá heo tạo ra từ kẹo bông gòn."),
  q("io_6", "Chiếc xe tên lửa đồ chơi của Bing Bong chạy bằng nguồn năng lượng gì?", "Xe tên lửa chạy bằng gì?", ["Song power (Sức mạnh câu hát bài ca)", "Electricity", "Gasoline", "Sunlight"], "Song power (Sức mạnh câu hát bài ca)", "Chiếc xe tăng tốc mỗi khi cất lên câu hát: 'Who's your friend who likes to play? Bing Bong, Bing Bong!'"),
  q("io_7", "Vực thẳm tăm tối nơi những ký ức cũ bị lãng quên và tan biến vĩnh viễn là:", "Nơi đó được gọi là gì?", ["Memory Dump (Hố rác ký ức)", "Memory Cloud", "Black Hole", "Ocean"], "Memory Dump (Hố rác ký ức)", "Memory Dump là nơi ký ức phai màu và tan thành cát bụi."),
  q("io_8", "Để giúp Joy thoát khỏi đáy vực thẳm ký ức, Bing Bong đã làm gì?", "Bing Bong đã hy sinh thế nào?", ["Jumped off the rocket wagon so Joy could reach the top", "Flew away alone", "Gave Joy magic wings", "Pushed Joy down"], "Jumped off the rocket wagon so Joy could reach the top", "Bing Bong nhảy xuống khỏi xe tên lửa để giảm trọng lượng giúp Joy bay lên."),
  q("io_9", "Bài học sâu sắc nhất của Joy về vai trò của Sadness (Nỗi Buồn) là gì?", "Sadness có vai trò quan trọng gì?", ["Giúp kết nối con người, giải tỏa cảm xúc và kêu gọi sự thấu cảm từ gia đình", "Chỉ làm mọi thứ tồi tệ hơn", "Không có tác dụng gì", "Làm hỏng ký ức"], "Giúp kết nối con người, giải tỏa cảm xúc và kêu gọi sự thấu cảm từ gia đình", "Nỗi buồn là chiếc chìa khóa giúp Riley nhận được sự an ủi và thấu cảm."),
  q("io_10", "Chuyến tàu đưa những suy nghĩ và ý niệm di chuyển trong tâm trí tên là gì?", "Tên chuyến tàu là gì?", ["Train of Thought", "Express Train", "Mind Bus", "Bullet Train"], "Train of Thought", "'Train of Thought' (Đoàn tàu suy nghĩ) chạy khắp tâm trí."),
  q("io_11", "Khi Anger nổi giận tột cùng, điều gì xảy ra trên đầu nhân vật này?", "Hiện tượng gì xảy ra?", ["Flames of fire erupt from his head (Ngọn lửa bùng cháy trên đỉnh đầu)", "Water sprays out", "Smoke comes from ears only", "He turns green"], "Flames of fire erupt from his head (Ngọn lửa bùng cháy trên đỉnh đầu)", "Đầu Anger bốc cháy phừng phừng khi tức giận cực độ."),
  q("io_12", "Cảm xúc Sợ Hãi (Fear) thực chất có nhiệm vụ bảo vệ tích cực nào?", "Nhiệm vụ của Fear là gì?", ["Giữ an toàn cho Riley khỏi các nguy cơ tai nạn", "Làm Riley xấu hổ", "Làm Riley khóc", "Khiến Riley ghét thức ăn"], "Giữ an toàn cho Riley khỏi các nguy cơ tai nạn", "Fear luôn kiểm tra rủi ro để bảo vệ an toàn tính mạng cho Riley."),
  q("io_13", "Môn thể thao yêu thích mà Riley chơi từ nhỏ ở Minnesota là môn gì?", "Môn thể thao đó là gì?", ["Ice hockey (Khúc côn cầu trên băng)", "Figure skating", "Basketball", "Swimming"], "Ice hockey (Khúc côn cầu trên băng)", "Riley là một vận động viên khúc côn cầu tài năng."),
  q("io_14", "Khi Riley quyết định bỏ trốn về Minnesota, hòn đảo nào cuối cùng bị sụp đổ?", "Hòn đảo nhân cách quan trọng nào sụp đổ?", ["Family Island (Đảo Gia Đình)", "Friendship Island", "Honesty Island", "Goofball Island"], "Family Island (Đảo Gia Đình)", "Hòn đảo Gia Đình nứt toác khi Riley cắt đứt liên lạc với bố mẹ."),
  q("io_15", "Ai là cảm xúc duy nhất có thể rút chiếc bóng đèn ý tưởng bỏ trốn khỏi bảng điều khiển?", "Cảm xúc nào rút được ý tưởng?", ["Sadness", "Joy", "Anger", "Disgust"], "Sadness", "Chỉ có Sadness mới có thể chạm vào và tháo gỡ cảm xúc bế tắc của Riley."),
  q("io_16", "Viên ngọc ký ức mới xuất hiện ở đoạn kết phim có đặc điểm màu sắc nào?", "Viên ký ức đó có màu gì?", ["Blended yellow and blue (Hòa quyện giữa Vàng và Xanh lam)", "Pure gold", "Pure black", "Pure red"], "Blended yellow and blue (Hòa quyện giữa Vàng và Xanh lam)", "Ký ức trưởng thành là sự đan xen sâu sắc giữa Niềm Vui và Nỗi Buồn."),
  q("io_17", "Từ tiếng Anh nào mang nghĩa 'những năm tháng tuổi dậy thì chập chững'?", "Từ vựng tiếng Anh là:", ["Puberty", "Adulthood", "Infancy", "Toddler"], "Puberty", "'Puberty' là giai đoạn tuổi dậy thì với nút bấm cảnh báo mới trên bảng điều khiển."),
  q("io_18", "Cụm từ tiếng Anh 'go through a rough patch' có nghĩa là gì?", "Cụm từ này có nghĩa là:", ["Trải qua một giai đoạn khó khăn sóng gió", "Đi qua bãi cỏ gồ ghề", "Đang rất sung sướng", "Mua một miếng vá quần áo"], "Trải qua một giai đoạn khó khăn sóng gió", "'Go through a rough patch' là thành ngữ chỉ giai đoạn thử thách tinh thần."),
  q("io_19", "Hòn đảo tính cách ngớ ngẩn thích đùa giỡn của Riley tên là gì?", "Tên hòn đảo là gì?", ["Goofball Island", "Fashion Island", "Smart Island", "Hockey Island"], "Goofball Island", "'Goofball Island' tượng trưng cho sự hồn nhiên nhí nhảnh của trẻ thơ."),
  q("io_20", "Thông điệp tâm lý học lớn nhất mà Inside Out mang lại cho khán giả là:", "Thông điệp cảm xúc cốt lõi là:", ["Mọi cảm xúc kể cả nỗi buồn đều có giá trị và cần được tôn trọng", "Lúc nào cũng phải gượng cười vui vẻ", "Không bao giờ được khóc", "Càng tức giận càng tốt"], "Mọi cảm xúc kể cả nỗi buồn đều có giá trị và cần được tôn trọng", "Chúng ta không cần chối bỏ nỗi buồn; buồn đau là một phần tự nhiên và đẹp đẽ của sự trưởng thành.")
]);

// 11. Harry Potter and the Sorcerer's Stone (B1-B2)
setQ("harry-potter-1", [
  q("hp_1", "Lá thư nhập học trường phù thủy Hogwarts gửi cho Harry được giao bởi con vật nào?", "Những lá thư được gửi bởi:", ["Owls (Những con cú mèo)", "Cats", "Toads", "Dogs"], "Owls (Những con cú mèo)", "Cú mèo là bưu tá truyền thư của thế giới pháp thuật."),
  q("hp_2", "Sân ga bí mật để đón chuyến tàu Tốc Hành Hogwarts tại London là sân ga số mấy?", "Sân ga có số hiệu là gì?", ["Platform 9 3/4 (Chín ba phần tư)", "Platform 10", "Platform 7 1/2", "Platform 4"], "Platform 9 3/4 (Chín ba phần tư)", "Sân ga 9 3/4 tại ga King's Cross."),
  q("hp_3", "Bốn nhà ký túc xá tại lâu đài Hogwarts là:", "Tên bốn nhà là gì?", ["Gryffindor, Hufflepuff, Ravenclaw, Slytherin", "North, South, East, West", "Fire, Water, Earth, Air", "Gold, Silver, Bronze, Iron"], "Gryffindor, Hufflepuff, Ravenclaw, Slytherin", "Bốn nhà do 4 đại phù thủy sáng lập."),
  q("hp_4", "Vết sẹo huyền thoại trên trán của Harry Potter có hình dạng gì?", "Vết sẹo có hình gì?", ["A lightning bolt (Tia chớp)", "A star", "A circle", "A cross"], "A lightning bolt (Tia chớp)", "Vết sẹo hình tia chớp là tàn tích sau lời nguyền chết chóc Avada Kedavra."),
  q("hp_5", "Con phố mua sắm sầm uất dành riêng cho giới phù thủy tại London tên là gì?", "Tên con hẻm phép thuật là gì?", ["Diagon Alley (Hẻm Xéo)", "Knockturn Alley", "Baker Street", "Wall Street"], "Diagon Alley (Hẻm Xéo)", "Hẻm Xéo là nơi Harry mua đũa phép, vạc đồng và sách thần chú."),
  q("hp_6", "Ngân hàng uy nghiêm được điều hành bởi loài yêu tinh (Goblins) tên là gì?", "Tên ngân hàng là gì?", ["Gringotts Wizarding Bank", "Hogwarts Bank", "London Bank", "Royal Bank"], "Gringotts Wizarding Bank", "Gringotts là nơi an toàn nhất thế giới phù thủy sau Hogwarts."),
  q("hp_7", "Người thợ chế tạo đũa phép tài ba bậc thầy tại Hẻm Xéo tên là gì?", "Tên tiệm đũa phép là gì?", ["Ollivanders", "Madam Malkin's", "Flourish and Blotts", "Weasleys' Wizard Wheezes"], "Ollivanders", "Gia tộc Ollivander chế tác đũa phép từ năm 382 trước Công Nguyên."),
  q("hp_8", "Lõi của cây đũa phép chọn Harry chứa lông của sinh vật huyền bí nào?", "Lõi đũa phép của Harry chứa gì?", ["Phoenix feather (Lông đuôi chim Phượng hoàng)", "Dragon heartstring", "Unicorn hair", "Veela hair"], "Phoenix feather (Lông đuôi chim Phượng hoàng)", "Lông đuôi chim phượng hoàng Fawkes - cùng một con cho lông đũa phép của Voldemort."),
  q("hp_9", "Chú chó khổng lồ ba đầu canh gác cửa sập dưới chân cầu thang tên là gì?", "Tên chú chó ba đầu của Hagrid là gì?", ["Fluffy", "Fang", "Norbert", "Buckbeak"], "Fluffy", "Fluffy sẽ lăn ra ngủ say sưa mỗi khi nghe thấy tiếng đàn du dương."),
  q("hp_10", "Vị giáo sư dạy môn Độc Dược bí ẩn có mái tóc đen dầu là ai?", "Tên của giáo sư là gì?", ["Severus Snape", "Minerva McGonagall", "Albus Dumbledore", "Quirinus Quirrell"], "Severus Snape", "Giáo sư Severus Snape - chủ nhiệm nhà Slytherin."),
  q("hp_11", "Trò chơi thể thao vua trên không bằng chổi bay của giới phù thủy gọi là:", "Môn thể thao đó là gì?", ["Quidditch", "Cricket", "Polo", "Rugby"], "Quidditch", "Quidditch với quả bóng Vàng Snitch có cánh bay lượn."),
  q("hp_12", "Vị trí thi đấu của Harry trong đội Quidditch nhà Gryffindor là gì?", "Harry chơi ở vị trí nào?", ["Seeker (Tầm thủ)", "Keeper", "Chaser", "Beater"], "Seeker (Tầm thủ)", "Harry là Tầm thủ trẻ tuổi nhất thế kỷ của nhà Gryffindor."),
  q("hp_13", "Quả bóng vàng nhỏ có cánh bay siêu nhanh mang lại 150 điểm kết thúc trận đấu là:", "Quả bóng đó tên là gì?", ["Golden Snitch", "Quaffle", "Bludger", "Silver Ball"], "Golden Snitch", "Quả bóng Golden Snitch."),
  q("hp_14", "Chiếc gương ma thuật phản chiếu ước muốn sâu thẳm nhất trong tim người nhìn tên là:", "Tên chiếc gương là gì?", ["Mirror of Erised", "Mirror of Truth", "Mirror of Future", "Mirror of Gold"], "Mirror of Erised", "Gương Erised ('Desire' viết ngược lại) soi chiếu khát vọng tâm can."),
  q("hp_15", "Người thực sự giấu gương mặt chúa tể Voldemort sau chiếc khăn quấn đầu là ai?", "Kẻ bị Voldemort ký sinh là ai?", ["Professor Quirrell", "Professor Snape", "Filch", "Lucius Malfoy"], "Professor Quirrell", "Giáo sư Quirrell dạy môn Phòng chống Nghệ thuật Hắc ám."),
  q("hp_16", "Câu thần chú làm bay đồ vật mà Hermione sửa cách phát âm cho Ron là gì?", "Thần chú nâng vật thể bay lên là:", ["Wingardium Leviosa", "Alohomora", "Lumos", "Expelliarmus"], "Wingardium Leviosa", "'It's levi-O-sa, not levio-SA!'"),
  q("hp_17", "Bàn cờ phù thủy khổng lồ nơi Ron Weasley thể hiện tài năng chiến thuật xuất chúng là:", "Trò chơi cờ đó là gì?", ["Wizard's Chess", "Checkers", "Monopoly", "Scrabble"], "Wizard's Chess", "Cờ Phù Thủy với các quân cờ sống động đập nát nhau."),
  q("hp_18", "Tại sao giáo sư Quirrell không thể chạm vào da thịt của Harry mà không bị thiêu cháy?", "Lực lượng nào bảo vệ Harry?", ["Tình yêu thương và sự hy sinh của người mẹ Lily Potter lưu truyền trong máu", "Phép thuật của đũa phép", "Nước thánh", "Áo choàng tàng hình"], "Tình yêu thương và sự hy sinh của người mẹ Lily Potter lưu truyền trong máu", "Dumbledore giải thích: Tình yêu để lại dấu ấn vô hình không ma thuật đen nào phá vỡ nổi."),
  q("hp_19", "Cậu bé Neville Longbottom nhận được 10 điểm quyết định giúp Gryffindor vô địch vì:", "Neville được thưởng điểm vì điều gì?", ["Lòng dũng cảm dám đứng lên ngăn cản bạn bè làm điều sai", "Bắt được quả bóng vàng", "Nấu độc dược giỏi", "Học thuộc bài"], "Lòng dũng cảm dám đứng lên ngăn cản bạn bè làm điều sai", "Dumbledore khen ngợi: Đứng lên chống lại bạn bè đòi hỏi lòng quả cảm lớn lao."),
  q("hp_20", "Từ ngữ nào chỉ những người sinh ra trong gia đình bình thường không biết phép thuật?", "Người không có dòng máu phù thủy là:", ["Muggle", "Wizard", "Squib", "Elf"], "Muggle", "'Muggle' là từ vựng chỉ người phàm trần trong vũ trụ Harry Potter.")
]);

// 12. Forrest Gump (B1-B2)
setQ("forrest-gump", [
  q("fg_1", "Câu danh ngôn nổi tiếng nhất mà mẹ Forrest thường nói về cuộc đời là gì?", "Life is like a box of _______.", ["chocolates", "cookies", "apples", "books"], "chocolates", "'Life was like a box of chocolates. You never know what you're gonna get.'"),
  q("fg_2", "Forrest Gump sinh ra và lớn lên tại thị trấn Greenbow thuộc tiểu bang nào của nước Mỹ?", "Forrest lớn lên ở bang nào?", ["Alabama", "Texas", "California", "Florida"], "Alabama", "Greenbow, Alabama là quê hương của Forrest."),
  q("fg_3", "Người con gái mà Forrest yêu tha thiết suốt cả cuộc đời tên là gì?", "Tên người bạn gái tri kỷ là gì?", ["Jenny Curran", "Peggy", "Mary", "Sarah"], "Jenny Curran", "Jenny là người bạn đầu tiên cho Forrest ngồi cùng trên xe buýt trường học."),
  q("fg_4", "Khi lũ trẻ bắt nạt ném đá vào Forrest thời thơ ấu, Jenny đã hét lên câu gì?", "Jenny shouted: 'Run, Forrest, _______!'", ["run", "hide", "fight", "jump"], "run", "'Run, Forrest! Run!' là tiếng reo vang giúp Forrest bứt đứt nẹp sắt ở chân."),
  q("fg_5", "Nhờ khả năng chạy nhanh như gió, Forrest được tuyển thẳng vào đại học để chơi môn gì?", "Forrest chơi môn thể thao nào?", ["College football (Bóng bầu dục)", "Basketball", "Baseball", "Tennis"], "College football (Bóng bầu dục)", "Forrest trở thành ngôi sao bóng bầu dục của Đại học Alabama dưới thời HLV Bear Bryant."),
  q("fg_6", "Người bạn thân nhất của Forrest trong quân ngũ có ước mơ mở công ty tàu đánh tôm là ai?", "Tên người bạn da đen thân thiết là gì?", ["Bubba (Benjamin Buford Blue)", "Dan", "Sam", "Joe"], "Bubba (Benjamin Buford Blue)", "Bubba kể vanh vách hàng chục món ăn chế biến từ tôm biển."),
  q("fg_7", "Người trung đội trưởng bị mất hai chân trong chiến tranh Việt Nam được Forrest cứu sống là ai?", "Tên vị trung đội trưởng là gì?", ["Lieutenant Dan Taylor", "General Patton", "Captain Miller", "Sergeant Barnes"], "Lieutenant Dan Taylor", "Trung úy Dan (Lieutenant Dan) mang số phận bi tráng nhưng kiên cường."),
  q("fg_8", "Forrest đã nhận phần thưởng cao quý nào từ Tổng thống Mỹ vì lòng dũng cảm cứu đồng đội?", "Huân chương quân đội đó là gì?", ["Medal of Honor (Huân chương Danh dự)", "Purple Heart only", "Bronze Star only", "Silver Cross"], "Medal of Honor (Huân chương Danh dự)", "Tổng thống Lyndon B. Johnson đã trao tặng Huân chương Danh dự cho Forrest."),
  q("fg_9", "Trong thời gian tĩnh dưỡng tại bệnh viện quân y, Forrest đã phát hiện ra tài năng thiên bẩm ở môn gì?", "Forrest chơi môn thể thao nào cực giỏi?", ["Ping-pong (Table tennis)", "Chess", "Golf", "Boxing"], "Ping-pong (Table tennis)", "Forrest luyện bóng bàn không rời mắt khỏi quả bóng và được cử đi thi đấu ngoại giao tại Trung Quốc."),
  q("fg_10", "Tên con tàu đánh tôm mà Forrest và Trung úy Dan cùng nhau lèo lái là gì?", "Tên con tàu đánh tôm là gì?", ["Jenny", "Bubba", "Alabama", "Freedom"], "Jenny", "Forrest đặt tên con tàu đánh tôm là 'Jenny' - cái tên đẹp nhất trần đời."),
  q("fg_11", "Trận bão biển hung dữ nào đã phá hủy toàn bộ các tàu bè khác, giúp tàu của Forrest độc quyền tôm?", "Cơn bão biển đó tên là gì?", ["Hurricane Carmen", "Hurricane Katrina", "Typhoon Haiyan", "Storm Sandy"], "Hurricane Carmen", "Cơn bão Carmen biến công ty Bubba Gump Shrimp thành đế chế khổng lồ."),
  q("fg_12", "Trung úy Dan đã dùng tiền lợi nhuận từ tôm để đầu tư vào 'công ty trái cây' nào?", "Công ty trái cây mà Forrest nhắc đến thực chất là gì?", ["Apple Inc. (Tập đoàn công nghệ Apple)", "Microsoft", "Banana Republic", "Orange Telecom"], "Apple Inc. (Tập đoàn công nghệ Apple)", "Forrest ngây thơ nói: 'He got me invested in some kind of fruit company.'"),
  q("fg_13", "Sau khi Jenny đột ngột rời đi, Forrest đã bắt đầu hành động kỳ lạ nào không ngừng nghỉ?", "Forrest đã làm gì suốt hơn ba năm?", ["He ran across America from coast to coast (Chạy bộ xuyên nước Mỹ)", "Sailed around the world", "Climbed Mount Everest", "Stayed in bed"], "He ran across America from coast to coast (Chạy bộ xuyên nước Mỹ)", "Forrest cứ thế chạy bộ xuyên bờ đông sang bờ tây nước Mỹ và truyền cảm hứng cho hàng triệu người."),
  q("fg_14", "Khi mọi người chạy theo và hỏi Forrest tại sao anh chạy, Forrest trả lời thế nào?", "Lý do chạy của Forrest là gì?", ["I just felt like running. (Tôi chỉ cảm thấy thích chạy vậy thôi.)", "For world peace.", "For money.", "For fitness."], "I just felt like running. (Tôi chỉ cảm thấy thích chạy vậy thôi.)", "Forrest không chạy vì mục đích chính trị nào, chỉ đơn giản là lắng nghe trái tim."),
  q("fg_15", "Forrest ngồi trên băng ghế công viên ở thành phố Savannah để kể chuyện cho ai nghe?", "Forrest kể chuyện cho ai?", ["Những người khách qua đường ngẫu nhiên chờ xe buýt", "Các phóng viên", "Thẩm phán", "Cảnh sát"], "Những người khách qua đường ngẫu nhiên chờ xe buýt", "Khung cảnh kinh điển mở đầu và kết thúc trên chiếc ghế chờ xe buýt."),
  q("fg_16", "Câu nói giản dị mà mẹ Forrest dạy cậu về thước đo sự ngu ngốc là gì?", "Stupid is as _______ does.", ["stupid", "smart", "lazy", "evil"], "stupid", "'Stupid is as stupid does' (Kẻ ngốc là kẻ làm những điều ngu xuẩn)."),
  q("fg_17", "Jenny qua đời vì căn bệnh hiểm nghèo thời kỳ đó, để lại cho Forrest điều gì quý giá nhất?", "Jenny để lại cho Forrest:", ["A young son named Forrest Gump Jr.", "A million dollars", "A big house", "A letter"], "A young son named Forrest Gump Jr.", "Cậu con trai bé bỏng thông minh giống hệt bố."),
  q("fg_18", "Forrest xúc động rơi nước mắt khi biết con trai mình:", "Forrest lo lắng và hạnh phúc khi biết con:", ["Is very smart and not slow like him (Rất thông minh chứ không bị chậm chạp)", "Can run fast", "Likes shrimp", "Plays ping pong"], "Is very smart and not slow like him (Rất thông minh chứ không bị chậm chạp)", "Khoảnh khắc người cha hỏi: 'Is he smart?' nghẹn ngào tình phụ tử."),
  q("fg_19", "Hình ảnh biểu tượng xuyên suốt mở đầu và kết thúc bộ phim bay bổng trong làn gió là:", "Vật thể biểu tượng đó là gì?", ["A white feather (Một chiếc lông vũ trắng)", "A red leaf", "A yellow butterfly", "A paper plane"], "A white feather (Một chiếc lông vũ trắng)", "Chiếc lông vũ trắng bay lượn tượng trưng cho sự trôi dạt định mệnh và tâm hồn thánh thiện."),
  q("fg_20", "Bài học nhân sinh vĩ đại nhất từ cuộc đời của Forrest Gump là gì?", "Bài học lớn nhất là gì?", ["Lòng chân thành, tử tế và kiên trì không vụ lợi có thể làm nên những điều kỳ diệu", "Chỉ người thông minh mới thành công", "Tiền bạc là trên hết", "Trốn tránh xã hội"], "Lòng chân thành, tử tế và kiên trì không vụ lợi có thể làm nên những điều kỳ diệu", "Một trái tim nhân hậu thuần khiết sẽ luôn chạm tới sự vĩ đại đích thực.")
]);

console.log("Saving full question banks 10-12...");
module.exports = { setQ, q };
