const { setQ, q } = require('./make_quiz_dataset.cjs');

// 16. Soul (B1-B2)
setQ("soul", [
  q("sl_1", "Joe Gardner là một thầy giáo dạy môn gì tại trường trung học ở New York?", "Joe dạy môn gì?", ["Middle school band / music (Âm nhạc)", "Math", "History", "Science"], "Middle school band / music (Âm nhạc)", "Joe là giáo viên dạy dàn nhạc thiếu nhi nhưng luôn khao khát trở thành nghệ sĩ dương cầm jazz chuyên nghiệp."),
  q("sl_2", "Cơ hội đổi đời gõ cửa khi Joe được mời thử việc chơi piano cho ban nhạc của ai?", "Nữ nghệ sĩ kèn saxophone huyền thoại tên là gì?", ["Dorothea Williams", "Ella Fitzgerald", "Billie Holiday", "Nina Simone"], "Dorothea Williams", "Dorothea Williams là nữ huyền thoại nhạc jazz tại câu lạc bộ Half Note."),
  q("sl_3", "Ngay sau buổi thử giọng thành công, bi kịch gì đã xảy ra với Joe trên đường phố?", "Joe bị tai nạn gì?", ["Fell into an open manhole (Rơi xuống một miệng cống mở)", "Hit by a car", "Lost his wallet", "Slipped on ice"], "Fell into an open manhole (Rơi xuống một miệng cống mở)", "Vì mải nói chuyện điện thoại vui sướng, Joe đã sẩy chân ngã xuống cống và hôn mê."),
  q("sl_4", "Cõi giới nơi các linh hồn mới được tôi luyện tính cách trước khi đến Trái Đất tên là gì?", "Cõi giới đó là gì?", ["The Great Before (Cõi Trước)", "The Great Beyond", "Earth", "Limbo"], "The Great Before (Cõi Trước)", "Nơi ươm mầm các linh hồn trẻ thơ nhận diện tính cách và tia sáng đam mê (spark)."),
  q("sl_5", "Con đường băng chuyền đưa các linh hồn đã qua đời đi về cõi vĩnh hằng tên là gì?", "Con đường ánh sáng đó là gì?", ["The Great Beyond (Cõi Sau)", "The Great Before", "Stairway to Heaven", "Milky Way"], "The Great Beyond (Cõi Sau)", "Joe đã hoảng loạn chạy ngược lại khỏi The Great Beyond để cố níu giữ cơ hội sống."),
  q("sl_6", "Linh hồn bướng bỉnh đã từ chối xuống Trái Đất hàng ngàn năm mang số hiệu bao nhiêu?", "Linh hồn bất trị đó là ai?", ["Number 22", "Number 7", "Number 1", "Number 100"], "Number 22", "Linh hồn 22 đã làm nản lòng hàng loạt người cố vấn vĩ đại như Gandhi, Mẹ Teresa, Abraham Lincoln."),
  q("sl_7", "Người kế toán vũ trụ nghiêm khắc chuyên đếm các linh hồn đi sang Cõi Sau tên là gì?", "Tên của nhân vật kế toán là gì?", ["Terry", "Jerry", "Gary", "Perry"], "Terry", "Terry luôn bị ám ảnh bởi việc số lượng linh hồn phải khớp tuyệt đối không được thiếu một ai."),
  q("sl_8", "Các thực thể trừu tượng nhiều chiều quản lý Cõi Trước đều có chung một cái tên là gì?", "Họ đều tự xưng là:", ["Jerry", "Terry", "Mary", "Larry"], "Jerry", "Tất cả các cố vấn tâm linh cao cấp ở Cõi Trước đều tự gọi mình là Jerry."),
  q("sl_9", "Khi rơi trở lại Trái Đất, linh hồn của 22 bị nhập nhầm vào cơ thể của sinh vật nào?", "22 nhập vào ai?", ["Joe Gardner's human body", "A therapy cat named Mr. Mittens (Chú mèo trị liệu)", "A dog", "A bird"], "A therapy cat named Mr. Mittens (Chú mèo trị liệu)", "22 nhập vào thân xác của Joe, còn linh hồn Joe lại bị mắc kẹt trong thân xác chú mèo lông xù!"),
  q("sl_10", "Món ăn đường phố đầu tiên mà 22 nếm thử ở New York khiến cô mê mẩn là gì?", "Món ăn đó là gì?", ["New York style pizza", "Hot dog", "Burger", "Ice cream"], "New York style pizza", "Một lát bánh pizza nóng hổi giúp 22 lần đầu cảm nhận được sự tuyệt diệu của vị giác."),
  q("sl_11", "Vật rơi từ cây xuống lòng bàn tay 22 tượng trưng cho vẻ đẹp tinh tế của sự sống là gì?", "Vật thể đó là gì?", ["A spinning helicopter seed (Hạt chò nâu bay trong gió)", "An apple", "A flower", "A coin"], "A spinning helicopter seed (Hạt chò nâu bay trong gió)", "Hạt chò xoay tít rơi xuống là khoảnh khắc 22 nhận ra ý nghĩa diệu kỳ của việc được sống."),
  q("sl_12", "Cuộc trò chuyện sâu sắc của 22 (trong thân xác Joe) với người thợ cạo tên Dez diễn ra ở đâu?", "Cuộc đối thoại diễn ra ở đâu?", ["A local barbershop (Tiệm cắt tóc)", "A hospital", "A restaurant", "A taxi"], "A local barbershop (Tiệm cắt tóc)", "Dez chia sẻ rằng anh từng muốn làm bác sĩ thú y nhưng vẫn tìm thấy niềm vui trọn vẹn trong nghề thợ cạo."),
  q("sl_13", "Mẹ của Joe là thợ may áo vest luôn phản đối ước mơ của con trai vì lý do gì?", "Mẹ Joe lo lắng điều gì?", ["Nghề nhạc jazz bấp bênh không có lương hưu và bảo hiểm y tế ổn định", "Bà ghét âm nhạc", "Bà muốn Joe đi lính", "Bà muốn Joe rời New York"], "Nghề nhạc jazz bấp bênh không có lương hưu và bảo hiểm y tế ổn định", "Mẹ Libba muốn Joe nhận vị trí giáo viên toàn thời gian để có sự ổn định tài chính."),
  q("sl_14", "Khi đam mê bị biến thành nỗi ám ảnh mù quáng, các linh hồn sẽ rơi vào trạng thái nào?", "Họ trở thành sinh vật gì?", ["Lost souls (Những linh hồn lạc lối phủ đầy cát đen u uất)", "Monsters", "Angels", "Ghosts"], "Lost souls (Những linh hồn lạc lối phủ đầy cát đen u uất)", "Những người quá ám ảnh hoặc trầm cảm bị giam cầm trong lớp vỏ cát đen."),
  q("sl_15", "Đội thuyền hoa tiêu bay lượn giữa ranh giới thực tại và hư vô do ai chỉ huy?", "Thuyền trưởng lập dị tên là gì?", ["Moonwind (Gió Trăng)", "Sunstorm", "Starlight", "Skywalker"], "Moonwind (Gió Trăng)", "Moonwind là người xoay biển quảng cáo ngoài đời thực khi đạt trạng thái thăng hoa thiền định."),
  q("sl_16", "Câu chuyện ngụ ngôn về con cá tìm kiếm đại dương do Dorothea kể nhằm thức tỉnh Joe điều gì?", "Ý nghĩa câu chuyện ngụ ngôn là:", ["Chúng ta thường mải mê theo đuổi một mục đích xa vời mà không nhận ra mình đang sống trong chính điều kỳ diệu đó mỗi ngày", "Cá phải sống dưới nước", "Đại dương rất rộng lớn", "Nên đi bơi mỗi ngày"], "Chúng ta thường mải mê theo đuổi một mục đích xa vời mà không nhận ra mình đang sống trong chính điều kỳ diệu đó mỗi ngày", "Sau buổi biểu diễn để đời, Joe nhận ra cuộc sống không thay đổi thần kỳ như anh tưởng."),
  q("sl_17", "Khái niệm 'tia sáng' (Spark) ở Cõi Trước thực chất không phải là mục đích cuộc đời mà là:", "Bản chất thực sự của 'spark' là gì?", ["Sự sẵn sàng đón nhận và tận hưởng trọn vẹn từng khoảnh khắc của sự sống", "Tài năng thiên bẩm để kiếm tiền", "Danh vọng vĩ đại", "Một bằng cấp học vấn"], "Sự sẵn sàng đón nhận và tận hưởng trọn vẹn từng khoảnh khắc của sự sống", "Jerry giải thích: 'A spark isn't a soul's purpose. It's just when you're ready to come and live.'"),
  q("sl_18", "Hành động cao đẹp nhất của Joe khi trao lại huy hiệu sự sống cho linh hồn 22 là gì?", "Joe đã làm gì?", ["Tự nguyện trao cơ hội được sống cho 22 và đồng hành cùng cô bé đến ngưỡng cửa Trái Đất", "Giành lấy chiếc huy hiệu cho riêng mình", "Đẩy 22 vào Cõi Sau", "Trốn thoát một mình"], "Tự nguyện trao cơ hội được sống cho 22 và đồng hành cùng cô bé đến ngưỡng cửa Trái Đất", "Joe nhận ra 22 xứng đáng được sinh ra để trải nghiệm thế giới tuyệt đẹp này."),
  q("sl_19", "Khi các vị thần Jerry ban cho Joe cơ hội thứ hai được tái sinh, họ hỏi anh sẽ làm gì với cuộc đời mình?", "Joe đã trả lời câu nói bất hủ nào?", ["I'm going to live every minute of it. (Tôi sẽ sống trọn vẹn từng phút giây của nó.)", "I will just play piano.", "I will make millions.", "I don't know."], "I'm going to live every minute of it. (Tôi sẽ sống trọn vẹn từng phút giây của nó.)", "Một kết thúc xúc động thấu cảm về ý nghĩa của từng hơi thở cuộc sống."),
  q("sl_20", "Bài học triết học sâu xa nhất của Pixar Soul gửi gắm tới chúng ta là gì?", "Bài học nhân sinh của phim là:", ["Ý nghĩa cuộc đời không nằm ở đích đến danh vọng mà nằm ở việc trân trọng từng khoảnh khắc bình dị hiện tại", "Chỉ những người nổi tiếng mới có giá trị", "Không nên theo đuổi đam mê", "Cái chết là điều đáng sợ nhất"], "Ý nghĩa cuộc đời không nằm ở đích đến danh vọng mà nằm ở việc trân trọng từng khoảnh khắc bình dị hiện tại", "Hạnh phúc đích thực hiện diện ngay trong tiếng lá xào xạc, miếng bánh ngon và sự kết nối giữa người với người.")
]);

// 17. Suits (C1-C2)
setQ("suits", [
  q("st_1", "Mike Ross có năng lực trí tuệ bẩm sinh siêu phàm nào giúp anh qua mặt các kỳ thi luật?", "Năng lực đặc biệt của Mike là gì?", ["Eidetic / Photographic memory (Trí nhớ nhiếp ảnh nhớ vĩnh viễn mọi thứ từng đọc)", "Telepathy", "Time travel", "Hypnosis"], "Eidetic / Photographic memory (Trí nhớ nhiếp ảnh nhớ vĩnh viễn mọi thứ từng đọc)", "Mike có thể nhớ chính xác từng điều luật và trang sách chỉ sau một lần liếc qua."),
  q("st_2", "Công ty luật danh giá hàng đầu New York nơi Harvey Specter làm việc là:", "Tên hãng luật là gì?", ["Pearson Hardman", "Skadden Arps", "Baker McKenzie", "Latham & Watkins"], "Pearson Hardman", "Hãng luật Pearson Hardman do Jessica Pearson và Daniel Hardman sáng lập."),
  q("st_3", "Quy tắc tuyển dụng nghiêm ngặt bất di bất dịch của Pearson Hardman đối với luật sư là:", "Công ty chỉ tuyển dụng những ai?", ["Only graduates from Harvard Law School (Chỉ tuyển sinh viên tốt nghiệp trường Luật Harvard)", "Chỉ tuyển người có 10 năm kinh nghiệm", "Chỉ tuyển người New York", "Chỉ tuyển con cháu chính trị gia"], "Only graduates from Harvard Law School (Chỉ tuyển sinh viên tốt nghiệp trường Luật Harvard)", "Chính quy định ngặt nghèo này đã buộc Harvey và Mike phải duy trì lời nói dối thế kỷ."),
  q("st_4", "Mike Ross tình cờ bước vào phòng phỏng vấn của Harvey Specter trong hoàn cảnh éo le nào?", "Mike đang làm gì lúc đó?", ["Đang chạy trốn cảnh sát với chiếc vali chứa đầy cần sa (marijuana)", "Đi xin việc bình thường", "Đi giao bánh pizza", "Làm phóng viên"], "Đang chạy trốn cảnh sát với chiếc vali chứa đầy cần sa (marijuana)", "Mike vô tình trốn vào phòng hội nghị khách sạn và gây ấn tượng kinh ngạc cho Harvey."),
  q("st_5", "Câu châm ngôn nổi tiếng của Harvey Specter khi đối diện với tỷ lệ cược bất lợi là:", "I don't play the odds, I play the _______.", ["man", "game", "cards", "dice"], "man", "'I don't play the odds, I play the man.' (Tôi không cược vào xác suất may rủi, tôi nắm thóp chính con người)."),
  q("st_6", "Bí thư trưởng kiêm 'linh hồn' của hãng luật, người luôn biết tất cả mọi bí mật là ai?", "Tên của thư ký thông minh sắc sảo là gì?", ["Donna Paulsen", "Rachel Zane", "Jessica Pearson", "Katrina Bennett"], "Donna Paulsen", "Donna Paulsen với câu nói thương hiệu: 'I'm Donna. I know everything.'"),
  q("st_7", "Người cộng sự cấp cao đam mê nhạc kịch, nuôi mèo và luôn có mối quan hệ thù-bạn với Harvey là ai?", "Tên vị luật sư lập dị đầy tài năng này là gì?", ["Louis Litt", "Trevor Evans", "Robert Zane", "Sean Cahill"], "Louis Litt", "Louis Litt với câu khẩu hiệu dằn mặt: 'You just got Litt up!'"),
  q("st_8", "Cô trợ lý pháp lý xinh đẹp và tài giỏi sau này trở thành vợ của Mike Ross là ai?", "Tên của nhân vật do Meghan Markle thủ vai là gì?", ["Rachel Zane", "Jenny Griffith", "Tess", "Claire"], "Rachel Zane", "Rachel Zane là con gái của đại luật sư Robert Zane lẫy lừng."),
  q("st_9", "Bà trùm quản lý điều hành đứng đầu Pearson Hardman đầy quyền uy và bản lĩnh là ai?", "Tên của nữ quản lý điều hành là gì?", ["Jessica Pearson", "Donna Paulsen", "Anita Gibbs", "Gretchen Bodinski"], "Jessica Pearson", "Jessica Pearson là người dẫn dắt công ty vượt qua vô số cuộc chiến thâu tóm."),
  q("st_10", "Louis Litt thích nhất liệu pháp thư giãn nào để phục hồi năng lượng và xả stress?", "Sở thích đặc trưng của Louis là gì?", ["Mudding (Ngâm mình trong bùn khoáng nóng)", "Golf", "Running", "Karaoke"], "Mudding (Ngâm mình trong bùn khoáng nóng)", "Louis coi việc ngâm bùn khoáng là đỉnh cao của sự hưởng thụ tinh thần."),
  q("st_11", "Khi Harvey đối mặt với tình thế bế tắc không có lối thoát (no-win situation), phương châm của anh là:", "Win a no-win situation by _______.", ["rewriting the rules (Viết lại luật chơi)", "giving up", "crying", "running away"], "rewriting the rules (Viết lại luật chơi)", "Harvey không bao giờ chấp nhận thất bại mà luôn chủ động xoay chuyển cục diện."),
  q("st_12", "Louis Litt phát hiện ra sự thật Mike Ross chưa từng học trường luật Harvard từ manh mối nào?", "Manh mối lật tẩy Mike là gì?", ["Chiếc chìa khóa danh dự của hội Order of the Coif tại Harvard", "Tấm ảnh tốt nghiệp", "Học bạ giả", "Lời khai của Trevor"], "Chiếc chìa khóa danh dự của hội Order of the Coif tại Harvard", "Harvard Law School không trao chìa khóa Order of the Coif, và Mike đã không biết điều đó."),
  q("st_13", "Để bảo vệ công ty và những người bạn bè, Mike Ross đã đưa ra quyết định dũng cảm nào?", "Hành động của Mike tại tòa là gì?", ["Nhận tội và chấp nhận đi tù hai năm để đổi lấy sự miễn tố cho Harvey và Jessica", "Đổ tội cho Harvey", "Bỏ trốn ra nước ngoài", "Hối lộ công tố viên"], "Nhận tội và chấp nhận đi tù hai năm để đổi lấy sự miễn tố cho Harvey và Jessica", "Mike chấp nhận hy sinh bản thân để bảo vệ những người đã cưu mang mình."),
  q("st_14", "Nữ công tố viên liên bang sắt đá kiên quyết đưa Mike Ross vào tù tên là gì?", "Tên của nữ công tố viên là gì?", ["Anita Gibbs", "Cameron Dennis", "Sean Cahill", "Eric Woodall"], "Anita Gibbs", "Anita Gibbs là đối thủ pháp lý đáng sợ nhất mà Harvey từng đối đầu."),
  q("st_15", "Môn thể thao quyền anh (boxing) mà Harvey thường tập luyện phản ánh điều gì về phong cách hành nghề của anh?", "Ý nghĩa của việc Harvey tập quyền anh là:", ["Tính chiến đấu cao, luôn tấn công trực diện và sẵn sàng chịu đòn để tung cú đấm quyết định", "Chỉ để giảm cân", "Bắt chước người khác", "Vì không có việc gì làm"], "Tính chiến đấu cao, luôn tấn công trực diện và sẵn sàng chịu đòn để tung cú đấm quyết định", "Harvey là một võ sĩ trên sàn đấu pháp lý: sắc bén, dứt khoát và không khoan nhượng."),
  q("st_16", "Bộ sưu tập đĩa than đồ sộ trong văn phòng của Harvey thể hiện gu thẩm mỹ nào của anh?", "Bộ sưu tập của Harvey gồm thể loại nhạc gì?", ["Classic Jazz, Soul, and Blues vinyl records", "Heavy metal", "K-pop", "EDM"], "Classic Jazz, Soul, and Blues vinyl records", "Harvey nghe đĩa than nhạc jazz và blues trên chiếc máy quay đĩa cổ điển đắt tiền."),
  q("st_17", "Sau khi ra tù, Mike Ross tiếp tục con đường sự nghiệp pháp lý nào?", "Mike chuyển sang làm công việc gì?", ["Làm việc cho một trung tâm trợ giúp pháp lý miễn phí (Legal Clinic) vì người nghèo", "Bỏ nghề luật", "Mở nhà hàng", "Đi bán xe hơi"], "Làm việc cho một trung tâm trợ giúp pháp lý miễn phí (Legal Clinic) vì người nghèo", "Mike quay lại với lý tưởng ban đầu là bảo vệ những người yếu thế không có tiền thuê luật sư."),
  q("st_18", "Từ thuật ngữ pháp lý 'subpoena' trong tiếng Anh có nghĩa là gì?", "What is a 'subpoena'?", ["Trát đòi hầu tòa hoặc trát nộp chứng cứ bắt buộc", "Hợp đồng mua bán", "Đơn xin nghỉ việc", "Biên lai thanh toán"], "Trát đòi hầu tòa hoặc trát nộp chứng cứ bắt buộc", "'Subpoena' là lệnh cưỡng chế tư pháp buộc đương sự phải ra hầu tòa hoặc nộp tài liệu."),
  q("st_19", "Cụm từ tiếng Anh 'attorney-client privilege' có hiệu lực pháp lý quan trọng nào?", "Đặc quyền luật sư - thân chủ mang ý nghĩa gì?", ["Bảo mật tuyệt đối mọi thông tin trao đổi giữa luật sư và khách hàng trước tòa", "Cho phép luật sư nói dối", "Khách hàng không phải trả tiền", "Luật sư được quyền làm chứng chống lại khách hàng"], "Bảo mật tuyệt đối mọi thông tin trao đổi giữa luật sư và khách hàng trước tòa", "Một nguyên tắc nền tảng của hệ thống tư pháp Mỹ."),
  q("st_20", "Bài học lớn nhất về đạo đức nghề nghiệp và tình nghĩa con người trong Suits là gì?", "Giá trị cốt lõi của Suits là:", ["Lòng trung thành với đồng đội và tinh thần phụng sự công lý cao hơn danh lợi tiền tài", "Chiến thắng bằng mọi giá bất chấp thủ đoạn", "Chỉ quan tâm bản thân", "Tiền bạc là thước đo duy nhất"], "Lòng trung thành với đồng đội và tinh thần phụng sự công lý cao hơn danh lợi tiền tài", "Bộ phim chứng minh rằng lòng trung thành và tình bạn tri kỷ là thứ tài sản quý giá nhất.")
]);

console.log("Saving full question banks 16-17...");
module.exports = { setQ, q };
