const { setQ, q } = require('./make_quiz_dataset.cjs');

// 21. The Crown (C1-C2)
setQ("the-crown", [
  q("cr_1", "Công chúa Elizabeth kết hôn với ai vào năm 1947 tại Tu viện Westminster?", "Chồng của Nữ hoàng Elizabeth II là ai?", ["Philip Mountbatten (Hoàng thân Philip - Công tước xứ Edinburgh)", "Lord Mountbatten", "Peter Townsend", "Antony Armstrong-Jones"], "Philip Mountbatten (Hoàng thân Philip - Công tước xứ Edinburgh)", "Hoàng thân Philip - người bạn đời đồng hành cùng Nữ hoàng hơn 70 năm."),
  q("cr_2", "Tin tức Vua cha George VI qua đời ập đến khi Công chúa Elizabeth đang công du tại quốc gia nào?", "Cô đang ở đâu khi trở thành Nữ hoàng?", ["Kenya (Châu Phi)", "Australia", "Canada", "India"], "Kenya (Châu Phi)", "Elizabeth đang ở khách sạn trên ngọn cây Treetops tại Kenya và lập tức bay về London."),
  q("cr_3", "Lời dặn dò tối hậu của Thái Hoàng thái hậu Mary gửi cho Elizabeth khi lên ngôi là gì?", "The crown must win. Must always _______.", ["win", "compromise", "lose", "retreat"], "win", "'Vương trượng và vương miện phải chiến thắng. Luôn luôn phải chiến thắng mọi toan tính của cá nhân.'"),
  q("cr_4", "Vị Thủ tướng Anh huyền thoại thời kỳ đầu trị vì của Nữ hoàng Elizabeth II là ai?", "Thủ tướng thời chiến vĩ đại là ai?", ["Winston Churchill", "Anthony Eden", "Harold Macmillan", "Margaret Thatcher"], "Winston Churchill", "Ngài Winston Churchill với bài học uy nghiêm về khoảng cách giữa quân vương và dân chúng."),
  q("cr_5", "Bi kịch tình yêu của Công chúa Margaret (em gái Nữ hoàng) bắt nguồn từ việc cô muốn kết hôn với ai?", "Người tình của Margaret là ai?", ["Group Captain Peter Townsend (Một phi công đã ly dị vợ)", "Lord Altrincham", "Billy Graham", "Porchey"], "Group Captain Peter Townsend (Một phi công đã ly dị vợ)", "Giáo hội Anh và Đạo luật Hôn nhân Hoàng gia 1772 cấm hoàng tộc kết hôn với người từng ly dị."),
  q("cr_6", "Sự kiện thảm họa ô nhiễm không khí lịch sử làm tê liệt London năm 1952 tên là gì?", "Thảm họa sương mù đó là gì?", ["The Great Smog of London (Trận đại sương mù khói than)", "The Great Fire", "The Black Plague", "The Blitz"], "The Great Smog of London (Trận đại sương mù khói than)", "Trận sương mù độc hại cướp đi sinh mạng của hàng ngàn người dân và làm lung lay ghế thủ tướng của Churchill."),
  q("cr_7", "Hoàng thân Philip đã đòi hỏi cải cách hiện đại nào đối với lễ đăng quang năm 1953 của Nữ hoàng?", "Philip đề xuất điều gì?", ["Televising the coronation live (Phát sóng truyền hình trực tiếp cho toàn dân xem)", "Hủy bỏ buổi lễ", "Tổ chức ngoài trời", "Bỏ nghi thức tuyên thệ"], "Televising the coronation live (Phát sóng truyền hình trực tiếp cho toàn dân xem)", "Hơn 20 triệu người dân đã lần đầu tiên được chiêm ngưỡng nghi lễ hoàng gia trên màn ảnh nhỏ."),
  q("cr_8", "Khủng hoảng ngoại giao quân sự chấn động năm 1956 tại Ai Cập làm sụp đổ chính phủ của Thủ tướng Anthony Eden là:", "Cuộc khủng hoảng đó tên là gì?", ["The Suez Crisis (Khủng hoảng kênh đào Suez)", "The Falklands War", "The Cold War", "The Gulf War"], "The Suez Crisis (Khủng hoảng kênh đào Suez)", "Kênh đào Suez đánh dấu sự suy tàn của ảnh hưởng đế quốc Anh tại Trung Đông."),
  q("cr_9", "Vấn đề tế nhị nào về dòng họ khiến Hoàng thân Philip cảm thấy bị tổn thương lòng tự trọng đàn ông?", "Philip phẫn nộ vì điều gì?", ["Các con của ông không được mang họ Mountbatten mà phải giữ họ Windsor", "Không được lái máy bay", "Không được đi du lịch", "Không có lương"], "Các con của ông không được mang họ Mountbatten mà phải giữ họ Windsor", "Philip cay đắng thốt lên: 'Am I an amoeba? The only man in the country not allowed to give his name to his own children?'"),
  q("cr_10", "Bức chân dung mừng sinh nhật 80 tuổi của Churchill do họa sĩ Graham Sutherland vẽ đã bị bà Clementine Churchill làm gì?", "Bức tranh đó đã bị làm sao?", ["Burned and destroyed secretly (Bị đốt cháy tiêu hủy bí mật)", "Treo ở bảo tàng", "Bán đấu giá", "Tặng cho Nữ hoàng"], "Burned and destroyed secretly (Bị đốt cháy tiêu hủy bí mật)", "Churchill ghét cay ghét đắng bức tranh vì nó phơi bày sự già nua tàn tạ của tuổi tác."),
  q("cr_11", "Thảm họa lở đất sập bãi xỉ than chôn vùi trường tiểu học năm 1966 tại xứ Wales diễn ra ở đâu?", "Thảm họa đau thương đó là:", ["The Aberfan disaster", "The Manchester flood", "The Liverpool collapse", "The Belfast blast"], "The Aberfan disaster", "Nữ hoàng Elizabeth sau này hối tiếc vì đã chần chừ tới thăm Aberfan quá muộn sau thảm họa."),
  q("cr_12", "Giám tuyển nghệ thuật hoàng gia Anthony Blunt bị phanh phui là gián điệp của thế lực nào?", "Blunt là gián điệp của ai?", ["A Soviet KGB spy (Gián điệp Liên Xô trong nhóm Cambridge Five)", "Gián điệp Mỹ", "Gián điệp Pháp", "Gián điệp Đức"], "A Soviet KGB spy (Gián điệp Liên Xô trong nhóm Cambridge Five)", "Vụ bê bối tình báo ngay bên trong Cung điện Buckingham thời Chiến tranh Lạnh."),
  q("cr_13", "Cuộc phỏng vấn truyền hình chấn động năm 1995 của Công nương Diana trên chương trình Panorama của BBC có câu nói:", "There were three of us in this marriage, so it was a bit _______.", ["crowded (Có tới ba người trong cuộc hôn nhân này, nên hơi chật chội)", "happy", "empty", "quiet"], "crowded (Có tới ba người trong cuộc hôn nhân này, nên hơi chật chội)", "Công nương Diana ám chỉ mối quan hệ ngoài luồng giữa Thái tử Charles và Camilla Parker Bowles."),
  q("cr_14", "Năm 1992 được Nữ hoàng Elizabeth II gọi trong tiếng Latin bằng cụm từ nổi tiếng nào do có quá nhiều tai ương hoàng gia?", "Năm 1992 được gọi là gì?", ["Annus Horribilis (Năm kinh hoàng khủng khiếp)", "Annus Mirabilis", "Carpe Diem", "Status Quo"], "Annus Horribilis (Năm kinh hoàng khủng khiếp)", "Năm 1992 chứng kiến vụ cháy lâu đài Windsor và sự tan vỡ hôn nhân của ba người con Nữ hoàng."),
  q("cr_15", "Nữ Thủ tướng 'Bà đầm thép' Margaret Thatcher đã có mâu thuẫn sâu sắc với Nữ hoàng về vấn đề gì?", "Hai người bất đồng về điều gì?", ["Trừng phạt kinh tế chế độ phân biệt chủng tộc Apartheid tại Nam Phi", "Chiến tranh Falklands", "Thuế thân", "Giáo dục"], "Trừng phạt kinh tế chế độ phân biệt chủng tộc Apartheid tại Nam Phi", "Nữ hoàng muốn bảo vệ sự đoàn kết của Khối Thịnh Vượng Chung trong khi Thatcher phản đối cấm vận."),
  q("cr_16", "Nguyên tắc chính trị tối cao bất thành văn của Quân vương Anh quốc là gì?", "Nữ hoàng phải luôn giữ lập trường gì?", ["Strict political neutrality (Tính trung lập chính trị tuyệt đối không can thiệp)", "Ủng hộ đảng Bảo thủ", "Ủng hộ đảng Công đoàn", "Tự ra quyết định luật"], "Strict political neutrality (Tính trung lập chính trị tuyệt đối không can thiệp)", "Quân vương trị vì nhưng không cai trị (The Monarch reigns but does not rule)."),
  q("cr_17", "Chuẩn mực phát âm tiếng Anh quý tộc sang trọng được sử dụng bởi các nhân vật trong The Crown gọi là:", "Giọng phát âm chuẩn mực đó là gì?", ["Received Pronunciation (RP / Queen's English)", "Cockney", "Scouse", "Geordie"], "Received Pronunciation (RP / Queen's English)", "Chuẩn mực phát âm danh giá của tầng lớp quý tộc Anh quốc cổ điển."),
  q("cr_18", "Cung điện mùa hè tại Scotland nơi Nữ hoàng Elizabeth II yêu thích nhất và gắn bó cho đến cuối đời là:", "Lâu đài đó tên là gì?", ["Balmoral Castle", "Windsor Castle", "Kensington Palace", "Sandringham House"], "Balmoral Castle", "Lâu đài Balmoral giữa cao nguyên Scotland hùng vĩ."),
  q("cr_19", "Cụm từ tiếng Anh 'constitutional monarchy' có nghĩa là gì?", "What is a 'constitutional monarchy'?", ["Chế độ quân chủ lập hiến", "Chế độ quân chủ chuyên chế", "Chế độ cộng hòa", "Chế độ liên bang"], "Chế độ quân chủ lập hiến", "Mô hình chính trị quyền lực quân vương bị giới hạn bởi hiến pháp và quốc hội."),
  q("cr_20", "Bài học sâu sắc nhất xuyên suốt 6 mùa của The Crown về bổn phận và sự hy sinh là gì?", "Chủ đề cốt lõi của The Crown là:", ["Vương quyền đòi hỏi sự hy sinh liên tục hạnh phúc cá nhân để phục vụ cho bổn phận quốc gia và tính trường tồn của thể chế", "Quyền lực mang lại tự do tuyệt đối", "Hoàng gia không có trách nhiệm gì", "Chỉ cần tiền là đủ"], "Vương quyền đòi hỏi sự hy sinh liên tục hạnh phúc cá nhân để phục vụ cho bổn phận quốc gia và tính trường tồn của thể chế", "Vương miện là gánh nặng khổng lồ của sự quên mình vì đại cuộc.")
]);

// 22. Oppenheimer (C1-C2)
setQ("oppenheimer", [
  q("op_1", "J. Robert Oppenheimer được lịch sử thế giới tôn vinh bằng danh hiệu gì?", "Oppenheimer is known as the:", ["Father of the Atomic Bomb (Cha đẻ của Bom Nguyên tử)", "Father of Modern Physics", "Father of the Internet", "Father of Rockets"], "Father of the Atomic Bomb (Cha đẻ của Bom Nguyên tử)", "Người lãnh đạo khoa học của Dự án Manhattan chế tạo bom nguyên tử."),
  q("op_2", "Địa điểm bí mật được chọn để xây dựng phòng thí nghiệm nghiên cứu hạt nhân ở sa mạc bang New Mexico là:", "Tên địa danh lịch sử đó là gì?", ["Los Alamos", "Area 51", "Cape Canaveral", "Oak Ridge"], "Los Alamos", "Los Alamos - thị trấn bí mật mọc lên giữa hoang mạc để quy tụ hàng ngàn nhà khoa học."),
  q("op_3", "Vị tướng quân đội thực dụng phụ trách chỉ huy hậu cần và an ninh của Dự án Manhattan là ai?", "Tên của vị tướng là gì?", ["General Leslie Groves (do Matt Damon thủ vai)", "General Eisenhower", "General MacArthur", "General Patton"], "General Leslie Groves (do Matt Damon thủ vai)", "Tướng Groves - người đã đặt niềm tin vào Oppenheimer bất chấp nghi vấn chính trị."),
  q("op_4", "Cuộc thử nghiệm vũ khí hạt nhân đầu tiên trong lịch sử nhân loại vào ngày 16/7/1945 có mật danh là gì?", "Mật danh vụ thử nguyên tử là gì?", ["Trinity (Thử nghiệm Trinity)", "Little Boy", "Fat Man", "Manhattan"], "Trinity (Thử nghiệm Trinity)", "Vụ nổ Trinity lóe sáng hơn cả ngàn mặt trời tại sa mạc Jornada del Muerto."),
  q("op_5", "Sau vụ nổ Trinity, Oppenheimer đã nhớ lại câu kinh cổ tiếng Phạn nào trong tác phẩm Bhagavad Gita?", "Now I am become Death, the destroyer of _______.", ["worlds", "stars", "nations", "enemies"], "worlds", "'Giờ đây tôi đã trở thành Thần Chết, kẻ hủy diệt các thế giới.'"),
  q("op_6", "Đối thủ chính trị thâm hiểm, cựu chủ tịch Ủy ban Năng lượng Nguyên tử (AEC) tìm cách hủy hoại Oppenheimer là ai?", "Tên nhân vật do Robert Downey Jr. thủ vai là gì?", ["Lewis Strauss", "Edward Teller", "David Hill", "Boris Pash"], "Lewis Strauss", "Lewis Strauss - vai diễn đem về giải Oscar Nam phụ xuất sắc cho Robert Downey Jr."),
  q("op_7", "Nhà vật lý cha đẻ của Bom Khinh khí (Bom H - nhiệt hạch) đã phản bội và làm chứng chống lại Oppenheimer là ai?", "Tên nhà vật lý đó là gì?", ["Edward Teller", "Enrico Fermi", "Niels Bohr", "Werner Heisenberg"], "Edward Teller", "Edward Teller kiên quyết thúc đẩy chế tạo siêu vũ khí khinh khí cầu và làm chứng chống lại Oppenheimer tại phiên điều trần."),
  q("op_8", "Nhà vật lý thiên tài đã khuyên Oppenheimer đừng quan tâm đến phiên điều trần và nên rời bỏ nước Mỹ là ai?", "Vị bác học già gặp Oppenheimer bên bờ hồ Princeton là ai?", ["Albert Einstein", "Richard Feynman", "Max Born", "Ernest Lawrence"], "Albert Einstein", "Albert Einstein - biểu tượng trí tuệ vĩ đại của thế kỷ 20."),
  q("op_9", "Hai thành phố của Nhật Bản hứng chịu hai quả bom nguyên tử Little Boy và Fat Man vào tháng 8/1945 là:", "Tên hai thành phố đó là gì?", ["Hiroshima and Nagasaki", "Tokyo and Kyoto", "Osaka and Yokohama", "Sapporo and Kobe"], "Hiroshima and Nagasaki", "Hai quả bom nguyên tử kết thúc Thế chiến 2 nhưng cướp đi sinh mạng của hơn 200.000 thường dân."),
  q("op_10", "Trong cuộc gặp gỡ tại Nhà Trắng sau chiến tranh, Oppenheimer đã thốt lên câu nói nào khiến Tổng thống Harry Truman tức giận?", "Oppenheimer nói:", ["Mr. President, I feel I have blood on my hands. (Thưa Tổng thống, tôi cảm thấy hai bàn tay mình nhuốm đầy máu.)", "I want more money.", "We should bomb Russia.", "I quit."], "Mr. President, I feel I have blood on my hands. (Thưa Tổng thống, tôi cảm thấy hai bàn tay mình nhuốm đầy máu.)", "Truman rút chiếc khăn tay mỉa mai và gọi Oppenheimer là 'kẻ khóc nhè' (crybaby)."),
  q("op_11", "Mối tình nồng cháy nhưng bi kịch của Oppenheimer với cô sinh viên đảng viên Đảng Cộng sản tên là gì?", "Tên người tình của Oppenheimer là gì?", ["Jean Tatlock (do Florence Pugh thủ vai)", "Kitty", "Ruth", "Lilli"], "Jean Tatlock (do Florence Pugh thủ vai)", "Jean Tatlock tự sát trong bồn tắm để lại nỗi ám ảnh dằn vặt suốt đời cho Oppenheimer."),
  q("op_12", "Người vợ mạnh mẽ, sắc sảo và nghiện rượu luôn bảo vệ Oppenheimer trước sự công kích là ai?", "Tên người vợ do Emily Blunt thủ vai là gì?", ["Katherine 'Kitty' Oppenheimer", "Jean", "Charlotte", "Mary"], "Katherine 'Kitty' Oppenheimer", "Kitty Oppenheimer với màn đối đáp đanh thép trước hội đồng thẩm vấn."),
  q("op_13", "Mối đe dọa mang tính toán xác suất nào từng khiến các nhà vật lý lo ngại trước vụ thử Trinity?", "Mối lo ngại kinh hoàng nhất là gì?", ["Khả năng vụ nổ hạt nhân kích hoạt phản ứng dây chuyền thiêu rụi toàn bộ bầu khí quyển Trái Đất", "Bom không nổ", "Trời mưa", "Bom phát ra tiếng ồn"], "Khả năng vụ nổ hạt nhân kích hoạt phản ứng dây chuyền thiêu rụi toàn bộ bầu khí quyển Trái Đất", "Xác suất dù gần như bằng không nhưng vẫn tồn tại về mặt lý thuyết."),
  q("op_14", "Phiên điều trần phòng kín thu hồi giấy phép an ninh của Oppenheimer năm 1954 diễn ra dưới thời kỳ bóng ma chính trị nào?", "Thời kỳ thanh trừng chính trị đó là:", ["Chủ nghĩa McCarthy (McCarthyism / Nỗi sợ Đỏ thời Chiến tranh Lạnh)", "Thế chiến 1", "Khủng hoảng 1929", "Nội chiến Mỹ"], "Chủ nghĩa McCarthy (McCarthyism / Nỗi sợ Đỏ thời Chiến tranh Lạnh)", "Nỗi sợ hãi gián điệp cộng sản biến những người hùng thành kẻ bị tình nghi phản quốc."),
  q("op_15", "Ai là nhà khoa học đã bất ngờ đứng lên vạch trần âm mưu trả thù cá nhân của Lewis Strauss trước Thượng viện?", "Tên nhà vật lý dũng cảm đó là gì?", ["Dr. David Hill (do Rami Malek thủ vai)", "Edward Teller", "Isidor Rabi", "Kenneth Nichols"], "Dr. David Hill (do Rami Malek thủ vai)", "Lời khai bất ngờ của David Hill đã đánh gục hoàn toàn cơ hội trở thành Bộ trưởng Thương mại của Strauss."),
  q("op_16", "Nhà vật lý Đan Mạch - người thầy tinh thần vĩ đại của cơ học lượng tử ghé thăm Los Alamos là ai?", "Tên của nhà bác học đó là gì?", ["Niels Bohr (do Kenneth Branagh thủ vai)", "Werner Heisenberg", "Max Planck", "Paul Dirac"], "Niels Bohr (do Kenneth Branagh thủ vai)", "Niels Bohr cảnh báo rằng vũ khí nguyên tử sẽ vĩnh viễn thay đổi tương lai nhân loại."),
  q("op_17", "Thủ pháp điện ảnh phân định màu sắc của đạo diễn Christopher Nolan trong phim mang ý nghĩa gì?", "Các cảnh màu và trắng đen biểu thị điều gì?", ["Màu sắc: Góc nhìn chủ quan của Oppenheimer (Fission) / Trắng đen: Góc nhìn khách quan của Lewis Strauss (Fusion)", "Phim cũ và phim mới", "Quá khứ và tương lai ngẫu nhiên", "Ngày và đêm"], "Màu sắc: Góc nhìn chủ quan của Oppenheimer (Fission) / Trắng đen: Góc nhìn khách quan của Lewis Strauss (Fusion)", "Cấu trúc kể chuyện bậc thầy giữa phân hạch và nhiệt hạch."),
  q("op_18", "Hình ảnh ẩn dụ thần thoại Hy Lạp được dùng làm tựa cuốn tiểu sử đoạt giải Pulitzer của Oppenheimer là ai?", "Vị thần bị trừng phạt đó là ai?", ["Prometheus (Vị thần Prometheus đánh cắp lửa trao cho loài người và chịu hình phạt muôn đời)", "Zeus", "Apollo", "Hercules"], "Prometheus (Vị thần Prometheus đánh cắp lửa trao cho loài người và chịu hình phạt muôn đời)", "'American Prometheus' - kẻ đem sức mạnh thần thánh của ngọn lửa hủy diệt xuống trần gian."),
  q("op_19", "Câu đối thoại kết phim giữa Oppenheimer và Einstein bên bờ hồ tiết lộ sự thật ám ảnh nào?", "Oppenheimer nói với Einstein:", ["Albert, when I came to you with those calculations, we thought we might start a chain reaction that would destroy the entire world... I believe we did.", "We failed.", "The bomb was small.", "War is over."], "Albert, when I came to you with those calculations, we thought we might start a chain reaction that would destroy the entire world... I believe we did.", "Phản ứng dây chuyền chạy đua vũ trang hủy diệt nhân loại thực sự đã bắt đầu."),
  q("op_20", "Bài học đạo đức vĩ đại nhất của kiệt tác điện ảnh Oppenheimer là:", "Thông điệp thời đại của phim là:", ["Khoa học kỹ thuật không thể tách rời trách nhiệm giải trình đạo đức trước sinh mệnh và sự tồn vong của nhân loại", "Chỉ cần thắng trận bằng mọi giá", "Vũ khí càng mạnh càng hòa bình", "Khoa học không cần quan tâm hậu quả"], "Khoa học kỹ thuật không thể tách rời trách nhiệm giải trình đạo đức trước sinh mệnh và sự tồn vong của nhân loại", "Một lời cảnh tỉnh sâu sắc gửi tới thời đại hạt nhân và trí tuệ nhân tạo ngày nay.")
]);

// 23. Inception (C1-C2)
setQ("inception", [
  q("inc_1", "Dom Cobb (Leonardo DiCaprio) là chuyên gia bậc thầy trong lĩnh vực tội phạm công nghệ nào?", "Cobb làm nghề gì?", ["Extraction - Đánh cắp thông tin bí mật từ tiềm thức khi đối tượng đang ngủ mơ", "Hacker máy tính", "Sát thủ", "Trộm ngân hàng"], "Extraction - Đánh cắp thông tin bí mật từ tiềm thức khi đối tượng đang ngủ mơ", "Cobb thâm nhập vào tầng tiềm thức để trích xuất những bí mật sâu kín nhất."),
  q("inc_2", "Nhiệm vụ bất khả thi ngược lại với 'Extraction' được doanh nhân Saito thuê Cobb thực hiện là gì?", "Nhiệm vụ đó gọi là gì?", ["Inception - Cấy ghép một ý niệm vào sâu trong tiềm thức để đối tượng tin là của chính mình", "Xóa trí nhớ", "Đánh thức vĩnh viễn", "Thôi miên bình thường"], "Inception - Cấy ghép một ý niệm vào sâu trong tiềm thức để đối tượng tin là của chính mình", "Cấy ghép một ý niệm tự nhiên nảy nở trong tiềm thức người thừa kế Robert Fischer."),
  q("inc_3", "Vật tổ (Totem) riêng biệt mà Cobb dùng để phân biệt giữa thế giới thực tại và giấc mơ là gì?", "Vật tổ của Cobb là gì?", ["A spinning top (Con quay kim loại)", "A chess piece", "A coin", "A loaded die"], "A spinning top (Con quay kim loại)", "Nếu con quay cứ quay mãi không bao giờ đổ, Cobb biết mình vẫn đang mắc kẹt trong mơ."),
  q("inc_4", "Cô sinh viên kiến trúc tài năng được tuyển mộ để thiết kế mê cung thế giới giấc mơ là ai?", "Tên của nữ kiến trúc sư là gì?", ["Ariadne (do Elliot Page thủ vai)", "Mal", "Phillipa", "Elena"], "Ariadne (do Elliot Page thủ vai)", "Ariadne thiết kế các mê cung kiến trúc đa tầng đánh lừa tiềm thức."),
  q("inc_5", "Kẻ cộng sự đóng vai trò 'giả dạng' (The Forger) có thể bắt chước dung mạo người khác trong mơ là ai?", "Tên nhân vật do Tom Hardy thủ vai là gì?", ["Eames", "Arthur", "Yusuf", "Saito"], "Eames", "Eames - bậc thầy biến hóa ngoại hình và thái độ của mục tiêu."),
  q("inc_6", "Người quản lý điểm tựa hậu cần chu đáo (The Point Man) phụ trách nghiên cứu mục tiêu là ai?", "Tên nhân vật do Joseph Gordon-Levitt thủ vai là gì?", ["Arthur", "Cobb", "Miles", "Browning"], "Arthur", "Arthur luôn tính toán mọi chi tiết logic và an toàn cho phi vụ."),
  q("inc_7", "Dược sĩ tài ba (The Chemist) bào chế loại thuốc an thần cực mạnh cho giấc mơ ba tầng là ai?", "Tên của dược sĩ là gì?", ["Yusuf", "Nash", "Peter", "Tadashi"], "Yusuf", "Yusuf chế tạo loại thuốc an thần giúp giấc mơ tầng sâu ổn định tuyệt đối."),
  q("inc_8", "Hậu quả chết người của việc dùng thuốc an thần liều cao nếu ai đó bị bắn chết trong giấc mơ là gì?", "Điều gì sẽ xảy ra thay vì tỉnh dậy?", ["Rơi vào cõi Limbo (Cõi hư vô vô tận của tiềm thức nguyên sơ)", "Chết thật ngoài đời", "Trở thành người thực vật", "Quên hết ký ức"], "Rơi vào cõi Limbo (Cõi hư vô vô tận của tiềm thức nguyên sơ)", "Trong Limbo, thời gian kéo dài vô tận và tâm trí sẽ quên mất thế giới thực tại."),
  q("inc_9", "Bóng ma tiềm thức đau đớn luôn phá hoại các nhiệm vụ của Cobb là hình chiếu của ai?", "Hình chiếu đó là ai?", ["His deceased wife Mal (Người vợ quá cố Mal)", "His father", "His boss", "His enemy"], "His deceased wife Mal (Người vợ quá cố Mal)", "Nỗi ân hận và cảm giác tội lỗi của Cobb đã nuôi dưỡng bóng ma Mal đầy nguy hiểm."),
  q("inc_10", "Tầng giấc mơ thứ nhất diễn ra trong bối cảnh không gian thời tiết nào?", "Bối cảnh tầng 1 là gì?", ["A rainy city with a speeding van (Thành phố mưa tầm tã với chiếc xe van chạy trốn)", "A luxury hotel", "A snowy mountain fortress", "A beach"], "A rainy city with a speeding van (Thành phố mưa tầm tã với chiếc xe van chạy trốn)", "Yusuf lái chiếc xe van lao đi dưới mưa bão trong khi các đồng đội ngủ say sưa phía sau."),
  q("inc_11", "Tầng giấc mơ thứ hai diễn ra ở đâu với màn chiến đấu không trọng lực kinh điển của Arthur?", "Bối cảnh tầng 2 là:", ["A luxury hotel corridor (Hành lang khách sạn sang trọng không trọng lực)", "A plane", "A castle", "A submarine"], "A luxury hotel corridor (Hành lang khách sạn sang trọng không trọng lực)", "Cảnh Arthur đánh nhau xoay vòng 360 độ trong hành lang không trọng lực thực hiện bằng kỹ xảo thực tế."),
  q("inc_12", "Tầng giấc mơ thứ ba diễn ra ở bối cảnh nào để đột nhập vào pháo đài tiềm thức của Fischer?", "Bối cảnh tầng 3 là:", ["A snowy alpine military fortress (Pháo đài quân sự tuyết trắng trên đỉnh núi)", "Desert", "Forest", "Island"], "A snowy alpine military fortress (Pháo đài quân sự tuyết trắng trên đỉnh núi)", "Eames trượt tuyết bắn súng bảo vệ Cobb và Fischer đột nhập buồng bảo mật."),
  q("inc_13", "Bản nhạc báo hiệu 'Cú hích' (The Kick) để thức tỉnh mọi người đồng loạt trở về là bài hát nào?", "Bài hát đó của nữ danh ca Edith Piaf là gì?", ["Non, je ne regrette rien", "La Vie En Rose", "Autumn Leaves", "My Way"], "Non, je ne regrette rien", "Âm thanh chậm rãi vang rền kéo dài như hồi chuông báo tử thức tỉnh đa tầng."),
  q("inc_14", "Nghịch lý kiến trúc mà Arthur dạy Ariadne xây dựng để đánh lừa bảo vệ tiềm thức là gì?", "Nghịch lý cầu thang vô tận đó tên là:", ["The Penrose stairs (Cầu thang nghịch lý Penrose)", "Escher loop", "Babel tower", "Pyramid"], "The Penrose stairs (Cầu thang nghịch lý Penrose)", "Cầu thang vòng tròn khép kín bước lên mãi mà không bao giờ tới đỉnh."),
  q("inc_15", "Ý niệm ban đầu mà Cobb từng cấy vào đầu Mal khiến cô phát điên và nhảy lầu tự vẫn là gì?", "Ý niệm nguy hiểm đó là:", ["Your world is not real. Death is the only way to wake up. (Thế giới này không có thật. Cái chết là cách duy nhất để tỉnh giấc.)", "You don't love me.", "You are sick.", "Run away."], "Your world is not real. Death is the only way to wake up. (Thế giới này không có thật. Cái chết là cách duy nhất để tỉnh giấc.)", "Ý niệm bén rễ quá sâu khiến Mal tin rằng thế giới thực tại chỉ là mơ và cô phải tự sát để thức tỉnh."),
  q("inc_16", "Câu thoại hóm hỉnh nổi tiếng của Eames khi lôi khẩu súng phóng lựu ra trước mặt Arthur là:", "You mustn't be afraid to dream a little _______, darling.", ["bigger", "smaller", "faster", "longer"], "bigger", "'Em không được sợ hãi mơ lớn hơn một chút đâu, cưng à!'"),
  q("inc_17", "Cobb phải xuống tận cõi Limbo để cứu ai trước khi người này già đi và chết trong quên lãng?", "Cobb xuống cứu ai?", ["Saito (bị thương và mắc kẹt hàng thập kỷ trong hình dạng một ông lão)", "Arthur", "Eames", "Fischer"], "Saito (bị thương và mắc kẹt hàng thập kỷ trong hình dạng một ông lão)", "Saito sống hàng chục năm cô độc trong lâu đài cát bờ biển Limbo trước khi Cobb nhắc lại lời thề."),
  q("inc_18", "Cảnh tượng xoay con quay ở cuối phim khi Cobb ôm hai đứa con có cái kết mở ra sao?", "Cảnh cuối phim diễn ra như thế nào?", ["Con quay xoay tít, bắt đầu hơi chao đảo thì màn hình vụt tắt đen ngòm", "Con quay đổ rạp ngay", "Con quay biến mất", "Con quay phát nổ"], "Con quay xoay tít, bắt đầu hơi chao đảo thì màn hình vụt tắt đen ngòm", "Một trong những cái kết gây tranh cãi và thảo luận sôi nổi nhất lịch sử điện ảnh."),
  q("inc_19", "Cobb so sánh một ý niệm được gieo vào tâm trí giống như loài sinh vật nào?", "An idea is like a _______.", ["virus (Resilient, highly contagious)", "flower", "tree", "bird"], "virus (Resilient, highly contagious)", "'Một ý niệm tựa như loài virus: kiên cường và có sức lây lan mãnh liệt.'"),
  q("inc_20", "Ý nghĩa nhân văn đích thực của Inception không phải là con quay có đổ hay không, mà là:", "Thông điệp cảm xúc cốt lõi là:", ["Cobb đã buông bỏ nỗi ám ảnh quá khứ để chọn quay về với thực tại và tình yêu dành cho hai đứa con", "Giấc mơ luôn tốt hơn thực tại", "Tiền bạc là tất cả", "Không ai có thể tin ai"], "Cobb đã buông bỏ nỗi ám ảnh quá khứ để chọn quay về với thực tại và tình yêu dành cho hai đứa con", "Cobb rời mắt khỏi con quay và chạy tới ôm các con - với anh, thực tại đích thực là nơi có gia đình yêu thương.")
]);

// 24. House of Cards (C1-C2)
setQ("house-of-cards", [
  q("hoc_1", "Nhân vật chính Frank Underwood (Kevin Spacey) đảm nhiệm chức vụ quyền lực nào ở đầu phim?", "Chức vụ của Frank ở đồi Capitol là gì?", ["House Majority Whip (Trưởng ban kỷ luật phe đa số tại Hạ viện Mỹ)", "Speaker of the House", "President", "Senator"], "House Majority Whip (Trưởng ban kỷ luật phe đa số tại Hạ viện Mỹ)", "Người nắm giữ kỷ luật bỏ phiếu và biết tất cả các điểm yếu của từng nghị sĩ."),
  q("hoc_2", "Kỹ thuật điện ảnh đặc trưng của Frank khi quay mặt về phía ống kính nói riêng với khán giả là:", "Thủ pháp nghệ thuật đó tên là gì?", ["Breaking the fourth wall (Phá vỡ bức tường thứ tư)", "Voiceover only", "Flashback", "Montage"], "Breaking the fourth wall (Phá vỡ bức tường thứ tư)", "Frank chia sẻ những mưu đồ trần trụi và triết lý quyền lực cay đắng thẳng thắn với người xem."),
  q("hoc_3", "Người vợ tham vọng, lạnh lùng và là đối tác quyền lực bình đẳng của Frank tên là gì?", "Tên của người vợ do Robin Wright thủ vai là gì?", ["Claire Underwood", "Zoe Barnes", "Rachel Posner", "Linda Vasquez"], "Claire Underwood", "Claire Underwood - người đàn bà sắt đá đồng hành trong mọi ván cờ chính trị."),
  q("hoc_4", "Món ăn dân dã tại quán ăn đêm quen thuộc mà Frank thích nhất ở khu ổ chuột Washington là gì?", "Món ăn khoái khẩu của Frank là:", ["Freddy's BBQ ribs (Món sườn nướng BBQ của Freddy)", "Pizza", "Steak", "Burger"], "Freddy's BBQ ribs (Món sườn nướng BBQ của Freddy)", "Quán sườn nướng của ông già Freddy là chốn bình yên hiếm hoi của Frank."),
  q("hoc_5", "Nữ phóng viên trẻ tham vọng của tờ The Washington Herald mà Frank lợi dụng để rò rỉ tin mật là ai?", "Tên cô phóng viên là gì?", ["Zoe Barnes (do Kate Mara thủ vai)", "Janine Skorsky", "Christina Gallagher", "Ayla Sayyad"], "Zoe Barnes (do Kate Mara thủ vai)", "Zoe đổi tin tức độc quyền lấy thể xác và quyền lực báo chí."),
  q("hoc_6", "Khi Zoe bắt đầu điều tra quá sâu và đe dọa sự nghiệp của Frank, anh đã trừ khử cô thế nào?", "Frank đã làm gì tại ga tàu điện ngầm?", ["Pushed her in front of an oncoming subway train (Đẩy cô vào đầu đoàn tàu điện ngầm đang lao tới)", "Shot her", "Poisoned her drink", "Bribed her"], "Pushed her in front of an oncoming subway train (Đẩy cô vào đầu đoàn tàu điện ngầm đang lao tới)", "Một trong những cảnh giết người chấn động và tàn nhẫn nhất màn ảnh nhỏ."),
  q("hoc_7", "Người trợ lý trung thành tuyệt đối sẵn sàng làm mọi việc bẩn thỉu cho Frank tên là gì?", "Tên người cận vệ tâm phúc là gì?", ["Doug Stamper (do Michael Kelly thủ vai)", "Peter Russo", "Remy Danton", "Seth Grayson"], "Doug Stamper (do Michael Kelly thủ vai)", "Doug Stamper là cánh tay phải mù quáng phụng sự cho tham vọng của Frank."),
  q("hoc_8", "Nghị sĩ bất hạnh Peter Russo mắc chứng nghiện rượu bị Frank thao túng đã kết thúc cuộc đời ra sao?", "Cái chết của Peter Russo diễn ra thế nào?", ["Frank dàn cảnh ông tự tử bằng khí độc carbon monoxide trong xe đóng kín cửa", "Bị bắn chết", "Bị tai nạn máy bay", "Uống thuốc độc"], "Frank dàn cảnh ông tự tử bằng khí độc carbon monoxide trong xe đóng kín cửa", "Frank lạnh lùng hạ sát Peter sau khi đã sử dụng hết giá trị con tốt thí."),
  q("hoc_9", "Chiến lược hai bước mà Frank dùng để leo lên chức Tổng thống Mỹ là gì?", "Hành trình thâu tóm Nhà Trắng của Frank là:", ["Ép Phó Tổng thống từ chức để thế chỗ, sau đó bẫy Tổng thống đương nhiệm Garrett Walker từ chức", "Bầu cử bình thường", "Đảo chính quân sự", "Ám sát Tổng thống"], "Ép Phó Tổng thống từ chức để thế chỗ, sau đó bẫy Tổng thống đương nhiệm Garrett Walker từ chức", "Frank lên làm Tổng thống thứ 46 của Hợp chúng quốc Hoa Kỳ mà không cần nhận một lá phiếu bầu của dân gian."),
  q("hoc_10", "Hành động kết thúc mùa 2 khi Frank bước vào Phòng Bầu dục (Oval Office) là gì?", "Cử chỉ quyền lực của Frank là:", ["Gõ chiếc nhẫn hai lần xuống mặt bàn Tổng thống (Double-tap on the Resolute desk)", "Mỉm cười", "Uống rượu", "Đốt điếu xì gà"], "Gõ chiếc nhẫn hai lần xuống mặt bàn Tổng thống (Double-tap on the Resolute desk)", "Cú gõ bàn đanh thép biểu tượng cho sự khải hoàn của kẻ tiếm quyền."),
  q("hoc_11", "Tổng thống Nga nham hiểm, sắc sảo đối đầu với Frank ở mùa 3 lấy nguyên mẫu từ ai?", "Tên Tổng thống Nga do Lars Mikkelsen thủ vai là gì?", ["Viktor Petrov", "Vladimir Putin", "Gorbachev", "Yeltsin"], "Viktor Petrov", "Viktor Petrov với những màn đấu trí và đấu rượu vodka căng thẳng tại Nhà Trắng."),
  q("hoc_12", "Chương trình việc làm quốc gia đầy tham vọng mà Tổng thống Frank Underwood ban hành tên là gì?", "Chính sách đó tên là gì?", ["America Works (AmWorks)", "New Deal", "Great Society", "Job First"], "America Works (AmWorks)", "Kế hoạch cắt giảm phúc lợi an sinh xã hội để tạo việc làm toàn dân."),
  q("hoc_13", "Vụ ám sát bất thành nhằm vào Frank tại trường đại học khiến Doug Stamper suýt mất mạng do ai thực hiện?", "Kẻ bắn súng là ai?", ["Lucas Goodwin (cựu phóng viên trả thù cho Zoe)", "Remy Danton", "Raymond Tusk", "Tom Hammerschmidt"], "Lucas Goodwin (cựu phóng viên trả thù cho Zoe)", "Vụ nổ súng khiến Frank bị thương nặng phải ghép gan khẩn cấp."),
  q("hoc_14", "Tỷ phú công nghiệp đầy quyền lực đứng sau giật dây Tổng thống Walker là ai?", "Tên nhà tài phiệt năng lượng là gì?", ["Raymond Tusk", "Peter Thiel", "Elon Musk", "Gordon Gekko"], "Raymond Tusk", "Cuộc đối đầu vĩ mô giữa tiền tài tư bản (Tusk) và quyền lực chính trị (Frank)."),
  q("hoc_15", "Câu nói kinh điển của Frank phân biệt giữa Tiền tài (Money) và Quyền lực (Power) là:", "Money is the McMansion in Sarasota... Power is the old stone building that stands for _______.", ["centuries (Hàng thế kỷ)", "years", "months", "days"], "centuries (Hàng thế kỷ)", "'Tiền tài như ngôi biệt thự sụp đổ sau 10 năm. Quyền lực là tòa lâu đài đá sừng sững qua nhiều thế kỷ.'"),
  q("hoc_16", "Câu châm ngôn hành động quyết liệt của Frank khi rơi vào thế cờ bị đối thủ sắp đặt là:", "If you don't like how the table is set, _______ the table.", ["turn over (Hãy lật tung cả cái bàn lên)", "clean", "buy", "leave"], "turn over (Hãy lật tung cả cái bàn lên)", "Luôn chủ động phá vỡ cục diện thay vì ngoan ngoãn chấp nhận thế trận của kẻ khác."),
  q("hoc_17", "Ở mùa cuối cùng, ai đã trở thành nữ Tổng thống đầu tiên của nước Mỹ sau cái chết của Frank?", "Người bước lên ngai vàng là ai?", ["Claire Underwood", "Jackie Sharp", "Cathy Durant", "Jane Davis"], "Claire Underwood", "Claire nhìn thẳng vào ống kính và tuyên bố dứt khoát: 'My turn.'"),
  q("hoc_18", "Từ tiếng Anh 'filibuster' trong nghị trường Mỹ có nghĩa là gì?", "What is a 'filibuster'?", ["Thủ pháp phát biểu kéo dài thời gian nhằm cản trở Thượng viện biểu quyết dự luật", "Lễ tuyên thệ", "Cuộc bầu cử sớm", "Vụ bê bối tài chính"], "Thủ pháp phát biểu kéo dài thời gian nhằm cản trở Thượng viện biểu quyết dự luật", "Một thủ thuật nghị viện kinh điển của chính trường Mỹ."),
  q("hoc_19", "Cụm từ tiếng Anh 'house of cards' mang ý nghĩa ẩn dụ sâu sắc nào?", "Nghĩa bóng của 'House of Cards' là gì?", ["Một cơ cấu quyền lực hào nhoáng nhưng cực kỳ mong manh dễ sụp đổ như lâu đài xếp bằng thẻ bài", "Một trò chơi bài", "Ngôi nhà xây bằng gạch", "Sòng bạc"], "Một cơ cấu quyền lực hào nhoáng nhưng cực kỳ mong manh dễ sụp đổ như lâu đài xếp bằng thẻ bài", "Tựa đề bộ phim lột tả bản chất phù phiếm và dễ tan biến của quyền lực phi nghĩa."),
  q("hoc_20", "Bài học sâu cay nhất mà House of Cards phơi bày về bản chất của tham vọng quyền lực mù quáng là:", "Thông điệp của phim là:", ["Quyền lực đoạt được bằng thủ đoạn tàn độc sẽ tha hóa con người và cuối cùng tự hủy diệt chính kẻ sở hữu nó", "Người tàn nhẫn luôn thắng", "Chính trị không có công lý", "Nên phản bội tất cả mọi người"], "Quyền lực đoạt được bằng thủ đoạn tàn độc sẽ tha hóa con người và cuối cùng tự hủy diệt chính kẻ sở hữu nó", "Lời cảnh tỉnh cay đắng về cái giá của sự tha hóa nhân tâm khi chạy theo ngai vàng quyền lực.")
]);

console.log("Saving full question banks 21-24...");
module.exports = { setQ, q };
