const { setQ, q } = require('./make_quiz_dataset');

// 18. Sherlock (BBC) (C1-C2)
setQ("sherlock", [
  q("sh_1", "Địa chỉ căn hộ huyền thoại tại London nơi Sherlock Holmes và Bác sĩ John Watson cùng thuê trọ là:", "Địa chỉ nổi tiếng là gì?", ["221B Baker Street", "10 Downing Street", "42 Wallaby Way", "4 Privet Drive"], "221B Baker Street", "221B Phố Baker dưới sự quản lý của bà chủ nhà tốt bụng Mrs. Hudson."),
  q("sh_2", "Sherlock Holmes tự định nghĩa về trạng thái tâm lý đặc biệt của bản thân khi bị gọi là kẻ tâm thần:", "I'm not a psychopath, I'm a high-functioning _______.", ["sociopath", "genius", "detective", "soldier"], "sociopath", "'I'm a high-functioning sociopath, do your research!'"),
  q("sh_3", "Kỹ thuật ghi nhớ siêu phàm trong tâm trí mà Sherlock sử dụng để lưu trữ và truy xuất thông tin gọi là:", "Phương pháp ghi nhớ đó tên là gì?", ["Mind palace (Lâu đài ký ức / Phương pháp cung điện La Mã)", "Brain cloud", "Memory box", "Digital bank"], "Mind palace (Lâu đài ký ức / Phương pháp cung điện La Mã)", "Kỹ thuật Memory Palace giúp lưu giữ hàng triệu dữ liệu hình ảnh trong trí não."),
  q("sh_4", "Kẻ thù không đội trời chung thiên tài bệnh hoạn, 'Napoleon của giới tội phạm' là ai?", "Tên của kẻ phản diện là gì?", ["Jim Moriarty", "Mycroft Holmes", "Charles Augustus Magnussen", "Irene Adler"], "Jim Moriarty", "Moriarty - 'tư vấn tội phạm' độc ác đối đầu với Sherlock - 'tư vấn thám tử'."),
  q("sh_5", "Người phụ nữ duy nhất vượt mặt được Sherlock và khiến anh kính nể được gọi là:", "The Woman trong mắt Sherlock là ai?", ["Irene Adler", "Mary Morstan", "Molly Hooper", "Sally Donovan"], "Irene Adler", "Irene Adler - người phụ nữ duy nhất đánh bại trí tuệ của thám tử đại tài."),
  q("sh_6", "Mật mã mở khóa chiếc điện thoại bí mật của Irene Adler mà Sherlock giải được vào phút chót là gì?", "Mật mã 4 chữ cái đó là gì?", ["SHER (I AM SHERLOCKED)", "LOVE", "HELP", "CODE"], "SHER (I AM SHERLOCKED)", "Mật mã tạo thành thông điệp: 'I am Sher-locked' (Tôi đã bị Sherlock chinh phục)."),
  q("sh_7", "Người anh trai quyền lực làm việc trong cơ quan tình báo tối cao của chính phủ Anh là ai?", "Tên người anh trai thông minh hơn cả Sherlock là gì?", ["Mycroft Holmes", "Eurus Holmes", "Sherrinford", "Lestrade"], "Mycroft Holmes", "Mycroft Holmes - người mà theo lời Sherlock: 'He IS the British government.'"),
  q("sh_8", "Người phụ nữ làm nghề bác sĩ pháp y thầm yêu Sherlock và luôn sẵn sàng giúp đỡ anh ở nhà xác là ai?", "Tên cô bác sĩ pháp y là gì?", ["Molly Hooper", "Mrs. Hudson", "Anthea", "Janine"], "Molly Hooper", "Molly Hooper làm việc tại bệnh viện St Bartholomew."),
  q("sh_9", "Viên thanh tra cảnh sát Scotland Yard luôn tin tưởng và cầu cứu Sherlock phá án là ai?", "Tên vị thanh tra là gì?", ["Inspector Greg Lestrade", "Anderson", "Donovan", "Hopkins"], "Inspector Greg Lestrade", "Thanh tra Lestrade luôn coi Sherlock là niềm hy vọng giải mã các kỳ án bế tắc."),
  q("sh_10", "Người vợ tài ba của John Watson có thân phận bí mật trong quá khứ là gì?", "Thân phận thật của Mary Morstan là:", ["An ex-secret agent and assassin (Cựu điệp viên sát thủ đánh thuê tinh nhuệ)", "A normal nurse", "A teacher", "A police officer"], "An ex-secret agent and assassin (Cựu điệp viên sát thủ đánh thuê tinh nhuệ)", "Mary là cựu điệp viên mật của tổ chức A.G.R.A."),
  q("sh_11", "Trò chơi tử thần mà Moriarty sắp đặt buộc Sherlock phải nhảy xuống từ nóc bệnh viện St Bart's là:", "Vụ án đó có tên là gì?", ["The Reichenbach Fall", "A Study in Pink", "The Blind Banker", "The Great Game"], "The Reichenbach Fall", "Sherlock buộc phải nhảy lầu tự vẫn giả để bảo vệ mạng sống của John, Mrs. Hudson và Lestrade."),
  q("sh_12", "Nhạc cụ mà Sherlock thường chơi mỗi khi cần tập trung suy nghĩ phá án là gì?", "Sherlock chơi nhạc cụ nào?", ["Violin (Cây đàn vĩ cầm)", "Piano", "Guitar", "Flute"], "Violin (Cây đàn vĩ cầm)", "Sherlock là một nghệ sĩ violin điêu luyện."),
  q("sh_13", "Vụ tống tiền kinh hoàng của trùm truyền thông Charles Augustus Magnussen được thực hiện bằng:", "Kho tài liệu đen của Magnussen nằm ở đâu?", ["Inside his mind palace (Chỉ tồn tại trong chính lâu đài ký ức của hắn)", "In a secret underground vault", "On hard drives", "In the bank"], "Inside his mind palace (Chỉ tồn tại trong chính lâu đài ký ức của hắn)", "Appledore không hề có kho tài liệu giấy nào; tất cả đều nằm trong đầu Magnussen."),
  q("sh_14", "Để ngăn chặn Magnussen tống tiền nước Anh và hủy hoại cuộc đời John và Mary, Sherlock đã làm gì?", "Hành động quyết liệt của Sherlock là:", ["Shot Magnussen in the head in front of the police", "Paid him money", "Ran away", "Sent him to court"], "Shot Magnussen in the head in front of the police", "Sherlock chấp nhận trở thành sát nhân bị lưu đày để bảo vệ người thân."),
  q("sh_15", "Người em gái thứ ba bí ẩn có trí tuệ siêu việt vượt xa cả Sherlock và Mycroft tên là gì?", "Tên cô em gái là gì?", ["Eurus Holmes", "Violet", "Enola", "Alice"], "Eurus Holmes", "Eurus - ngọn gió đông ('the east wind') hủy diệt bị giam giữ tại nhà tù đảo Sherrinford."),
  q("sh_16", "Trò chơi ghép hình mà Eurus thiết kế thời thơ ấu đã chôn vùi sự thật về người bạn thời thơ ấu nào của Sherlock?", "Bí mật về 'chú chó Victor' thực chất là gì?", ["Sherlock's human childhood best friend Victor Trevor (Người bạn thân thuở nhỏ bị Eurus dìm chết dưới giếng)", "A real dog", "A cat", "A toy"], "Sherlock's human childhood best friend Victor Trevor (Người bạn thân thuở nhỏ bị Eurus dìm chết dưới giếng)", "Sherlock vì quá đau đớn nên não bộ đã biến ký ức về người bạn Victor thành một chú chó mang tên Redbeard."),
  q("sh_17", "Phương pháp suy luận cốt lõi của Sherlock được miêu tả bằng câu danh ngôn nào?", "When you have eliminated the impossible, whatever remains, however improbable, must be the _______.", ["truth", "lie", "future", "past"], "truth", "'Loại bỏ tất cả những điều bất khả, thì điều duy nhất còn lại dù khó tin đến đâu ắt phải là sự thật.'"),
  q("sh_18", "Từ tiếng Anh 'deduction' trong ngữ cảnh điều tra trinh thám có nghĩa là gì?", "What is 'deduction'?", ["Sự suy luận diễn dịch logic từ các chi tiết nhỏ để tìm ra bản chất", "Phép trừ tiền thuế", "Sự đoán mò", "Sự mơ mộng"], "Sự suy luận diễn dịch logic từ các chi tiết nhỏ để tìm ra bản chất", "Kỹ năng quan sát và diễn dịch logic trứ danh của Sherlock Holmes."),
  q("sh_19", "Tiếng súng nổ kết liễu Moriarty trên nóc bệnh viện St Bart's diễn ra như thế nào?", "Moriarty đã chết vì sao?", ["Tự bắn vào miệng mình để buộc Sherlock không còn cách nào khác ngoài cái chết", "Bị Sherlock bắn", "Bị trượt chân ngã", "Bị John Watson bắn"], "Tự bắn vào miệng mình để buộc Sherlock không còn cách nào khác ngoài cái chết", "Moriarty tự sát để khóa chặt thế cờ buộc Sherlock phải nhảy xuống."),
  q("sh_20", "Bài học sâu sắc nhất về tình người mà John Watson đã dạy cho Sherlock Holmes là gì?", "Sự biến chuyển lớn nhất của Sherlock là:", ["Trở thành một con người biết yêu thương, trân trọng tình bạn và có trái tim nhân ái bên cạnh trí tuệ siêu phàm", "Chỉ cần thông minh là đủ", "Không cần bạn bè", "Coi thường tất cả mọi người"], "Trở thành một con người biết yêu thương, trân trọng tình bạn và có trái tim nhân ái bên cạnh trí tuệ siêu phàm", "Từ một cỗ máy suy luận lạnh lùng, Sherlock đã trở thành một con người vĩ đại và nhân hậu nhờ John Watson.")
]);

// 19. The Social Network (C1-C2)
setQ("the-social-network", [
  q("sn_1", "Trang web đầu tiên Mark Zuckerberg viết tại ký túc xá Harvard so sánh nhan sắc nữ sinh tên là:", "Tên trang web gây sập mạng Harvard là gì?", ["Facemash", "TheFacebook", "ConnectU", "Napster"], "Facemash", "Facemash sử dụng thuật toán cờ vua Elo để xếp hạng sắc đẹp nữ sinh."),
  q("sn_2", "Người bạn thân cùng phòng cấp vốn 19.000 USD đầu tiên và là CFO của TheFacebook là ai?", "Tên người bạn đồng sáng lập là gì?", ["Eduardo Saverin", "Sean Parker", "Cameron Winklevoss", "Tyler Winklevoss"], "Eduardo Saverin", "Eduardo Saverin - người bạn thân sau này bị pha loãng cổ phần đau đớn."),
  q("sn_3", "Hai anh em sinh đôi quý tộc Harvard kiện Mark vì tội ăn cắp ý tưởng ConnectU là ai?", "Hai anh em sinh đôi đó tên là gì?", ["The Winklevoss twins (Cameron and Tyler)", "The Wright brothers", "The Warner brothers", "The Koch brothers"], "The Winklevoss twins (Cameron and Tyler)", "Hai anh em nhà Winklevoss cùng Divya Narendra thuê Mark lập trình mạng xã hội HarvardConnection."),
  q("sn_4", "Người sáng lập dịch vụ chia sẻ nhạc Napster đã kết nối Mark với Thung lũng Silicon là ai?", "Tên nhân vật do Justin Timberlake thủ vai là gì?", ["Sean Parker", "Steve Jobs", "Bill Gates", "Elon Musk"], "Sean Parker", "Sean Parker - kẻ nổi loạn mang tầm nhìn định hình đế chế hàng tỷ đô la."),
  q("sn_5", "Lời khuyên đắt giá đầu tiên mà Sean Parker dành cho Mark về việc đặt tên trang web là gì?", "Sean khuyên Mark bỏ từ nào?", ["Drop the 'The'. Just 'Facebook'. It's cleaner.", "Add 'Global'", "Change to 'Chat'", "Make it longer"], "Drop the 'The'. Just 'Facebook'. It's cleaner.", "'Bỏ chữ The đi. Chỉ gọi là Facebook thôi. Ngắn gọn và sắc nét hơn nhiều.'"),
  q("sn_6", "Câu nói kinh điển của Sean Parker tại nhà hàng Manhattan về quy mô tiền bạc là:", "A million dollars isn't cool. You know what's cool? A _______ dollars.", ["billion", "trillion", "thousand", "hundred"], "billion", "'Một triệu đô chẳng có gì ngầu cả. Một tỷ đô mới thực sự ngầu!'"),
  q("sn_7", "Thuật toán xếp hạng người chơi cờ vua mà Mark dùng cho Facemash do ai sáng tạo?", "Tên nhà toán học sáng tạo thuật toán là gì?", ["Arpad Elo", "Alan Turing", "John Nash", "Blaise Pascal"], "Arpad Elo", "Thuật toán hệ số Elo xếp hạng cờ vua được viết vội lên tấm kính cửa sổ."),
  q("sn_8", "Nhà đầu tư mạo hiểm đầu tiên rót 500.000 USD cho Facebook tại Silicon Valley là ai?", "Tên nhà đầu tư thiên thần nổi tiếng là gì?", ["Peter Thiel", "Warren Buffett", "Mark Cuban", "Jeff Bezos"], "Peter Thiel", "Peter Thiel - nhà sáng lập PayPal rót khoản đầu tư bước ngoặt đầu tiên."),
  q("sn_9", "Eduardo Saverin đã trả đũa bằng cách đóng băng tài khoản nào khiến công ty suýt sụp đổ?", "Eduardo đã đóng băng tài khoản nào?", ["The company bank account in Florida", "Mark's personal account", "Harvard account", "Sean's account"], "The company bank account in Florida", "Eduardo đóng băng tài khoản ngân hàng vì bất đồng về việc chèn quảng cáo lên trang web."),
  q("sn_10", "Tỷ lệ cổ phần của Eduardo bị Mark và Sean pha loãng từ hơn 30% xuống còn bao nhiêu?", "Cổ phần của Eduardo bị ép xuống còn:", ["0.03% (Không phẩy không ba phần trăm)", "10%", "5%", "1%"], "0.03% (Không phẩy không ba phần trăm)", "Chiêu trò pháp lý tinh vi phát hành thêm cổ phiếu mới khiến Eduardo gần như mất trắng."),
  q("sn_11", "Phản ứng dữ dội của Eduardo khi phát hiện bị phản bội tại trụ sở Palo Alto là gì?", "Eduardo đã làm hành động gì?", ["Smashed Mark's computer monitor and threatened to sue (Đập nát màn hình máy tính của Mark và tuyên bố khởi kiện)", "Cried and left", "Hugged Mark", "Stayed silent"], "Smashed Mark's computer monitor and threatened to sue (Đập nát màn hình máy tính của Mark và tuyên bố khởi kiện)", "'You better lawyer up, asshole, because I'm not coming back for my 30%, I'm coming back for EVERYTHING!'"),
  q("sn_12", "Hai anh em Winklevoss tham gia môn thể thao Olympic nào tại thế vận hội Bắc Kinh?", "Môn thể thao chèo thuyền Olympic là:", ["Rowing (Môn đua thuyền chèo đôi)", "Sailing", "Swimming", "Polo"], "Rowing (Môn đua thuyền chèo đôi)", "Phân đoạn đua thuyền cúp Henley hoàng gia được đạo diễn David Fincher dàn dựng tuyệt mỹ."),
  q("sn_13", "Mark Zuckerberg từng từ chối bán quảng cáo ở giai đoạn đầu vì lý do gì?", "Mark muốn bảo vệ điều gì ở Facebook?", ["Facebook is cool. Advertising ruins the cool factor. (Quảng cáo sẽ làm hỏng sự sành điệu của trang web)", "Không cần tiền", "Ghét tiền", "Không biết bán quảng cáo"], "Facebook is cool. Advertising ruins the cool factor. (Quảng cáo sẽ làm hỏng sự sành điệu của trang web)", "Mark ví Facebook như một bữa tiệc độc quyền chưa bao giờ tàn."),
  q("sn_14", "Câu phản pháo đanh thép của Mark trước các luật sư của anh em Winklevoss là:", "If you guys were the inventors of Facebook, you'd have _______ Facebook.", ["invented", "bought", "deleted", "liked"], "invented", "'Nếu các anh thực sự là những người phát minh ra Facebook, thì các anh đã tự phát minh ra nó rồi.'"),
  q("sn_15", "Bi kịch dẫn đến việc Sean Parker bị loại khỏi hội đồng quản trị Facebook là gì?", "Sean vướng vào bê bối gì?", ["Bị cảnh sát bắt tại bữa tiệc vì tàng trữ ma túy cocaine", "Đánh nhau", "Ăn cắp tiền", "Bỏ trốn"], "Bị cảnh sát bắt tại bữa tiệc vì tàng trữ ma túy cocaine", "Vụ bắt giữ bê bối khiến Peter Thiel và ban điều hành yêu cầu Sean phải rút lui."),
  q("sn_16", "Nữ luật sư trẻ Marylin Delpy khuyên Mark chấp nhận dàn xếp bồi thường bằng câu nói:", "You're not an asshole, Mark. You're just trying so hard to be _______.", ["one", "rich", "famous", "cool"], "one", "'Cậu không phải một gã tồi tệ đâu, Mark. Chỉ là cậu đang cố gắng gồng mình để trở thành một kẻ tồi mà thôi.'"),
  q("sn_17", "Cảnh cuối phim, Mark Zuckerberg ngồi cô độc một mình trước màn hình laptop làm hành động gì?", "Mark liên tục nhấn F5 để làm gì?", ["F5 refreshing the friend request sent to his ex-girlfriend Erica Albright (Nhấn F5 làm mới trang chờ người yêu cũ chấp nhận kết bạn)", "Chơi game", "Viết code mới", "Đếm tiền"], "F5 refreshing the friend request sent to his ex-girlfriend Erica Albright (Nhấn F5 làm mới trang chờ người yêu cũ chấp nhận kết bạn)", "Bi kịch của kẻ kết nối 500 triệu người trên Trái Đất nhưng lại hoàn toàn cô độc và không thể kết nối lại với người con gái mình từng yêu."),
  q("sn_18", "Nhạc phim (Original Score) đỉnh cao của The Social Network do nhạc sĩ thiên tài nào sáng tác?", "Nhạc phim đoạt giải Oscar do ai sáng tác?", ["Trent Reznor and Atticus Ross", "Hans Zimmer", "John Williams", "Ennio Morricone"], "Trent Reznor and Atticus Ross", "Bản phối âm thanh điện tử ám ảnh mang về tượng vàng Oscar danh giá."),
  q("sn_19", "Từ tiếng Anh 'dilution' trong tài chính doanh nghiệp có nghĩa là gì?", "What does 'dilution' mean?", ["Sự pha loãng tỷ lệ sở hữu cổ phần khi công ty phát hành thêm cổ phiếu mới", "Sự tăng giá cổ phiếu", "Sự phá sản", "Sự giải thể"], "Sự pha loãng tỷ lệ sở hữu cổ phần khi công ty phát hành thêm cổ phiếu mới", "Chiêu bài tài chính then chốt trong vụ kiện giữa Eduardo và Mark."),
  q("sn_20", "Bài học sâu cay nhất mà bộ phim The Social Network phản ánh về thế giới công nghệ là:", "Thông điệp của phim là:", ["Bạn không thể tạo ra 500 triệu người bạn mà không vô tình tạo ra vài kẻ thù dọc đường", "Thành công dễ dàng không mất mát gì", "Tình bạn quan trọng hơn tiền bạc trong kinh doanh", "Ai cũng là người tốt"], "Bạn không thể tạo ra 500 triệu người bạn mà không vô tình tạo ra vài kẻ thù dọc đường", "'You don't get to 500 million friends without making a few enemies.'")
]);

// 20. The King's Speech (C1-C2)
setQ("the-kings-speech", [
  q("ks_1", "Hoàng tử Albert (sau này là Vua George VI) mắc chứng tật ngôn ngữ bẩm sinh nào?", "Hoàng tử mắc chứng tật gì?", ["A severe stammer / stutter (Tật nói lắp bắp nghiêm trọng)", "Deafness", "Blindness", "Aphasia"], "A severe stammer / stutter (Tật nói lắp bắp nghiêm trọng)", "Tật nói lắp khiến ông vô cùng sợ hãi và tự ti mỗi khi phải đứng trước đám đông."),
  q("ks_2", "Người vợ tận tụy Elizabeth (Hoàng mẫu hậu sau này) đã tìm đến ai để điều trị cho chồng?", "Tên của người thầy phát âm lập dị là gì?", ["Lionel Logue", "Sigmund Freud", "Alexander Bell", "Winston Churchill"], "Lionel Logue", "Lionel Logue là một chuyên gia trị liệu giọng nói người Úc sống tại London."),
  q("ks_3", "Quy tắc bắt buộc đầu tiên mà Lionel Logue yêu cầu Hoàng tử Albert khi bước vào phòng khám là:", "Nguyên tắc của Lionel là:", ["In here, it's better if we're equals (Ở trong phòng này, chúng ta hoàn toàn bình đẳng như nhau)", "Phải quỳ lạy", "Phải gọi hoàng tử là bệ hạ", "Không được nói chuyện"], "In here, it's better if we're equals (Ở trong phòng này, chúng ta hoàn toàn bình đẳng như nhau)", "Lionel từ chối nghi thức cung đình và gọi hoàng tử bằng tên thân mật 'Bertie'."),
  q("ks_4", "Kỹ thuật đầu tiên Lionel áp dụng cho Bertie đọc văn bản trôi chảy mà không bị lắp là gì?", "Lionel đã cho Bertie làm gì?", ["Đeo tai nghe phát nhạc lớn và đọc văn bản ghi âm trên đĩa hát", "Uống thuốc ngủ", "Ngậm đá cuội", "Chạy bộ"], "Đeo tai nghe phát nhạc lớn và đọc văn bản ghi âm trên đĩa hát", "Khi tai không nghe thấy giọng nói của chính mình, Bertie đọc trôi chảy từng chữ."),
  q("ks_5", "Vua George V thúc ép con trai phải tập phát thanh vì sự xuất hiện của công nghệ mới nào?", "Phương tiện truyền thông thời đó là gì?", ["The wireless radio (Đài phát thanh vô tuyến)", "Television", "Internet", "Cinema"], "The wireless radio (Đài phát thanh vô tuyến)", "Đài phát thanh đưa giọng nói của nguyên thủ đến hàng triệu gia đình cùng lúc."),
  q("ks_6", "Người anh trai ăn chơi của Bertie là Vua Edward VIII đã thoái vị vì lý do gì?", "Edward VIII thoái vị để làm gì?", ["To marry Wallis Simpson - a divorced American woman (Cưới một phụ nữ Mỹ từng hai đời chồng)", "Bị đảo chính", "Vì bị bệnh nặng", "Đi tu"], "To marry Wallis Simpson - a divorced American woman (Cưới một phụ nữ Mỹ từng hai đời chồng)", "Cuộc khủng hoảng thoái vị chấn động năm 1936 đưa Bertie bất đắc dĩ lên ngôi hoàng đế."),
  q("ks_7", "Cơ quan cơ thể quan trọng nhất mà Lionel huấn luyện Bertie dùng để lấy hơi sâu là gì?", "Cơ quan đó là gì?", ["Diaphragm (Cơ hoành bụng)", "Chest", "Throat", "Mouth"], "Diaphragm (Cơ hoành bụng)", "'Breathe from your diaphragm, not your chest.'"),
  q("ks_8", "Trong cơn bộc phát cảm xúc mạnh mẽ tại phòng khám, Bertie đã gào lên câu danh ngôn nào?", "Bertie hét lên:", ["Because I have a voice! (Bởi vì tôi có tiếng nói của riêng mình!)", "I am the King!", "Leave me alone!", "I hate you!"], "Because I have a voice! (Bởi vì tôi có tiếng nói của riêng mình!)", "Khoảnh khắc phá vỡ rào cản tự ti để khẳng định quyền được lắng nghe."),
  q("ks_9", "Bằng cấp y khoa thực sự của Lionel Logue bị Tổng Giám mục Canterbury hoài nghi là gì?", "Thực tế về bằng cấp của Lionel là:", ["Ông không có bằng bác sĩ chính quy mà chỉ có kinh nghiệm thực chiến trị liệu cho lính thương binh sau Thế chiến 1", "Bằng giả", "Bằng tiến sĩ Oxford", "Là giáo sư đại học"], "Ông không có bằng bác sĩ chính quy mà chỉ có kinh nghiệm thực chiến trị liệu cho lính thương binh sau Thế chiến 1", "Lionel cứu chữa hàng ngàn cựu binh bị sang chấn tâm lý mất giọng sau chiến hào."),
  q("ks_10", "Hành động ngồi chễm chệ lên ngai vàng St. Edward's Chair của Lionel trước lễ đăng quang nhằm mục đích gì?", "Mục đích của Lionel là:", ["Kích thích lòng tự tôn và sự phẫn nộ của Bertie để ông cất tiếng nói phản kháng dõng dạc", "Muốn cướp ngôi", "Muốn chụp ảnh", "Vì mỏi chân"], "Kích thích lòng tự tôn và sự phẫn nộ của Bertie để ông cất tiếng nói phản kháng dõng dạc", "Liệu pháp tâm lý đảo ngược giúp Bertie quên đi nỗi sợ hãi cung đình."),
  q("ks_11", "Bài phát biểu lịch sử quan trọng nhất trong đời Vua George VI diễn ra vào thời điểm nào?", "Bối cảnh bài phát biểu là gì?", ["Ngày 3 tháng 9 năm 1939 - Nước Anh tuyên chiến với Đức Quốc Xã mở đầu Thế chiến 2", "Ngày đăng quang", "Lễ giáng sinh", "Ngày sinh nhật"], "Ngày 3 tháng 9 năm 1939 - Nước Anh tuyên chiến với Đức Quốc Xã mở đầu Thế chiến 2", "Bài phát biểu radio định mệnh tiếp thêm dũng khí cho toàn thể nhân dân Đế chế Anh."),
  q("ks_12", "Trong phòng phát thanh bí mật tại Cung điện Buckingham, Lionel đã đứng ở đâu?", "Lionel đứng ở vị trí nào?", ["Đứng ngay đối diện chiếc micro, chỉ huy nhịp điệu bằng tay như một nhạc trưởng giao hưởng", "Ngồi ngoài phòng", "Ở nhà", "Đứng sau rèm"], "Đứng ngay đối diện chiếc micro, chỉ huy nhịp điệu bằng tay như một nhạc trưởng giao hưởng", "Lionel nhắc Bertie: 'Forget the millions. Just say it to me as a friend.'"),
  q("ks_13", "Bản giao hưởng bất hủ nào của Beethoven được lồng vào phân đoạn phát biểu tuyên chiến?", "Bản giao hưởng đó là:", ["Symphony No. 7 in A major, Op. 92 - II. Allegretto", "Symphony No. 5", "Symphony No. 9", "Moonlight Sonata"], "Symphony No. 7 in A major, Op. 92 - II. Allegretto", "Âm nhạc bi tráng nâng tầm cảm xúc của một trong những cảnh phim vĩ đại nhất lịch sử."),
  q("ks_14", "Khi kết thúc bài diễn văn hoàn hảo, Lionel đùa về lỗi vấp nhỏ ở chữ đầu tiên, nhà vua đáp:", "I had to throw in a few so they'd know it was _______.", ["me (Tôi phải nói vấp vài từ để dân chúng nhận ra đúng là tôi chứ)", "good", "the King", "radio"], "me (Tôi phải nói vấp vài từ để dân chúng nhận ra đúng là tôi chứ)", "Lối đối đáp hóm hỉnh nhẹ nhõm sau áp lực nghẹt thở."),
  q("ks_15", "Tước hiệu cao quý mà Vua George VI ban tặng cho Lionel Logue sau đó là gì?", "Tước hiệu hoàng gia là gì?", ["Commander of the Royal Victorian Order (CVO)", "Knight", "Duke", "Lord"], "Commander of the Royal Victorian Order (CVO)", "Sự công nhận và tri ân trọn đời của nhà vua dành cho người thầy tri kỷ."),
  q("ks_16", "Nguyên nhân tâm lý sâu xa của tật nói lắp thời thơ ấu của Bertie bắt nguồn từ đâu?", "Nguyên nhân là do:", ["Sự hà khắc bạo lực tinh thần của cha, sự ngược đãi của vú em và việc bị ép dùng tay phải", "Bị ngã từ trên cao", "Bị sốt xuất huyết", "Ăn phải chất độc"], "Sự hà khắc bạo lực tinh thần của cha, sự ngược đãi của vú em và việc bị ép dùng tay phải", "Bertie vốn thuận tay trái nhưng bị phạt đánh đập ép đổi tay, cộng thêm tật chân vòng kiềng đau đớn."),
  q("ks_17", "Phương pháp chữa trị kỳ quặc mà các bác sĩ quý tộc trước đó bắt Bertie làm là gì?", "Phương pháp phản khoa học đó là:", ["Ngậm 7 viên đá cuội vô trùng trong miệng và vừa hút thuốc lá để thả lỏng họng", "Cắt lưỡi", "Uống rượu mạnh", "Nhịn ăn"], "Ngậm 7 viên đá cuội vô trùng trong miệng và vừa hút thuốc lá để thả lỏng họng", "Bertie suýt nuốt phải những viên đá cuội khiến ông mất niềm tin vào y học hoàng gia."),
  q("ks_18", "Hai cô công chúa nhỏ đáng yêu của Vua George VI trong phim sau này là ai?", "Người con gái lớn sau này là:", ["Princess Elizabeth (Nữ hoàng Elizabeth II sau này) và Princess Margaret", "Diana", "Victoria", "Mary"], "Princess Elizabeth (Nữ hoàng Elizabeth II sau này) và Princess Margaret", "Chính là Nữ hoàng Elizabeth II trị vì suốt 70 năm lịch sử."),
  q("ks_19", "Từ tiếng Anh 'elocution' có nghĩa là gì?", "What is 'elocution'?", ["Nghệ thuật phát âm chuẩn xác, rõ ràng và truyền cảm trước công chúng", "Kỹ thuật viết lách", "Sự im lặng", "Tiếng cười đùa"], "Nghệ thuật phát âm chuẩn xác, rõ ràng và truyền cảm trước công chúng", "'Elocution' là nghệ thuật luyện âm hùng biện."),
  q("ks_20", "Bài học sâu sắc nhất mà The King's Speech mang lại cho người học tiếng Anh và giao tiếp là:", "Bài học lớn nhất là gì?", ["Sự tự tin cất lên tiếng nói của chính mình và dũng cảm đối diện với khiếm khuyết quan trọng hơn sự hoàn hảo sáo rỗng", "Chỉ cần nói to là được", "Không bao giờ được mắc lỗi", "Tránh né đám đông"], "Sự tự tin cất lên tiếng nói của chính mình và dũng cảm đối diện với khiếm khuyết quan trọng hơn sự hoàn hảo sáo rỗng", "Vượt qua nỗi sợ hãi tâm lý để tìm thấy tiếng nói đích thực của bản thân là chiến thắng vĩ đại nhất.")
]);

console.log("Saving full question banks 18-20...");
module.exports = { setQ, q };
