const { setQ, q } = require('./make_quiz_dataset.cjs');

// 7. Toy Story (A1-A2)
setQ("toy-story", [
  q("ts_1", "Khẩu hiệu bay vào vũ trụ bất hủ của Buzz Lightyear là gì?", "To infinity and _______!", ["beyond", "behind", "below", "between"], "beyond", "'To infinity and beyond!' (Vươn tới vô cực và xa hơn nữa!)."),
  q("ts_2", "Woody là món đồ chơi thuộc thể loại nhân vật nào?", "Woody is a vintage _______ doll.", ["cowboy", "astronaut", "pirate", "ninja"], "cowboy", "Woody là búp bê cao bồi kéo dây cổ điển."),
  q("ts_3", "Tên cậu bé chủ nhân yêu quý của các món đồ chơi là gì?", "Tên của cậu bé là gì?", ["Andy", "Sid", "Billy", "Tommy"], "Andy", "Andy là cậu bé chủ nhân tốt bụng viết tên mình dưới đế giày đồ chơi."),
  q("ts_4", "Cậu bé hàng xóm độc ác thích tháo rời và phá hoại đồ chơi tên là gì?", "Tên của cậu bé hung dữ là gì?", ["Sid Phillips", "Buster", "Rex", "Slinky"], "Sid Phillips", "Sid là cậu bé chuyên dùng pháo hoa và kìm để tra tấn đồ chơi."),
  q("ts_5", "Chú khủng long bạo chúa nhút nhát và luôn lo lắng tên là gì?", "Tên chú khủng long xanh là gì?", ["Rex", "Hamm", "Slinky", "Bullseye"], "Rex", "Rex là chú khủng long bạo chúa nhưng tính tình lại siêu nhút nhát."),
  q("ts_6", "Chú heo đất tiết kiệm thích pha trò châm biếm tên là gì?", "Tên chú heo đất là gì?", ["Hamm", "Porky", "Babe", "Wilbur"], "Hamm", "Hamm là chú heo đất thông thái hay nói lời mỉa mai."),
  q("ts_7", "Chú chó lò xo trung thành luôn đứng về phía Woody tên là gì?", "Tên chú chó lò xo là gì?", ["Slinky Dog", "Buster", "Scud", "Pluto"], "Slinky Dog", "Slinky Dog là chú chó có thân lò xo co giãn."),
  q("ts_8", "Buzz Lightyear ban đầu luôn lầm tưởng bản thân là ai?", "Buzz nghĩ mình là gì?", ["A real Space Ranger (Cảnh sát vũ trụ thật)", "A wooden toy", "A normal human", "A movie star"], "A real Space Ranger (Cảnh sát vũ trụ thật)", "Buzz từng ngây thơ tin rằng mình là chiến binh không gian thật có phi thuyền."),
  q("ts_9", "Woody hét lên với Buzz để đánh thức cậu về thực tế:", "You are a _______!", ["toy", "monster", "hero", "pilot"], "toy", "'You are a toy! You aren't the real Buzz Lightyear!'"),
  q("ts_10", "Nhà hàng pizza mang phong cách không gian nơi Andy đến ăn tối tên là gì?", "Tên nhà hàng pizza là gì?", ["Pizza Planet", "Pizza Hut", "Domino's", "Galaxy Food"], "Pizza Planet", "Pizza Planet là nhà hàng trò chơi không gian nổi tiếng."),
  q("ts_11", "Những chú người ngoài hành tinh ba mắt màu xanh lá cây tôn thờ cỗ máy nào?", "Họ tôn thờ vật gì?", ["The Claw (Cần gắp thú bông)", "The Rocket", "The Sun", "The Laser"], "The Claw (Cần gắp thú bông)", "Lũ người ngoài hành tinh tí hon tôn sùng chiếc Cần Gắp Thú ('The Claw is our master!')."),
  q("ts_12", "Buzz phát hiện ra sự thật mình chỉ là đồ chơi khi nhìn thấy điều gì trên TV?", "Buzz thấy gì trên TV?", ["A commercial showing Buzz Lightyear toys for sale", "A real spaceship", "Andy crying", "A cartoon"], "A commercial showing Buzz Lightyear toys for sale", "Buzz nhìn thấy mẩu quảng cáo bán đồ chơi Buzz với giá 19.99 đô la tại Al's Toy Barn."),
  q("ts_13", "Khi Buzz nhảy từ lan can xuống để cố bay, cậu đã:", "Buzz đã bị làm sao khi rơi xuống?", ["Fell and broke his left arm", "Flew out the window", "Disappeared", "Landed safely"], "Fell and broke his left arm", "Buzz rơi xuống sàn nhà và gãy lìa cánh tay trái."),
  q("ts_14", "Khi Woody và Buzz lướt gió bay theo chiếc xe tải của Andy, Buzz nói:", "This isn't flying, this is falling with _______!", ["style", "speed", "fear", "magic"], "style", "'Falling with style' (Rơi xuống một cách đầy phong cách!)."),
  q("ts_15", "Tên bài hát mở đầu và chủ đề tình bạn của Toy Story là gì?", "Tên bài hát là gì?", ["You've Got a Friend in Me", "A Whole New World", "Can You Feel the Love Tonight", "Beauty and the Beast"], "You've Got a Friend in Me", "Ca khúc bất hủ do Randy Newman sáng tác."),
  q("ts_16", "Luật bất thành văn quan trọng nhất của thế giới đồ chơi là gì?", "Đồ chơi không được làm gì trước mặt con người?", ["Không được cử động hay nói chuyện khi có người nhìn thấy", "Không được chơi với nhau", "Không được ăn uống", "Không được thay quần áo"], "Không được cử động hay nói chuyện khi có người nhìn thấy", "Đồ chơi phải 'đóng băng' bất động khi con người xuất hiện."),
  q("ts_17", "Để dọa Sid và dạy cho cậu bài học nhớ đời, Woody đã làm gì?", "Woody đã làm gì trong sân nhà Sid?", ["Broke the rule and talked directly to Sid", "Threw a rock at Sid", "Called the police", "Bit Sid's leg"], "Broke the rule and talked directly to Sid", "Lũ đồ chơi sống dậy bao vây Sid và Woody cảnh cáo: 'Play nice!'"),
  q("ts_18", "Món quà sinh nhật mới toanh mà Andy nhận được ở cuối phim làm Woody và Buzz lo lắng là gì?", "Món quà đó là gì?", ["A puppy (Một chú cún con thật)", "A new bike", "A computer", "A cat"], "A puppy (Một chú cún con thật)", "Andy được tặng một chú chó con thật tên là Buster."),
  q("ts_19", "Cụm từ tiếng Anh 'stick together' có nghĩa là gì?", "What does 'stick together' mean?", ["Gắn bó, đoàn kết bên nhau", "Dán keo vào nhau", "Chia rẽ nhau", "Bỏ rơi nhau"], "Gắn bó, đoàn kết bên nhau", "'Stick together' là thành ngữ nghĩa là luôn sát cánh, đoàn kết ủng hộ nhau."),
  q("ts_20", "Bài học ý nghĩa nhất về giá trị của một món đồ chơi trong Toy Story là gì?", "Giá trị lớn nhất của đồ chơi là gì?", ["Đem lại niềm vui và đồng hành cùng tuổi thơ của đứa trẻ", "Trưng bày trong tủ kính kiếm tiền", "Luôn mới tinh không vết xước", "Có cánh bay thật"], "Đem lại niềm vui và đồng hành cùng tuổi thơ của đứa trẻ", "Sứ mệnh đẹp nhất của đồ chơi là tình yêu thương vô điều kiện dành cho đứa trẻ.")
]);

// 8. Modern Family (A1-A2)
setQ("modern-family", [
  q("mf_1", "Phil Dunphy luôn tự phong cho mình danh hiệu gì trước mặt các con?", "Phil calls himself a _______ dad.", ["cool", "strict", "boring", "rich"], "cool", "Phil luôn tự hào mình là một 'cool dad' bắt kịp giới trẻ."),
  q("mf_2", "Công việc chính mà Phil Dunphy làm để kiếm sống là gì?", "What is Phil's profession?", ["Real estate agent (Realtor)", "Lawyer", "Doctor", "Teacher"], "Real estate agent (Realtor)", "Phil là nhân viên môi giới nhà đất California."),
  q("mf_3", "Người vợ đảm đang, tháo vát và thích kiểm soát của Phil tên là gì?", "Tên người vợ là gì?", ["Claire", "Gloria", "Cameron", "Haley"], "Claire", "Claire Pritchett-Dunphy là mẹ của Haley, Alex và Luke."),
  q("mf_4", "Con gái thứ hai Alex Dunphy nổi bật với đặc điểm tính cách nào?", "Alex Dunphy nổi tiếng về điều gì?", ["Extremely smart and competitive (Mọt sách thiên tài)", "Lazy", "Bad at math", "Only cares about fashion"], "Extremely smart and competitive (Mọt sách thiên tài)", "Alex là cô bé thần đồng đạt điểm số học tập xuất sắc."),
  q("mf_5", "Con gái đầu Haley Dunphy thường có mối quan tâm lớn nhất về điều gì?", "Haley quan tâm nhất đến:", ["Fashion, boys, and social life", "Chemistry", "Rocket science", "Politics"], "Fashion, boys, and social life", "Haley là cô chị cả sành điệu thích tiệc tùng và thời trang."),
  q("mf_6", "Cậu con trai út ngây thơ và tinh nghịch của nhà Phil tên là gì?", "Tên cậu con út là gì?", ["Luke", "Manny", "Joe", "Dylan"], "Luke", "Luke Dunphy ngây ngô hay làm trò nghịch dại cùng bố Phil."),
  q("mf_7", "Jay Pritchett kết hôn với người vợ thứ hai xinh đẹp người Colombia tên là gì?", "Tên người vợ Colombia là gì?", ["Gloria", "Maria", "Elena", "Sofia"], "Gloria", "Gloria Delgado-Pritchett với chất giọng Latin đầy cuốn hút."),
  q("mf_8", "Cậu con trai riêng sâu sắc, thích làm thơ và uống cà phê của Gloria tên là gì?", "Tên cậu bé là gì?", ["Manny", "Luke", "Alex", "Joe"], "Manny", "Manny Delgado là cậu bé có tâm hồn như ông cụ non lãng mạn."),
  q("mf_9", "Cặp đôi đồng tính đáng yêu nhận nuôi bé gái Lily từ Việt Nam là ai?", "Cặp đôi đó là ai?", ["Mitchell and Cameron", "Phil and Jay", "Luke and Manny", "Dylan and Andy"], "Mitchell and Cameron", "Mitch (luật sư) và Cam (giáo viên âm nhạc) là cặp đôi đồng tính đáng yêu."),
  q("mf_10", "Cameron Tucker có niềm đam mê đặc biệt với nhân vật chú hề biểu diễn tên là gì?", "Nhân vật chú hề của Cam tên là gì?", ["Fizbo the Clown", "Bozo", "Pennywise", "Joker"], "Fizbo the Clown", "Cam rất tự hào mỗi khi hóa trang thành chú hề Fizbo."),
  q("mf_11", "Jay Pritchett làm giàu và sở hữu công ty chuyên sản xuất kinh doanh sản phẩm gì?", "Công ty của Jay bán gì?", ["Closets and blinds (Tủ quần áo)", "Cars", "Computers", "Shoes"], "Closets and blinds (Tủ quần áo)", "Jay sở hữu công ty tủ đồ 'Pritchett's Closets & Blinds'."),
  q("mf_12", "Cún cưng giống bò sữa Pháp mà Jay cưng chiều hơn cả con cái tên là gì?", "Tên chú chó cưng là gì?", ["Stella", "Daisy", "Bella", "Luna"], "Stella", "Stella là cô chó giống French Bulldog được Jay vô cùng cưng chiều."),
  q("mf_13", "Khi Phil phát minh ra triết lý sống kết hợp giữa Phil và Philosophy, ông gọi nó là gì?", "Triết lý của Phil tên là gì?", ["Phil's-osophy", "Phil-ology", "Phil-wisdom", "Dunphy-code"], "Phil's-osophy", "'Phil's-osophy' là cuốn cẩm nang lời khuyên cuộc đời hài hước của Phil."),
  q("mf_14", "Khi Gloria nói tiếng Anh bị nhầm lẫn giữa 'helicopter' và 'gyrocopter', nguyên nhân là do:", "Gloria gặp khó khăn vì:", ["Tiếng Anh là ngôn ngữ thứ hai của cô (native Spanish)", "Cô không biết nói", "Cô bị điếc", "Cô nói tiếng Pháp"], "Tiếng Anh là ngôn ngữ thứ hai của cô (native Spanish)", "Gloria tự hào: 'Do you know how smart I am in Spanish?!'"),
  q("mf_15", "Anh chàng bạn trai ngốc nghếch chơi guitar của Haley tên là gì?", "Tên bạn trai lâu năm của Haley là gì?", ["Dylan", "Andy", "Rainer", "Arvin"], "Dylan", "Dylan Marshall hát những bản nhạc chế ngộ nghĩnh tặng gia đình."),
  q("mf_16", "Môn thể thao bóng bầu dục mà Cameron từng huấn luyện tại trường trung học là gì?", "Cam huấn luyện môn gì?", ["Football", "Soccer", "Baseball", "Basketball"], "Football", "Cam là huấn luyện viên bóng bầu dục trường cấp ba rất mát tay."),
  q("mf_17", "Từ tiếng Anh nào chỉ 'sự kỳ quặc, lập dị nhưng đáng yêu' của các thành viên?", "Từ vựng tiếng Anh là:", ["Eccentric", "Boring", "Ordinary", "Cruel"], "Eccentric", "'Eccentric' là tính cách lập dị, khác người nhưng thú vị."),
  q("mf_18", "Hình thức quay phim độc đáo của Modern Family mô phỏng phim tài liệu được gọi là gì?", "Thể loại hài kịch này là gì?", ["Mockumentary", "Horror", "Musical", "Thriller"], "Mockumentary", "'Mockumentary' là thể loại giả tài liệu với các đoạn phỏng vấn nhìn thẳng ống kính."),
  q("mf_19", "Cụm từ tiếng Anh 'Family first' có ý nghĩa là gì?", "What does 'Family first' mean?", ["Gia đình luôn là ưu tiên số một trên hết", "Gia đình đứng thứ hai", "Không quan tâm gia đình", "Đi làm trước về nhà sau"], "Gia đình luôn là ưu tiên số một trên hết", "'Family first' là nguyên tắc đặt gia đình lên hàng đầu."),
  q("mf_20", "Bài học tình cảm lớn nhất xuyên suốt 11 mùa của Modern Family là gì?", "Giá trị cốt lõi của phim là gì?", ["Gia đình dù có ồn ào bất đồng nhưng luôn yêu thương và bao bọc nhau vô điều kiện", "Kiếm thật nhiều tiền mới hạnh phúc", "Càng ít gặp mặt gia đình càng tốt", "Chỉ gia đình hoàn hảo mới vui vẻ"], "Gia đình dù có ồn ào bất đồng nhưng luôn yêu thương và bao bọc nhau vô điều kiện", "Phim tôn vinh vẻ đẹp của sự bất toàn nhưng tràn đầy tình thân gắn kết.")
]);

// 9. Friends (B1-B2)
setQ("friends", [
  q("fr_1", "Quán cà phê quen thuộc nơi 6 người bạn tụ họp mỗi ngày ở Manhattan tên là gì?", "Tên quán cà phê là gì?", ["Central Perk", "Starbucks", "Coffee Bean", "Monk's Diner"], "Central Perk", "Central Perk với chiếc ghế sofa màu cam huyền thoại."),
  q("fr_2", "Câu cưa cẩm thương hiệu số một của Joey Tribbiani là gì?", "How you _______?", ["doin'", "feelin'", "sleepin'", "lookin'"], "doin'", "'How you doin'?' là câu cửa miệng tán gái kinh điển của Joey."),
  q("fr_3", "Cuộc tranh cãi nảy lửa giữa Ross và Rachel về việc tạm chia tay được gọi là:", "We were on a _______!", ["break", "trip", "vacation", "diet"], "break", "'We were on a break!' là đề tài tranh cãi kéo dài suốt 10 mùa."),
  q("fr_4", "Monica Geller có đặc điểm tính cách nổi tiếng nào khiến bạn bè vừa yêu vừa sợ?", "Monica nổi tiếng là người:", ["Obsessed with cleanliness and winning (Cuồng sạch sẽ và hiếu thắng)", "Messy and lazy", "Shy and quiet", "Forgetful"], "Obsessed with cleanliness and winning (Cuồng sạch sẽ và hiếu thắng)", "Monica mắc hội chứng ưa sạch sẽ ngăn nắp cực độ."),
  q("fr_5", "Công việc thực sự của Chandler Bing mà bạn bè không bao giờ nhớ nổi tên chính xác là gì?", "Nghề nghiệp của Chandler liên quan đến:", ["Statistical analysis and data reconfiguration", "Paleontology", "Acting", "Chef"], "Statistical analysis and data reconfiguration", "Mọi người hay đoán mò Chandler là 'Transponster' (từ bịa đặt)."),
  q("fr_6", "Ross Geller là tiến sĩ nghiên cứu chuyên ngành khoa học nào?", "Ross làm nghề gì?", ["Paleontologist (Nhà cổ sinh vật học)", "Surgeon", "Pilot", "Lawyer"], "Paleontologist (Nhà cổ sinh vật học)", "Ross là tiến sĩ cổ sinh vật học rất đam mê khủng long."),
  q("fr_7", "Bài hát nổi tiếng nhất của Phoebe Buffay về chú mèo bốc mùi tên là gì?", "Tên bài hát là gì?", ["Smelly Cat", "Lazy Dog", "Black Cat", "Tiny Mouse"], "Smelly Cat", "'Smelly Cat, Smelly Cat, what are they feeding you?'"),
  q("fr_8", "Joey không bao giờ chịu chia sẻ thứ gì với bất kỳ ai, kể cả bạn gái?", "Joey doesn't share _______!", ["food", "clothes", "money", "movies"], "food", "'Joey doesn't share food!' (Joey không bao giờ nhường đồ ăn đâu nhé!)."),
  q("fr_9", "Người quản lý tóc vàng thầm thương trộm nhớ Rachel suốt nhiều năm tại Central Perk là ai?", "Tên anh chàng pha chế là gì?", ["Gunther", "Mike", "Paul", "Richard"], "Gunther", "Gunther luôn âm thầm say đắm Rachel từ quầy thu ngân."),
  q("fr_10", "Cô bạn gái cũ nói giọng the thé kinh hoàng của Chandler hay kêu 'Oh... My... God!' tên là gì?", "Tên cô bạn gái là gì?", ["Janice", "Emily", "Ursula", "Amy"], "Janice", "Janice với giọng cười the thé như máy khoan cắt kính."),
  q("fr_11", "Khi Ross cố khiêng chiếc sofa lên cầu thang, anh liên tục hét to từ gì?", "Ross yelled:", ["Pivot!", "Faster!", "Stop!", "Drop!"], "Pivot!", "'Pivot! Pivot! Pivot!' (Xoay góc đi!)."),
  q("fr_12", "Cặp đôi nào trong nhóm đã bí mật hẹn hò tại London rồi đi đến hôn nhân hạnh phúc?", "Đó là cặp đôi nào?", ["Chandler and Monica", "Ross and Phoebe", "Joey and Rachel", "Gunther and Rachel"], "Chandler and Monica", "Mối tình ngọt ngào bất ngờ giữa Chandler và Monica."),
  q("fr_13", "Món bánh mì kẹp thịt gà tây tạ ơn của Ross có lớp sốt đặc biệt gọi là gì?", "Chiếc bánh sandwich của Ross có:", ["The Moist Maker (Một lát bánh mì nhúng nước sốt gravy ở giữa)", "Extra cheese", "Hot chili", "Chocolate"], "The Moist Maker (Một lát bánh mì nhúng nước sốt gravy ở giữa)", "Ross nổi điên khi có người ở bảo tàng ăn mất chiếc bánh sandwich này."),
  q("fr_14", "Chú khỉ cưng tinh nghịch mà Ross từng nuôi tên là gì?", "Tên chú khỉ đuôi dài là gì?", ["Marcel", "George", "Abu", "Kong"], "Marcel", "Chú khỉ Marcel từng thích nghe bài hát 'The Lion Sleeps Tonight'."),
  q("fr_15", "Hai con vật cưng kỳ quặc mà Joey và Chandler nuôi trong căn hộ của họ là gì?", "Hai con vật đó là:", ["A chick and a duck (Một con gà con và một con vịt)", "A dog and a cat", "Two rabbits", "A parrot and a snake"], "A chick and a duck (Một con gà con và một con vịt)", "Bộ đôi Gà và Vịt sống chung trong căn hộ của hai chàng trai."),
  q("fr_16", "Tại đám cưới ở London, Ross đã vô tình gọi nhầm tên cô dâu Emily thành tên ai?", "Ross đã gọi tên ai trước bàn thờ Chúa?", ["Rachel", "Monica", "Phoebe", "Janice"], "Rachel", "Ross lỡ lời nói: 'I take thee, Rachel' khiến đám cưới trở thành thảm họa."),
  q("fr_17", "Trong trò chơi cá cược căn hộ, câu hỏi khiến Monica và Rachel thua căn hộ là gì?", "Họ thua vì không trả lời được:", ["Công việc thực sự của Chandler Bing là gì", "Sinh nhật của Ross", "Cỡ giày của Joey", "Tên đệm của Phoebe"], "Công việc thực sự của Chandler Bing là gì", "Rachel hét lên 'He's a transponster!' và thua cuộc."),
  q("fr_18", "Tập cuối cùng, Rachel quyết định hủy chuyến bay đi Paris vì:", "Rachel nói gì khi xuất hiện ở cửa nhà Ross?", ["I got off the plane.", "I lost my passport.", "The flight was cancelled.", "I hate Paris."], "I got off the plane.", "'I got off the plane' (Em đã xuống máy bay rồi) là khoảnh khắc đoàn tụ viên mãn."),
  q("fr_19", "Thành ngữ 'You're my lobster' do Phoebe giải thích mang ý nghĩa gì?", "Nghĩa của câu nói là gì?", ["Bạn là người bạn đời định mệnh duy nhất của tôi", "Bạn giống con tôm hùm", "Tôi muốn ăn bạn", "Bạn có màu đỏ"], "Bạn là người bạn đời định mệnh duy nhất của tôi", "Phoebe tin rằng loài tôm hùm chỉ yêu một bạn tình duy nhất suốt đời."),
  q("fr_20", "Lý do sê-ri Friends được xem là giáo trình luyện nghe nói tiếng Anh số 1 là:", "Tại sao Friends giúp học tiếng Anh siêu hiệu quả?", ["Đối thoại tự nhiên, ngữ điệu chân thực, câu nói ngắn gọn và tiếng lóng Mỹ sống động", "Nói tiếng Anh cổ thời trung cổ", "Dùng toàn thuật ngữ y học phức tạp", "Chỉ có nhạc không có lời thoại"], "Đối thoại tự nhiên, ngữ điệu chân thực, câu nói ngắn gọn và tiếng lóng Mỹ sống động", "Friends hội tụ đầy đủ tiếng Anh giao tiếp chuẩn New York ứng dụng thực tế cao.")
]);

console.log("Saving full question banks 7-9...");
module.exports = { setQ, q };
