import { Topic } from "./types";

export const topics: Topic[] = [
  {
    id: "fruits-veggies",
    name: "Rau củ & Trái cây",
    icon: "🍎",
    color: "bg-red-100 text-red-600 border-red-200",
    words: [
      { id: "1", word: "apple", pronunciation: "/ˈæp.əl/", meaning: "táo", example: "I eat an apple every morning.", emoji: "🍎" },
      { id: "2", word: "banana", pronunciation: "/bəˈnɑː.nə/", meaning: "chuối", example: "The banana is ripe and sweet.", emoji: "🍌" },
      { id: "3", word: "orange", pronunciation: "/ˈɒr.ɪndʒ/", meaning: "cam", example: "She drank a glass of orange juice.", emoji: "🍊" },
      { id: "4", word: "grape", pronunciation: "/ɡreɪp/", meaning: "nho", example: "These grapes are very sweet.", emoji: "🍇" },
      { id: "5", word: "mango", pronunciation: "/ˈmæŋ.ɡəʊ/", meaning: "xoài", example: "Mango is my favorite fruit.", emoji: "🥭" },
      { id: "6", word: "pineapple", pronunciation: "/ˈpaɪnˌæp.əl/", meaning: "dứa", example: "We bought a fresh pineapple.", emoji: "🍍" },
      { id: "7", word: "watermelon", pronunciation: "/ˈwɔː.təˌmel.ən/", meaning: "dưa hấu", example: "The watermelon is refreshing.", emoji: "🍉" },
      { id: "8", word: "papaya", pronunciation: "/pəˈpaɪ.ə/", meaning: "đu đủ", example: "Papaya helps digestion.", emoji: "🍈" },
      { id: "9", word: "coconut", pronunciation: "/ˈkəʊ.kə.nʌt/", meaning: "dừa", example: "I like coconut water.", emoji: "🥥" },
      { id: "10", word: "lemon", pronunciation: "/ˈlem.ən/", meaning: "chanh vàng", example: "Add some lemon to the tea.", emoji: "🍋" },
      { id: "11", word: "lime", pronunciation: "/laɪm/", meaning: "chanh xanh", example: "Lime juice tastes sour.", emoji: "🍈" },
      { id: "12", word: "strawberry", pronunciation: "/ˈstrɔː.bər.i/", meaning: "dâu tây", example: "She grows strawberries.", emoji: "🍓" },
      { id: "13", word: "blueberry", pronunciation: "/ˈbluːˌber.i/", meaning: "việt quất", example: "Blueberries are healthy.", emoji: "🫐" },
      { id: "14", word: "raspberry", pronunciation: "/ˈrɑːz.bər.i/", meaning: "mâm xôi", example: "Raspberries are delicious.", emoji: "🍇" },
      { id: "15", word: "cherry", pronunciation: "/ˈtʃer.i/", meaning: "anh đào", example: "The cherries are red.", emoji: "🍒" },
      { id: "16", word: "peach", pronunciation: "/piːtʃ/", meaning: "đào", example: "This peach is juicy.", emoji: "🍑" },
      { id: "17", word: "pear", pronunciation: "/peər/", meaning: "lê", example: "I bought two pears.", emoji: "🍐" },
      { id: "18", word: "plum", pronunciation: "/plʌm/", meaning: "mận", example: "The plum is purple.", emoji: "🍑" },
      { id: "19", word: "kiwi", pronunciation: "/ˈkiː.wiː/", meaning: "kiwi", example: "Kiwi contains vitamin C.", emoji: "🥝" },
      { id: "20", word: "avocado", pronunciation: "/ˌæv.əˈkɑː.dəʊ/", meaning: "bơ", example: "Avocado is rich in nutrients.", emoji: "🥑" },
      { id: "21", word: "carrot", pronunciation: "/ˈkær.ət/", meaning: "cà rốt", example: "Rabbits like carrots.", emoji: "🥕" },
      { id: "22", word: "potato", pronunciation: "/pəˈteɪ.təʊ/", meaning: "khoai tây", example: "We cooked potatoes.", emoji: "🥔" },
      { id: "23", word: "tomato", pronunciation: "/təˈmɑː.təʊ/", meaning: "cà chua", example: "Tomatoes are used in salads.", emoji: "🍅" },
      { id: "24", word: "onion", pronunciation: "/ˈʌn.jən/", meaning: "hành tây", example: "The onion made me cry.", emoji: "🧅" },
      { id: "25", word: "garlic", pronunciation: "/ˈɡɑː.lɪk/", meaning: "tỏi", example: "Garlic adds flavor.", emoji: "🧄" },
      { id: "26", word: "cabbage", pronunciation: "/ˈkæb.ɪdʒ/", meaning: "bắp cải", example: "Cabbage is cheap today.", emoji: "🥬" },
      { id: "27", word: "lettuce", pronunciation: "/ˈlet.ɪs/", meaning: "rau diếp", example: "I need lettuce for the burger.", emoji: "🥬" },
      { id: "28", word: "spinach", pronunciation: "/ˈspɪn.ɪtʃ/", meaning: "rau chân vịt", example: "Spinach is nutritious.", emoji: "🥬" },
      { id: "29", word: "cucumber", pronunciation: "/ˈkjuː.kʌm.bər/", meaning: "dưa leo", example: "Slice the cucumber thinly.", emoji: "🥒" },
      { id: "30", word: "pumpkin", pronunciation: "/ˈpʌmp.kɪn/", meaning: "bí ngô", example: "Pumpkin soup is tasty.", emoji: "🎃" },
      { id: "31", word: "eggplant", pronunciation: "/ˈeɡ.plɑːnt/", meaning: "cà tím", example: "We grilled eggplant.", emoji: "🍆" },
      { id: "32", word: "broccoli", pronunciation: "/ˈbrɒk.əl.i/", meaning: "bông cải xanh", example: "Broccoli is healthy.", emoji: "🥦" },
      { id: "33", word: "cauliflower", pronunciation: "/ˈkɒl.ɪˌflaʊ.ər/", meaning: "súp lơ trắng", example: "Cauliflower is easy to cook.", emoji: "🥦" },
      { id: "34", word: "corn", pronunciation: "/kɔːn/", meaning: "bắp", example: "The corn is sweet.", emoji: "🌽" },
      { id: "35", word: "pea", pronunciation: "/piː/", meaning: "đậu Hà Lan", example: "Peas are rich in fiber.", emoji: "🫛" },
      { id: "36", word: "bean", pronunciation: "/biː/", meaning: "đậu", example: "She planted beans.", emoji: "🫘" },
      { id: "37", word: "mushroom", pronunciation: "/ˈmʌʃ.ruːm/", meaning: "nấm", example: "Mushrooms grow quickly.", emoji: "🍄" },
      { id: "38", word: "ginger", pronunciation: "/ˈdʒɪn.dʒər/", meaning: "gừng", example: "Ginger tea is warm.", emoji: "🫚" },
      { id: "39", word: "chili", pronunciation: "/ˈtʃɪl.i/", meaning: "ớt", example: "This chili is spicy.", emoji: "🌶️" },
      { id: "40", word: "radish", pronunciation: "/ˈræd.ɪʃ/", meaning: "củ cải", example: "Radishes are crunchy.", emoji: "🥬" },
      { id: "41", word: "beetroot", pronunciation: "/ˈbiːt.ruːt/", meaning: "củ dền", example: "Beetroot is red.", emoji: "🧅" },
      { id: "42", word: "celery", pronunciation: "/ˈsel.ər.i/", meaning: "cần tây", example: "Celery has a fresh taste.", emoji: "🥬" },
      { id: "43", word: "leek", pronunciation: "/liːk/", meaning: "tỏi tây", example: "Leeks are used in soup.", emoji: "🧅" },
      { id: "44", word: "sweet potato", pronunciation: "/ˌswiːt pəˈteɪ.təʊ/", meaning: "khoai lang", example: "Sweet potatoes are nutritious.", emoji: "🍠" },
      { id: "45", word: "yam", pronunciation: "/jæm/", meaning: "khoai mỡ", example: "Yams are popular here.", emoji: "🍠" },
      { id: "46", word: "turnip", pronunciation: "/ˈtɜː.nɪp/", meaning: "củ cải trắng", example: "Turnips grow underground.", emoji: "🧅" },
      { id: "47", word: "zucchini", pronunciation: "/zuˈkiː.ni/", meaning: "bí ngòi", example: "Zucchini is easy to cook.", emoji: "🥒" },
      { id: "48", word: "durian", pronunciation: "/ˈdʒʊə.ri.ən/", meaning: "sầu riêng", example: "Durian has a strong smell.", emoji: "🍈" },
      { id: "49", word: "jackfruit", pronunciation: "/ˈdʒæk.fruːt/", meaning: "mít", example: "Jackfruit is sweet.", emoji: "🍈" },
      { id: "50", word: "dragon fruit", pronunciation: "/ˈdræɡ.ən fruːt/", meaning: "thanh long", example: "Dragon fruit is popular in Vietnam.", emoji: "🐉" }
    ]
  },
  {
    id: "animals",
    name: "Động vật",
    icon: "🐶",
    color: "bg-amber-100 text-amber-600 border-amber-200",
    words: [
      { id: "51", word: "dog", pronunciation: "/dɒɡ/", meaning: "chó", example: "My dog is friendly.", emoji: "🐶" },
      { id: "52", word: "cat", pronunciation: "/kæt/", meaning: "mèo", example: "The cat is sleeping.", emoji: "🐱" },
      { id: "53", word: "rabbit", pronunciation: "/ˈræb.ɪt/", meaning: "thỏ", example: "The rabbit eats carrots.", emoji: "🐰" },
      { id: "54", word: "horse", pronunciation: "/hɔːs/", meaning: "ngựa", example: "The horse runs fast.", emoji: "🐴" },
      { id: "55", word: "cow", pronunciation: "/kaʊ/", meaning: "bò", example: "The cow produces milk.", emoji: "🐮" },
      { id: "56", word: "buffalo", pronunciation: "/ˈbʌf.ə.ləʊ/", meaning: "trâu", example: "The buffalo works in the field.", emoji: "🐃" },
      { id: "57", word: "goat", pronunciation: "/ɡəʊt/", meaning: "dê", example: "The goat climbed the hill.", emoji: "🐐" },
      { id: "58", word: "sheep", pronunciation: "/ʃiːp/", meaning: "cừu", example: "The sheep are grazing.", emoji: "🐑" },
      { id: "59", word: "pig", pronunciation: "/pɪɡ/", meaning: "heo", example: "The pig is eating.", emoji: "🐷" },
      { id: "60", word: "chicken", pronunciation: "/ˈtʃɪk.ɪn/", meaning: "gà", example: "The chicken laid an egg.", emoji: "🐔" },
      { id: "61", word: "duck", pronunciation: "/dʌk/", meaning: "vịt", example: "The duck is swimming.", emoji: "🦆" },
      { id: "62", word: "goose", pronunciation: "/ɡuːs/", meaning: "ngỗng", example: "The goose is noisy.", emoji: "🪿" },
      { id: "63", word: "turkey", pronunciation: "/ˈtɜː.ki/", meaning: "gà tây", example: "We ate turkey for dinner.", emoji: "🦃" },
      { id: "64", word: "pigeon", pronunciation: "/ˈpɪdʒ.ən/", meaning: "chim bồ câu", example: "A pigeon landed nearby.", emoji: "🕊️" },
      { id: "65", word: "sparrow", pronunciation: "/ˈspær.əʊ/", meaning: "chim sẻ", example: "The sparrow sang beautifully.", emoji: "🐦" },
      { id: "66", word: "eagle", pronunciation: "/ˈiː.ɡəl/", meaning: "đại bàng", example: "The eagle flew high.", emoji: "🦅" },
      { id: "67", word: "owl", pronunciation: "/aʊl/", meaning: "cú mèo", example: "The owl hunts at night.", emoji: "🦉" },
      { id: "68", word: "parrot", pronunciation: "/ˈpær.ət/", meaning: "vẹt", example: "The parrot can talk.", emoji: "🦜" },
      { id: "69", word: "crow", pronunciation: "/krəʊ/", meaning: "quạ", example: "The crow is intelligent.", emoji: "🐦‍⬛" },
      { id: "70", word: "swan", pronunciation: "/swɒn/", meaning: "thiên nga", example: "The swan is elegant.", emoji: "🦢" },
      { id: "71", word: "lion", pronunciation: "/ˈlaɪ.ən/", meaning: "sư tử", example: "The lion is strong.", emoji: "🦁" },
      { id: "72", word: "tiger", pronunciation: "/ˈtaɪ.ɡər/", meaning: "hổ", example: "Tigers are endangered.", emoji: "🐯" },
      { id: "73", word: "leopard", pronunciation: "/ˈlep.əd/", meaning: "báo hoa mai", example: "The leopard climbed a tree.", emoji: "🐆" },
      { id: "74", word: "cheetah", pronunciation: "/ˈtʃiː.tə/", meaning: "báo gê-pa", example: "The cheetah is fast.", emoji: "🐆" },
      { id: "75", word: "elephant", pronunciation: "/ˈel.ɪ.fənt/", meaning: "voi", example: "Elephants have long trunks.", emoji: "🐘" },
      { id: "76", word: "giraffe", pronunciation: "/dʒɪˈrɑːf/", meaning: "hươu cao cổ", example: "The giraffe has a long neck.", emoji: "🦒" },
      { id: "77", word: "zebra", pronunciation: "/ˈzeb.rə/", meaning: "ngựa vằn", example: "Zebras have stripes.", emoji: "🦓" },
      { id: "78", word: "monkey", pronunciation: "/ˈmʌŋ.ki/", meaning: "khỉ", example: "The monkey climbed the tree.", emoji: "🐒" },
      { id: "79", word: "gorilla", pronunciation: "/ɡəˈrɪl.ə/", meaning: "khỉ đột", example: "Gorillas are powerful.", emoji: "🦍" },
      { id: "80", word: "bear", pronunciation: "/beər/", meaning: "gấu", example: "The bear lives in the forest.", emoji: "🐻" },
      { id: "81", word: "deer", pronunciation: "/dɪər/", meaning: "nai", example: "We saw a deer yesterday.", emoji: "🦌" },
      { id: "82", word: "fox", pronunciation: "/fɒks/", meaning: "cáo", example: "The fox is clever.", emoji: "🦊" },
      { id: "83", word: "wolf", pronunciation: "/wʊlf/", meaning: "sói", example: "Wolves hunt in packs.", emoji: "🐺" },
      { id: "84", word: "kangaroo", pronunciation: "/ˌkæŋ.ɡəˈruː/", meaning: "chuột túi", example: "Kangaroos live in Australia.", emoji: "🦘" },
      { id: "85", word: "koala", pronunciation: "/kəʊˈɑː.lə/", meaning: "gấu túi", example: "The koala eats eucalyptus leaves.", emoji: "🐨" },
      { id: "86", word: "panda", pronunciation: "/ˈpæn.də/", meaning: "gấu trúc", example: "Pandas love bamboo.", emoji: "🐼" },
      { id: "87", word: "dolphin", pronunciation: "/ˈdɒl.fɪn/", meaning: "cá heo", example: "Dolphins are intelligent.", emoji: "🐬" },
      { id: "88", word: "whale", pronunciation: "/weɪl/", meaning: "cá voi", example: "The whale is huge.", emoji: "🐳" },
      { id: "89", word: "shark", pronunciation: "/ʃɑːk/", meaning: "cá mập", example: "Sharks are predators.", emoji: "🦈" },
      { id: "90", word: "octopus", pronunciation: "/ˈɒk.tə.pəs/", meaning: "bạch tuộc", example: "The octopus has eight arms.", emoji: "🐙" },
      { id: "91", word: "crab", pronunciation: "/kræb/", meaning: "cua", example: "The crab moved sideways.", emoji: "🦀" },
      { id: "92", word: "lobster", pronunciation: "/ˈlɒb.stər/", meaning: "tôm hùm", example: "Lobster is expensive.", emoji: "🦞" },
      { id: "93", word: "shrimp", pronunciation: "/ʃrɪmp/", meaning: "tôm", example: "I like grilled shrimp.", emoji: "🦐" },
      { id: "94", word: "frog", pronunciation: "/frɒɡ/", meaning: "ếch", example: "The frog jumped away.", emoji: "🐸" },
      { id: "95", word: "snake", pronunciation: "/sneɪk/", meaning: "rắn", example: "The snake disappeared quickly.", emoji: "🐍" },
      { id: "96", word: "crocodile", pronunciation: "/ˈkrɒk.ə.daɪl/", meaning: "cá sấu", example: "The crocodile is dangerous.", emoji: "🐊" },
      { id: "97", word: "turtle", pronunciation: "/ˈtɜː.təl/", meaning: "rùa", example: "The turtle moves slowly.", emoji: "🐢" },
      { id: "98", word: "lizard", pronunciation: "/ˈlɪz.əd/", meaning: "thằn lằn", example: "A lizard was on the wall.", emoji: "🦎" },
      { id: "99", word: "ant", pronunciation: "/ænt/", meaning: "kiến", example: "Ants work together.", emoji: "🐜" },
      { id: "100", word: "bee", pronunciation: "/biː/", meaning: "ong", example: "Bees make honey.", emoji: "🐝" }
    ]
  },
  {
    id: "everyday",
    name: "Vật dụng hàng ngày",
    icon: "🛋️",
    color: "bg-blue-100 text-blue-600 border-blue-200",
    words: [
      { id: "101", word: "table", pronunciation: "/ˈteɪ.bəl/", meaning: "cái bàn", example: "The books are on the table.", emoji: "🪑" },
      { id: "102", word: "chair", pronunciation: "/tʃeər/", meaning: "cái ghế", example: "Please sit on the chair.", emoji: "🪑" },
      { id: "103", word: "bed", pronunciation: "/bed/", meaning: "cái giường", example: "I went to bed early.", emoji: "🛏️" },
      { id: "104", word: "pillow", pronunciation: "/ˈpɪl.əʊ/", meaning: "gối", example: "This pillow is soft.", emoji: "🛏️" },
      { id: "105", word: "blanket", pronunciation: "/ˈblæŋ.kɪt/", meaning: "chăn", example: "The blanket keeps me warm.", emoji: "🧣" },
      { id: "106", word: "wardrobe", pronunciation: "/ˈwɔː.drəʊb/", meaning: "tủ quần áo", example: "My clothes are in the wardrobe.", emoji: "🚪" },
      { id: "107", word: "cabinet", pronunciation: "/ˈkæb.ɪ.nət/", meaning: "tủ", example: "The dishes are in the cabinet.", emoji: "🗄️" },
      { id: "108", word: "shelf", pronunciation: "/ʃelf/", meaning: "kệ", example: "Put the books on the shelf.", emoji: "📚" },
      { id: "109", word: "mirror", pronunciation: "/ˈmɪr.ər/", meaning: "gương", example: "She looked in the mirror.", emoji: "🪞" },
      { id: "110", word: "clock", pronunciation: "/klɒk/", meaning: "đồng hồ treo tường", example: "The clock shows 8 o'clock.", emoji: "🕰️" },
      { id: "111", word: "watch", pronunciation: "/wɒtʃ/", meaning: "đồng hồ đeo tay", example: "My watch is new.", emoji: "⌚" },
      { id: "112", word: "lamp", pronunciation: "/læmp/", meaning: "đèn bàn", example: "Turn on the lamp.", emoji: "🪔" },
      { id: "113", word: "light bulb", pronunciation: "/ˈlaɪt bʌlb/", meaning: "bóng đèn", example: "The light bulb is broken.", emoji: "💡" },
      { id: "114", word: "fan", pronunciation: "/fæn/", meaning: "quạt", example: "The fan is spinning.", emoji: "🪭" },
      { id: "115", word: "air conditioner", pronunciation: "/ˈeə kənˌdɪʃ.ən.ər/", meaning: "máy lạnh", example: "The air conditioner is on.", emoji: "❄️" },
      { id: "116", word: "television", pronunciation: "/ˈtel.ɪ.vɪʒ.ən/", meaning: "tivi", example: "We watched television all night.", emoji: "📺" },
      { id: "117", word: "remote control", pronunciation: "/rɪˈməʊt kənˌtrəʊl/", meaning: "điều khiển từ xa", example: "Where is the remote control?", emoji: "🎛️" },
      { id: "118", word: "refrigerator", pronunciation: "/rɪˈfrɪdʒ.ər.eɪ.tər/", meaning: "tủ lạnh", example: "The milk is in the refrigerator.", emoji: "🧊" },
      { id: "119", word: "microwave", pronunciation: "/ˈmaɪ.krə.weɪv/", meaning: "lò vi sóng", example: "Heat the food in the microwave.", emoji: "♨️" },
      { id: "120", word: "oven", pronunciation: "/ˈʌv.ən/", meaning: "lò nướng", example: "The cake is in the oven.", emoji: "🍳" },
      { id: "121", word: "stove", pronunciation: "/stəʊv/", meaning: "bếp", example: "She is cooking on the stove.", emoji: "🔥" },
      { id: "122", word: "kettle", pronunciation: "/ˈket.əl/", meaning: "ấm đun nước", example: "The kettle is boiling.", emoji: "🫖" },
      { id: "123", word: "cup", pronunciation: "/kʌp/", meaning: "cái cốc", example: "I drank a cup of coffee.", emoji: "☕" },
      { id: "124", word: "mug", pronunciation: "/mʌɡ/", meaning: "ly sứ", example: "This mug is large.", emoji: "🍵" },
      { id: "125", word: "glass", pronunciation: "/ɡlɑːs/", meaning: "ly thủy tinh", example: "The glass is full of water.", emoji: "🥛" },
      { id: "126", word: "plate", pronunciation: "/pleɪt/", meaning: "cái đĩa", example: "Put the food on the plate.", emoji: "🍽️" },
      { id: "127", word: "bowl", pronunciation: "/bəʊl/", meaning: "cái tô", example: "The soup is in the bowl.", emoji: "🥣" },
      { id: "128", word: "spoon", pronunciation: "/spuːn/", meaning: "cái muỗng", example: "Use a spoon to eat.", emoji: "🥄" },
      { id: "129", word: "fork", pronunciation: "/fɔːk/", meaning: "cái nĩa", example: "The fork is on the table.", emoji: "🍴" },
      { id: "130", word: "knife", pronunciation: "/naɪf/", meaning: "con dao", example: "Be careful with the knife.", emoji: "🔪" },
      { id: "131", word: "chopsticks", pronunciation: "/ˈtʃɒp.stɪks/", meaning: "đũa", example: "I eat rice with chopsticks.", emoji: "🥢" },
      { id: "132", word: "pan", pronunciation: "/pæn/", meaning: "chảo", example: "Eggs are frying in the pan.", emoji: "🍳" },
      { id: "133", word: "pot", pronunciation: "/pɒt/", meaning: "nồi", example: "The pot is on the stove.", emoji: "🍲" },
      { id: "134", word: "bucket", pronunciation: "/ˈbʌk.ɪt/", meaning: "cái xô", example: "Fill the bucket with water.", emoji: "🪣" },
      { id: "135", word: "broom", pronunciation: "/bruːm/", meaning: "chổi", example: "She swept the floor with a broom.", emoji: "🧹" },
      { id: "136", word: "mop", pronunciation: "/mɒp/", meaning: "cây lau nhà", example: "The mop is wet.", emoji: "🧹" },
      { id: "137", word: "towel", pronunciation: "/ˈtaʊ.əl/", meaning: "khăn tắm", example: "Dry yourself with a towel.", emoji: "🧖" },
      { id: "138", word: "toothbrush", pronunciation: "/ˈtuːθ.brʌʃ/", meaning: "bàn chải đánh răng", example: "I need a new toothbrush.", emoji: "🪥" },
      { id: "139", word: "toothpaste", pronunciation: "/ˈtuːθ.peɪst/", meaning: "kem đánh răng", example: "This toothpaste smells fresh.", emoji: "🪥" },
      { id: "140", word: "soap", pronunciation: "/səʊp/", meaning: "xà phòng", example: "Wash your hands with soap.", emoji: "🧼" },
      { id: "141", word: "shampoo", pronunciation: "/ʃæmˈpuː/", meaning: "dầu gội", example: "The shampoo smells nice.", emoji: "🧴" },
      { id: "142", word: "comb", pronunciation: "/kəʊm/", meaning: "lược", example: "He used a comb for his hair.", emoji: "🪮" },
      { id: "143", word: "hair dryer", pronunciation: "/ˈheə ˌdraɪ.ər/", meaning: "máy sấy tóc", example: "The hair dryer is noisy.", emoji: "💨" },
      { id: "144", word: "backpack", pronunciation: "/ˈbæk.pæk/", meaning: "ba lô", example: "My laptop is in the backpack.", emoji: "🎒" },
      { id: "145", word: "suitcase", pronunciation: "/ˈsuːt.keɪs/", meaning: "va li", example: "She packed her suitcase.", emoji: "🧳" },
      { id: "146", word: "wallet", pronunciation: "/ˈwɒl.ɪt/", meaning: "ví tiền", example: "My wallet is missing.", emoji: "👛" },
      { id: "147", word: "key", pronunciation: "/kiː/", meaning: "chìa khóa", example: "I can't find my key.", emoji: "🔑" },
      { id: "148", word: "lock", pronunciation: "/lɒk/", meaning: "ổ khóa", example: "The lock is secure.", emoji: "🔒" },
      { id: "149", word: "umbrella", pronunciation: "/ʌmˈbrel.ə/", meaning: "ô dù", example: "Take an umbrella with you.", emoji: "☂️" },
      { id: "150", word: "scissors", pronunciation: "/ˈsɪz.əz/", meaning: "kéo", example: "Cut the paper with scissors.", emoji: "✂️" }
    ]
  },
  {
    id: "streets",
    name: "Đường phố",
    icon: "🚦",
    color: "bg-stone-100 text-stone-600 border-stone-200",
    words: [
      { id: "151", word: "street", pronunciation: "/striːt/", meaning: "đường phố", example: "The street is crowded.", emoji: "🛣️" },
      { id: "152", word: "road", pronunciation: "/rəʊd/", meaning: "con đường", example: "This road leads to the city.", emoji: "🛣️" },
      { id: "153", word: "avenue", pronunciation: "/ˈæv.ə.njuː/", meaning: "đại lộ", example: "They live on a busy avenue.", emoji: "🏙️" },
      { id: "154", word: "lane", pronunciation: "/leɪn/", meaning: "ngõ nhỏ", example: "The lane is very narrow.", emoji: "🛤️" },
      { id: "155", word: "alley", pronunciation: "/ˈæl.i/", meaning: "hẻm", example: "The shop is in the alley.", emoji: "🛣️" },
      { id: "156", word: "sidewalk", pronunciation: "/ˈsaɪd.wɔːk/", meaning: "vỉa hè", example: "Walk on the sidewalk.", emoji: "🚶" },
      { id: "157", word: "pavement", pronunciation: "/ˈpeɪv.mənt/", meaning: "vỉa hè", example: "The pavement is clean.", emoji: "🚶" },
      { id: "158", word: "intersection", pronunciation: "/ˌɪn.təˈsek.ʃən/", meaning: "ngã tư", example: "Stop at the intersection.", emoji: "🔀" },
      { id: "159", word: "crosswalk", pronunciation: "/ˈkrɒs.wɔːk/", meaning: "vạch qua đường", example: "Use the crosswalk safely.", emoji: "🦓" },
      { id: "160", word: "traffic light", pronunciation: "/ˈtræf.ɪk laɪt/", meaning: "đèn giao thông", example: "The traffic light turned green.", emoji: "🚥" },
      { id: "161", word: "traffic sign", pronunciation: "/ˈtræf.ɪk saɪn/", meaning: "biển báo giao thông", example: "Read the traffic signs carefully.", emoji: "🚸" },
      { id: "162", word: "bridge", pronunciation: "/brɪdʒ/", meaning: "cây cầu", example: "We crossed the bridge.", emoji: "🌉" },
      { id: "163", word: "tunnel", pronunciation: "/ˈtʌn.əl/", meaning: "đường hầm", example: "The tunnel is long.", emoji: "🚇" },
      { id: "164", word: "roundabout", pronunciation: "/ˈraʊnd.ə.baʊt/", meaning: "vòng xoay", example: "Take the second exit at the roundabout.", emoji: "🔄" },
      { id: "165", word: "bus stop", pronunciation: "/ˈbʌs stɒp/", meaning: "trạm xe buýt", example: "We waited at the bus stop.", emoji: "🚏" },
      { id: "166", word: "station", pronunciation: "/ˈsteɪ.ʃən/", meaning: "nhà ga", example: "The station is nearby.", emoji: "🚉" },
      { id: "167", word: "parking lot", pronunciation: "/ˈpɑː.kɪŋ lɒt/", meaning: "bãi đỗ xe", example: "The parking lot is full.", emoji: "🅿️" },
      { id: "168", word: "gas station", pronunciation: "/ˈɡæs steɪ.ʃən/", meaning: "cây xăng", example: "Let's stop at the gas station.", emoji: "⛽" },
      { id: "169", word: "highway", pronunciation: "/ˈhaɪ.weɪ/", meaning: "đường cao tốc", example: "Cars move fast on the highway.", emoji: "🛣️" },
      { id: "170", word: "expressway", pronunciation: "/ɪkˈspres.weɪ/", meaning: "đường cao tốc", example: "The expressway saves time.", emoji: "🛣️" },
      { id: "171", word: "vehicle", pronunciation: "/ˈviː.ɪ.kəl/", meaning: "phương tiện", example: "Every vehicle must stop here.", emoji: "🚗" },
      { id: "172", word: "bicycle", pronunciation: "/ˈbaɪ.sɪ.kəl/", meaning: "xe đạp", example: "She rides a bicycle to work.", emoji: "🚲" },
      { id: "173", word: "motorbike", pronunciation: "/ˈməʊ.tə.baɪk/", meaning: "xe máy", example: "Motorbikes are common in Vietnam.", emoji: "🏍️" },
      { id: "174", word: "scooter", pronunciation: "/ˈskuː.tər/", meaning: "xe tay ga", example: "He bought a new scooter.", emoji: "🛵" },
      { id: "175", word: "car", pronunciation: "/kɑːr/", meaning: "ô tô", example: "Their car is expensive.", emoji: "🚗" },
      { id: "176", word: "taxi", pronunciation: "/ˈtæk.si/", meaning: "taxi", example: "We took a taxi home.", emoji: "🚕" },
      { id: "177", word: "bus", pronunciation: "/bʌs/", meaning: "xe buýt", example: "The bus arrives at 7 AM.", emoji: "🚌" },
      { id: "178", word: "truck", pronunciation: "/trʌk/", meaning: "xe tải", example: "The truck carries goods.", emoji: "🚚" },
      { id: "179", word: "van", pronunciation: "/væn/", meaning: "xe tải nhỏ", example: "A van stopped outside.", emoji: "🚐" },
      { id: "180", word: "train", pronunciation: "/treɪn/", meaning: "tàu hỏa", example: "The train left the station.", emoji: "🚂" },
      { id: "181", word: "subway", pronunciation: "/ˈsʌb.weɪ/", meaning: "tàu điện ngầm", example: "I use the subway daily.", emoji: "🚇" },
      { id: "182", word: "airplane", pronunciation: "/ˈeə.pleɪn/", meaning: "máy bay", example: "The airplane landed safely.", emoji: "✈️" },
      { id: "183", word: "airport", pronunciation: "/ˈeə.pɔːt/", meaning: "sân bay", example: "We arrived at the airport early.", emoji: "🛫" },
      { id: "184", word: "helmet", pronunciation: "/ˈhel.mɪt/", meaning: "mũ bảo hiểm", example: "Always wear a helmet.", emoji: "⛑️" },
      { id: "185", word: "seat belt", pronunciation: "/ˈsiːt belt/", meaning: "dây an toàn", example: "Fasten your seat belt.", emoji: "💺" },
      { id: "186", word: "driver", pronunciation: "/ˈdraɪ.vər/", meaning: "tài xế", example: "The driver was careful.", emoji: "🧑‍✈️" },
      { id: "187", word: "passenger", pronunciation: "/ˈpæs.ən.dʒər/", meaning: "hành khách", example: "The passengers boarded the bus.", emoji: "🧳" },
      { id: "188", word: "pedestrian", pronunciation: "/pəˈdes.tri.ən/", meaning: "người đi bộ", example: "Pedestrians should use crosswalks.", emoji: "🚶" },
      { id: "189", word: "traffic jam", pronunciation: "/ˈtræf.ɪk dʒæm/", meaning: "kẹt xe", example: "We were stuck in a traffic jam.", emoji: "🚗🚕🚚" },
      { id: "190", word: "accident", pronunciation: "/ˈæk.sɪ.dənt/", meaning: "tai nạn", example: "The accident blocked the road.", emoji: "💥" },
      { id: "191", word: "speed limit", pronunciation: "/ˈspiːd ˌlɪm.ɪt/", meaning: "giới hạn tốc độ", example: "Follow the speed limit.", emoji: "🛑" },
      { id: "192", word: "police officer", pronunciation: "/pəˈliːs ˌɒf.ɪ.sər/", meaning: "cảnh sát", example: "The police officer directed traffic.", emoji: "👮" },
      { id: "193", word: "map", pronunciation: "/mæp/", meaning: "bản đồ", example: "Check the map first.", emoji: "🗺️" },
      { id: "194", word: "direction", pronunciation: "/dəˈrek.ʃən/", meaning: "phương hướng", example: "Can you give me directions?", emoji: "🧭" },
      { id: "195", word: "downtown", pronunciation: "/ˌdaʊnˈtaʊn/", meaning: "trung tâm thành phố", example: "The office is downtown.", emoji: "🏙️" },
      { id: "196", word: "neighborhood", pronunciation: "/ˈneɪ.bə.hʊd/", meaning: "khu dân cư", example: "It's a quiet neighborhood.", emoji: "🏡" },
      { id: "197", word: "building", pronunciation: "/ˈbɪl.dɪŋ/", meaning: "tòa nhà", example: "That building is very tall.", emoji: "🏢" },
      { id: "198", word: "apartment", pronunciation: "/əˈpɑːt.mənt/", meaning: "căn hộ", example: "She lives in an apartment.", emoji: "🏢" },
      { id: "199", word: "market", pronunciation: "/ˈmɑː.kɪt/", meaning: "chợ", example: "The market opens early.", emoji: "🛒" },
      { id: "200", word: "park", pronunciation: "/pɑːk/", meaning: "công viên", example: "Children are playing in the park.", emoji: "🏞️" }
    ]
  },
  {
    id: "human-body",
    name: "Cơ thể",
    icon: "🧠",
    color: "bg-rose-100 text-rose-600 border-rose-200",
    words: [
      { id: "201", word: "head", pronunciation: "/hed/", meaning: "đầu", example: "My head hurts.", emoji: "🗣️" },
      { id: "202", word: "face", pronunciation: "/feɪs/", meaning: "khuôn mặt", example: "She has a beautiful face.", emoji: "👱‍♀️" },
      { id: "203", word: "hair", pronunciation: "/heər/", meaning: "tóc", example: "His hair is black.", emoji: "💇" },
      { id: "204", word: "forehead", pronunciation: "/ˈfɔː.hed/", meaning: "trán", example: "She touched her forehead.", emoji: "🤕" },
      { id: "205", word: "eye", pronunciation: "/aɪ/", meaning: "mắt", example: "Her eyes are blue.", emoji: "👁️" },
      { id: "206", word: "eyebrow", pronunciation: "/ˈaɪ.braʊ/", meaning: "lông mày", example: "He raised his eyebrows.", emoji: "🤨" },
      { id: "207", word: "eyelash", pronunciation: "/ˈaɪ.læʃ/", meaning: "lông mi", example: "She has long eyelashes.", emoji: "👁️" },
      { id: "208", word: "ear", pronunciation: "/ɪər/", meaning: "tai", example: "My ear is itchy.", emoji: "👂" },
      { id: "209", word: "nose", pronunciation: "/nəʊz/", meaning: "mũi", example: "His nose is small.", emoji: "👃" },
      { id: "210", word: "nostril", pronunciation: "/ˈnɒs.trəl/", meaning: "lỗ mũi", example: "The doctor checked my nostrils.", emoji: "👃" },
      { id: "211", word: "mouth", pronunciation: "/maʊθ/", meaning: "miệng", example: "Open your mouth.", emoji: "👄" },
      { id: "212", word: "lip", pronunciation: "/lɪp/", meaning: "môi", example: "Her lips are dry.", emoji: "👄" },
      { id: "213", word: "tooth", pronunciation: "/tuːθ/", meaning: "răng", example: "I brushed my teeth.", emoji: "🦷" },
      { id: "214", word: "teeth", pronunciation: "/tiːθ/", meaning: "hàm răng", example: "His teeth are white.", emoji: "🦷" },
      { id: "215", word: "tongue", pronunciation: "/tʌŋ/", meaning: "lưỡi", example: "The soup burned my tongue.", emoji: "👅" },
      { id: "216", word: "chin", pronunciation: "/tʃɪn/", meaning: "cằm", example: "He touched his chin.", emoji: "🧔‍♂️" },
      { id: "217", word: "cheek", pronunciation: "/tʃiːk/", meaning: "má", example: "The baby has chubby cheeks.", emoji: "😊" },
      { id: "218", word: "neck", pronunciation: "/nek/", meaning: "cổ", example: "My neck feels stiff.", emoji: "🧣" },
      { id: "219", word: "shoulder", pronunciation: "/ˈʃəʊl.dər/", meaning: "vai", example: "She carried the bag on her shoulder.", emoji: "🤷" },
      { id: "220", word: "arm", pronunciation: "/ɑːm/", meaning: "cánh tay", example: "He raised his arm.", emoji: "💪" },
      { id: "221", word: "elbow", pronunciation: "/ˈel.bəʊ/", meaning: "khuỷu tay", example: "I hit my elbow.", emoji: "💪" },
      { id: "222", word: "wrist", pronunciation: "/rɪst/", meaning: "cổ tay", example: "She wears a watch on her wrist.", emoji: "⌚" },
      { id: "223", word: "hand", pronunciation: "/hænd/", meaning: "bàn tay", example: "Wash your hands.", emoji: "🖐️" },
      { id: "224", word: "finger", pronunciation: "/ˈfɪŋ.ɡər/", meaning: "ngón tay", example: "Point with your finger.", emoji: "☝️" },
      { id: "225", word: "thumb", pronunciation: "/θʌm/", meaning: "ngón cái", example: "Give me a thumbs up.", emoji: "👍" },
      { id: "226", word: "nail", pronunciation: "/neɪl/", meaning: "móng tay", example: "She painted her nails.", emoji: "💅" },
      { id: "227", word: "chest", pronunciation: "/tʃest/", meaning: "ngực", example: "He felt pain in his chest.", emoji: "🫁" },
      { id: "228", word: "back", pronunciation: "/bæk/", meaning: "lưng", example: "My back is sore.", emoji: "🔙" },
      { id: "229", word: "waist", pronunciation: "/weɪst/", meaning: "eo", example: "She has a slim waist.", emoji: "🧍" },
      { id: "230", word: "stomach", pronunciation: "/ˈstʌm.ək/", meaning: "dạ dày, bụng", example: "My stomach is full.", emoji: "🤰" },
      { id: "231", word: "hip", pronunciation: "/hɪp/", meaning: "hông", example: "He injured his hip.", emoji: "🚶" },
      { id: "232", word: "leg", pronunciation: "/leɡ/", meaning: "chân", example: "My leg hurts.", emoji: "🦵" },
      { id: "233", word: "knee", pronunciation: "/niː/", meaning: "đầu gối", example: "Bend your knees.", emoji: "🦵" },
      { id: "234", word: "ankle", pronunciation: "/ˈæŋ.kəl/", meaning: "mắt cá chân", example: "She twisted her ankle.", emoji: "🦶" },
      { id: "235", word: "foot", pronunciation: "/fʊt/", meaning: "bàn chân", example: "My foot is tired.", emoji: "🦶" },
      { id: "236", word: "toe", pronunciation: "/təʊ/", meaning: "ngón chân", example: "I stubbed my toe.", emoji: "🦶" },
      { id: "237", word: "skin", pronunciation: "/skɪn/", meaning: "da", example: "Protect your skin from the sun.", emoji: "🧴" },
      { id: "238", word: "blood", pronunciation: "/blʌd/", meaning: "máu", example: "Blood carries oxygen.", emoji: "🩸" },
      { id: "239", word: "bone", pronunciation: "/bəʊn/", meaning: "xương", example: "The bone was broken.", emoji: "🦴" },
      { id: "240", word: "muscle", pronunciation: "/ˈmʌs.əl/", meaning: "cơ bắp", example: "Exercise builds muscle.", emoji: "💪" },
      { id: "241", word: "heart", pronunciation: "/hɑːt/", meaning: "tim", example: "My heart beats fast.", emoji: "❤️" },
      { id: "242", word: "lung", pronunciation: "/lʌŋ/", meaning: "phổi", example: "Smoking damages the lungs.", emoji: "🫁" },
      { id: "243", word: "brain", pronunciation: "/breɪn/", meaning: "não", example: "The brain controls the body.", emoji: "🧠" },
      { id: "244", word: "liver", pronunciation: "/ˈlɪv.ər/", meaning: "gan", example: "The liver is important.", emoji: "🩸" },
      { id: "245", word: "kidney", pronunciation: "/ˈkɪd.ni/", meaning: "thận", example: "The kidneys filter blood.", emoji: "🩸" },
      { id: "246", word: "throat", pronunciation: "/θrəʊt/", meaning: "cổ họng", example: "My throat is sore.", emoji: "🗣️" },
      { id: "247", word: "beard", pronunciation: "/bɪəd/", meaning: "râu", example: "He has a long beard.", emoji: "🧔" },
      { id: "248", word: "mustache", pronunciation: "/məˈstɑːʃ/", meaning: "ria mép", example: "His mustache looks neat.", emoji: "🧔" },
      { id: "249", word: "jaw", pronunciation: "/dʒɔː/", meaning: "quai hàm", example: "He clenched his jaw.", emoji: "💀" },
      { id: "250", word: "palm", pronunciation: "/pɑːm/", meaning: "lòng bàn tay", example: "She held the coin in her palm.", emoji: "🖐️" }
    ]
  },
  {
    id: "clothing",
    name: "Trang phục",
    icon: "👕",
    color: "bg-purple-100 text-purple-600 border-purple-200",
    words: [
      { id: "251", word: "shirt", pronunciation: "/ʃɜːt/", meaning: "áo sơ mi", example: "He wears a white shirt.", emoji: "👔" },
      { id: "252", word: "T-shirt", pronunciation: "/ˈtiː.ʃɜːt/", meaning: "áo thun", example: "I bought a new T-shirt.", emoji: "👕" },
      { id: "253", word: "blouse", pronunciation: "/blaʊz/", meaning: "áo kiểu nữ", example: "She wore a blue blouse.", emoji: "👚" },
      { id: "254", word: "jacket", pronunciation: "/ˈdʒæk.ɪt/", meaning: "áo khoác", example: "Take your jacket.", emoji: "🧥" },
      { id: "255", word: "coat", pronunciation: "/kəʊt/", meaning: "áo choàng", example: "The coat is warm.", emoji: "🧥" },
      { id: "256", word: "sweater", pronunciation: "/ˈswet.ər/", meaning: "áo len", example: "This sweater is soft.", emoji: "🧥" },
      { id: "257", word: "hoodie", pronunciation: "/ˈhʊd.i/", meaning: "áo hoodie", example: "He likes wearing hoodies.", emoji: "🧥" },
      { id: "258", word: "vest", pronunciation: "/vest/", meaning: "áo ghi lê", example: "The vest matches his suit.", emoji: "🦺" },
      { id: "259", word: "suit", pronunciation: "/suːt/", meaning: "bộ vest", example: "He wore a suit to work.", emoji: "🕴️" },
      { id: "260", word: "tie", pronunciation: "/taɪ/", meaning: "cà vạt", example: "His tie is red.", emoji: "👔" },
      { id: "261", word: "dress", pronunciation: "/dres/", meaning: "váy đầm", example: "She bought a new dress.", emoji: "👗" },
      { id: "262", word: "skirt", pronunciation: "/skɜːt/", meaning: "váy", example: "The skirt is beautiful.", emoji: "👗" },
      { id: "263", word: "jeans", pronunciation: "/dʒiːnz/", meaning: "quần jean", example: "I wear jeans every day.", emoji: "👖" },
      { id: "264", word: "trousers", pronunciation: "/ˈtraʊ.zəz/", meaning: "quần dài", example: "These trousers fit well.", emoji: "👖" },
      { id: "265", word: "shorts", pronunciation: "/ʃɔːts/", meaning: "quần short", example: "He wore shorts at the beach.", emoji: "🩳" },
      { id: "266", word: "socks", pronunciation: "/sɒks/", meaning: "vớ", example: "My socks are wet.", emoji: "🧦" },
      { id: "267", word: "shoes", pronunciation: "/ʃuːz/", meaning: "giày", example: "These shoes are comfortable.", emoji: "👞" },
      { id: "268", word: "sneakers", pronunciation: "/ˈsniː.kəz/", meaning: "giày thể thao", example: "I bought new sneakers.", emoji: "👟" },
      { id: "269", word: "boots", pronunciation: "/buːts/", meaning: "ủng, giày boot", example: "The boots are waterproof.", emoji: "👢" },
      { id: "270", word: "sandals", pronunciation: "/ˈsæn.dəlz/", meaning: "dép quai", example: "She wore sandals.", emoji: "👡" },
      { id: "271", word: "slippers", pronunciation: "/ˈslɪp.əz/", meaning: "dép đi trong nhà", example: "Put on your slippers.", emoji: "🩴" },
      { id: "272", word: "hat", pronunciation: "/hæt/", meaning: "mũ", example: "He wears a hat.", emoji: "🎩" },
      { id: "273", word: "cap", pronunciation: "/kæp/", meaning: "nón lưỡi trai", example: "The cap protects from the sun.", emoji: "🧢" },
      { id: "274", word: "helmet", pronunciation: "/ˈhel.mɪt/", meaning: "mũ bảo hiểm", example: "Always wear a helmet.", emoji: "⛑️" },
      { id: "275", word: "scarf", pronunciation: "/skɑːf/", meaning: "khăn quàng cổ", example: "The scarf is warm.", emoji: "🧣" },
      { id: "276", word: "gloves", pronunciation: "/ɡlʌvz/", meaning: "găng tay", example: "Wear gloves in winter.", emoji: "🧤" },
      { id: "277", word: "belt", pronunciation: "/belt/", meaning: "thắt lưng", example: "His belt is black.", emoji: "🥋" },
      { id: "278", word: "wallet", pronunciation: "/ˈwɒl.ɪt/", meaning: "ví tiền", example: "My wallet is missing.", emoji: "👛" },
      { id: "279", word: "handbag", pronunciation: "/ˈhænd.bæɡ/", meaning: "túi xách nữ", example: "She bought a handbag.", emoji: "👜" },
      { id: "280", word: "backpack", pronunciation: "/ˈbæk.pæk/", meaning: "ba lô", example: "The backpack is heavy.", emoji: "🎒" },
      { id: "281", word: "suitcase", pronunciation: "/ˈsuːt.keɪs/", meaning: "va li", example: "Pack your suitcase.", emoji: "🧳" },
      { id: "282", word: "umbrella", pronunciation: "/ʌmˈbrel.ə/", meaning: "ô", example: "Take an umbrella.", emoji: "☂️" },
      { id: "283", word: "ring", pronunciation: "/rɪŋ/", meaning: "nhẫn", example: "She wears a ring.", emoji: "💍" },
      { id: "284", word: "necklace", pronunciation: "/ˈnek.ləs/", meaning: "dây chuyền", example: "The necklace is expensive.", emoji: "📿" },
      { id: "285", word: "bracelet", pronunciation: "/ˈbreɪ.slət/", meaning: "vòng tay", example: "He gave her a bracelet.", emoji: "🧿" },
      { id: "286", word: "earring", pronunciation: "/ˈɪə.rɪŋ/", meaning: "bông tai", example: "Her earrings sparkle.", emoji: "👂" },
      { id: "287", word: "watch", pronunciation: "/wɒtʃ/", meaning: "đồng hồ đeo tay", example: "My watch is accurate.", emoji: "⌚" },
      { id: "288", word: "sunglasses", pronunciation: "/ˈsʌnˌɡlɑː.sɪz/", meaning: "kính mát", example: "Wear sunglasses outside.", emoji: "🕶️" },
      { id: "289", word: "glasses", pronunciation: "/ˈɡlɑː.sɪz/", meaning: "kính mắt", example: "I need new glasses.", emoji: "👓" },
      { id: "290", word: "uniform", pronunciation: "/ˈjuː.nɪ.fɔːm/", meaning: "đồng phục", example: "Students wear uniforms.", emoji: "🧑‍🎓" },
      { id: "291", word: "pajamas", pronunciation: "/pəˈdʒɑː.məz/", meaning: "đồ ngủ", example: "He changed into pajamas.", emoji: "🥻" },
      { id: "292", word: "underwear", pronunciation: "/ˈʌn.də.weər/", meaning: "đồ lót", example: "Buy new underwear.", emoji: "🩲" },
      { id: "293", word: "bra", pronunciation: "/brɑː/", meaning: "áo ngực", example: "She bought a new bra.", emoji: "👙" },
      { id: "294", word: "swimsuit", pronunciation: "/ˈswɪm.suːt/", meaning: "đồ bơi", example: "The swimsuit is colorful.", emoji: "🩱" },
      { id: "295", word: "raincoat", pronunciation: "/ˈreɪn.kəʊt/", meaning: "áo mưa", example: "Wear a raincoat today.", emoji: "🧥" },
      { id: "296", word: "zipper", pronunciation: "/ˈzɪp.ər/", meaning: "dây kéo", example: "The zipper is broken.", emoji: "🤐" },
      { id: "297", word: "button", pronunciation: "/ˈbʌt.ən/", meaning: "nút áo", example: "Sew the button back.", emoji: "🔘" },
      { id: "298", word: "pocket", pronunciation: "/ˈpɒk.ɪt/", meaning: "túi áo/quần", example: "My phone is in my pocket.", emoji: "👖" },
      { id: "299", word: "sleeve", pronunciation: "/sliːv/", meaning: "tay áo", example: "Roll up your sleeves.", emoji: "👕" },
      { id: "300", word: "collar", pronunciation: "/ˈkɒl.ər/", meaning: "cổ áo", example: "The collar is dirty.", emoji: "👔" }
    ]
  },
  {
    id: "business",
    name: "Business & Work",
    icon: "💼",
    color: "bg-blue-100 text-blue-600 border-blue-200",
    words: [
      { id: "bz1", word: "meeting", pronunciation: "/ˈmiː.tɪŋ/", meaning: "cuộc họp", example: "We have a meeting at 10 AM.", emoji: "🤝" },
      { id: "bz2", word: "contract", pronunciation: "/ˈkɒn.trækt/", meaning: "hợp đồng", example: "Please sign the contract.", emoji: "📄" },
      { id: "bz3", word: "investment", pronunciation: "/ɪnˈvest.mənt/", meaning: "Sự đầu tư", example: "It is a risky investment.", emoji: "📈" },
      { id: "bz4", word: "profit", pronunciation: "/ˈprɒf.ɪt/", meaning: "lợi nhuận", example: "The company made a huge profit.", emoji: "💰" },
      { id: "bz5", word: "employee", pronunciation: "/ɪmˈplɔɪ.iː/", meaning: "nhân viên", example: "The new employee is smart.", emoji: "🧑‍💻" },
      { id: "bz6", word: "manager", pronunciation: "/ˈmæn.ɪ.dʒər/", meaning: "quản lý", example: "Speak to the manager.", emoji: "👔" },
      { id: "bz7", word: "deadline", pronunciation: "/ˈded.laɪn/", meaning: "Hạn chót", example: "The deadline is tomorrow.", emoji: "⏰" },
      { id: "bz8", word: "presentation", pronunciation: "/ˌprez.ənˈteɪ.ʃən/", meaning: "bài thuyết trình", example: "Her presentation was excellent.", emoji: "📊" },
      { id: "bz9", word: "salary", pronunciation: "/ˈsæl.ər.i/", meaning: "lương", example: "They offer a competitive salary.", emoji: "💵" },
      { id: "bz10", word: "interview", pronunciation: "/ˈɪn.tə.vjuː/", meaning: "phỏng vấn", example: "I have a job interview today.", emoji: "🗣️" }
    ]
  },
  {
    id: "travel",
    name: "Travel & Transport",
    icon: "✈️",
    color: "bg-sky-100 text-sky-600 border-sky-200",
    words: [
      { id: "tr1", word: "airport", pronunciation: "/ˈeə.pɔːt/", meaning: "sân bay", example: "We arrived at the airport early.", emoji: "🛫" },
      { id: "tr2", word: "ticket", pronunciation: "/ˈtɪk.ɪt/", meaning: "vé", example: "Here is your train ticket.", emoji: "🎫" },
      { id: "tr3", word: "luggage", pronunciation: "/ˈlʌɡ.ɪdʒ/", meaning: "hành lý", example: "My luggage is heavy.", emoji: "🧳" },
      { id: "tr4", word: "passport", pronunciation: "/ˈpɑːs.pɔːt/", meaning: "hộ chiếu", example: "Don't forget your passport.", emoji: "🛂" },
      { id: "tr5", word: "flight", pronunciation: "/flaɪt/", meaning: "chuyến bay", example: "The flight is delayed.", emoji: "✈️" },
      { id: "tr6", word: "hotel", pronunciation: "/həʊˈtel/", meaning: "khách sạn", example: "We booked a hotel room.", emoji: "🏨" },
      { id: "tr7", word: "tourism", pronunciation: "/ˈtʊə.rɪ.zəm/", meaning: "du lịch", example: "Tourism is booming here.", emoji: "🌍" },
      { id: "tr8", word: "guide", pronunciation: "/ɡaɪd/", meaning: "hướng dẫn viên", example: "The guide was helpful.", emoji: "🗺️" },
      { id: "tr9", word: "journey", pronunciation: "/ˈdʒɜː.ni/", meaning: "chuyến hành trình", example: "It was a long journey.", emoji: "🚂" },
      { id: "tr10", word: "destination", pronunciation: "/ˌdes.tɪˈneɪ.ʃən/", meaning: "điểm đến", example: "We reached our destination.", emoji: "📍" }
    ]
  }
];
