import { Topic } from "./types";

export const extraTopics5: Topic[] = [
  {
    id: "weather-climate",
    name: "Thời tiết & Khí hậu",
    icon: "⛅",
    color: "bg-sky-100 text-sky-800 border-sky-200",
    words: [
      { id: "wth1", word: "forecast", pronunciation: "/ˈfɔːkɑːst/", meaning: "dự báo thời tiết", example: "Check the weather forecast before going out.", emoji: "📺" },
      { id: "wth2", word: "temperature", pronunciation: "/ˈtemprətʃə/", meaning: "nhiệt độ", example: "The temperature dropped sharply tonight.", emoji: "🌡️" },
      { id: "wth3", word: "humidity", pronunciation: "/hjuːˈmɪdəti/", meaning: "độ ẩm", example: "High humidity makes the air feel heavy.", emoji: "💧" },
      { id: "wth4", word: "drizzle", pronunciation: "/ˈdrɪzl/", meaning: "mưa phùn", example: "A gentle drizzle started in the afternoon.", emoji: "🌧️" },
      { id: "wth5", word: "downpour", pronunciation: "/ˈdaʊnpɔː/", meaning: "mưa rào xối xả", example: "We got caught in a sudden downpour.", emoji: "⛈️" },
      { id: "wth6", word: "thunderstorm", pronunciation: "/ˈθʌndəstɔːm/", meaning: "giông bão", example: "The thunderstorm shook the windows.", emoji: "🌩️" },
      { id: "wth7", word: "lightning", pronunciation: "/ˈlaɪtnɪŋ/", meaning: "tia sét", example: "Lightning flashed across the night sky.", emoji: "⚡" },
      { id: "wth8", word: "blizzard", pronunciation: "/ˈblɪzəd/", meaning: "bão tuyết", example: "The blizzard closed all the roads.", emoji: "❄️" },
      { id: "wth9", word: "hurricane", pronunciation: "/ˈhʌrɪkən/", meaning: "cuồng phong", example: "The hurricane caused severe coastal damage.", emoji: "🌀" },
      { id: "wth10", word: "tornado", pronunciation: "/tɔːˈneɪdəʊ/", meaning: "lốc xoáy", example: "A powerful tornado swept through the valley.", emoji: "🌪️" },
      { id: "wth11", word: "rainbow", pronunciation: "/ˈreɪnbəʊ/", meaning: "cầu vồng", example: "A bright rainbow appeared after the storm.", emoji: "🌈" },
      { id: "wth12", word: "overcast", pronunciation: "/ˌəʊvəˈkɑːst/", meaning: "u ám, nhiều mây", example: "The sky remained overcast all morning.", emoji: "☁️" },
      { id: "wth13", word: "breeze", pronunciation: "/briːz/", meaning: "làn gió nhẹ thoang thoảng", example: "A cool breeze blew from the ocean.", emoji: "🍃" },
      { id: "wth14", word: "heatwave", pronunciation: "/ˈhiːtweɪv/", meaning: "đợt nắng nóng gay gắt", example: "Stay hydrated during the heatwave.", emoji: "🔥" },
      { id: "wth15", word: "drought", pronunciation: "/draʊt/", meaning: "hạn hán", example: "The prolonged drought damaged local crops.", emoji: "🏜️" },
      { id: "wth16", word: "flood", pronunciation: "/flʌd/", meaning: "lũ lụt", example: "Heavy rainfall triggered a flash flood.", emoji: "🌊" },
      { id: "wth17", word: "frost", pronunciation: "/frɒst/", meaning: "sương giá, băng mỏng", example: "Morning frost covered the grass.", emoji: "🧊" },
      { id: "wth18", word: "hail", pronunciation: "/heɪl/", meaning: "mưa đá", example: "Hailstones damaged car windshields.", emoji: "🌨️" },
      { id: "wth19", word: "fog", pronunciation: "/fɒɡ/", meaning: "sương mù dày đặc", example: "Dense fog reduced highway visibility.", emoji: "🌫️" },
      { id: "wth20", word: "mist", pronunciation: "/mɪst/", meaning: "sương mờ quang cảnh", example: "A light mist hung over the mountains.", emoji: "🌁" },
      { id: "wth21", word: "gale", pronunciation: "/ɡeɪl/", meaning: "cơn gió bão mạnh", example: "Gale-force winds knocked down tree branches.", emoji: "💨" },
      { id: "wth22", word: "climate", pronunciation: "/ˈklaɪmət/", meaning: "khí hậu", example: "The Mediterranean climate is warm and pleasant.", emoji: "🌍" },
      { id: "wth23", word: "atmosphere", pronunciation: "/ˈætməsfɪə/", meaning: "khí quyển", example: "Gases trap heat inside the Earth's atmosphere.", emoji: "🌐" },
      { id: "wth24", word: "barometer", pronunciation: "/bəˈrɒmɪtə/", meaning: "phong vũ biểu", example: "The barometer indicated dropping air pressure.", emoji: "⏱️" },
      { id: "wth25", word: "monsoon", pronunciation: "/mɒnˈsuːn/", meaning: "gió mùa", example: "The summer monsoon brings needed rain.", emoji: "☔" },
      { id: "wth26", word: "typhoon", pronunciation: "/taɪˈfuːn/", meaning: "bão nhiệt đới", example: "Residents evacuated ahead of the typhoon.", emoji: "🌀" },
      { id: "wth27", word: "sunshine", pronunciation: "/ˈsʌnʃaɪn/", meaning: "ánh nắng mặt trời", example: "Children played outside in the warm sunshine.", emoji: "☀️" },
      { id: "wth28", word: "Celsius", pronunciation: "/ˈselsiəs/", meaning: "độ C", example: "Water freezes at zero degrees Celsius.", emoji: "🌡️" },
      { id: "wth29", word: "Fahrenheit", pronunciation: "/ˈfærənhaɪt/", meaning: "độ F", example: "Seventy degrees Fahrenheit is quite comfortable.", emoji: "🌡️" },
      { id: "wth30", word: "meteorology", pronunciation: "/ˌmiːtiəˈrɒlədʒi/", meaning: "khí tượng học", example: "She studied meteorology to predict weather events.", emoji: "📡" },
      { id: "wth31", word: "cyclone", pronunciation: "/ˈsaɪkləʊn/", meaning: "xoáy thuận nhiệt đới", example: "The cyclone formed over warm ocean currents.", emoji: "🌀" },
      { id: "wth32", word: "precipitation", pronunciation: "/prɪˌsɪpɪˈteɪʃn/", meaning: "lượng mưa, giáng thủy", example: "Annual precipitation is high in rainforests.", emoji: "🌧️" },
      { id: "wth33", word: "chilly", pronunciation: "/ˈtʃɪli/", meaning: "se se lạnh", example: "Put on a sweater; it is chilly outside.", emoji: "🧣" },
      { id: "wth34", word: "muggy", pronunciation: "/ˈmʌɡi/", meaning: "nồm ẩm, oi bức", example: "The muggy weather made sleeping difficult.", emoji: "😓" },
      { id: "wth35", word: "sweltering", pronunciation: "/ˈsweltərɪŋ/", meaning: "nóng bức ngột ngạt", example: "We stayed indoors on a sweltering afternoon.", emoji: "🥵" },
      { id: "wth36", word: "thaw", pronunciation: "/θɔː/", meaning: "sự tan băng tuyết", example: "Snow began to thaw as spring arrived.", emoji: "💧" },
      { id: "wth37", word: "avalanche", pronunciation: "/ˈævəlɑːnʃ/", meaning: "tuyết lở", example: "Skiers were warned of avalanche danger on the slope.", emoji: "🏔️" },
      { id: "wth38", word: "squall", pronunciation: "/skwɔːl/", meaning: "cơn gió giật kèm mưa", example: "A sudden squall rocked the fishing boat.", emoji: "🌬️" },
      { id: "wth39", word: "smog", pronunciation: "/smɒɡ/", meaning: "khói sương mù ô nhiễm", example: "Heavy smog covered the metropolitan skyline.", emoji: "🏙️" },
      { id: "wth40", word: "dew", pronunciation: "/djuː/", meaning: "giọt sương mai", example: "Morning dew sparkled on the flower petals.", emoji: "💧" },
      { id: "wth41", word: "gust", pronunciation: "/ɡʌst/", meaning: "cơn gió giật mạnh", example: "A sudden gust blew away my umbrella.", emoji: "💨" },
      { id: "wth42", word: "snowflake", pronunciation: "/ˈsnəʊfleɪk/", meaning: "bông tuyết", example: "Each snowflake has a unique geometric pattern.", emoji: "❄️" },
      { id: "wth43", word: "parched", pronunciation: "/pɑːtʃt/", meaning: "khô nẻ, cằn cỗi", example: "The parched earth cracked beneath the sun.", emoji: "🏜️" },
      { id: "wth44", word: "tropical", pronunciation: "/ˈtrɒpɪkl/", meaning: "thuộc nhiệt đới", example: "Tropical plants require abundant water and light.", emoji: "🌴" },
      { id: "wth45", word: "temperate", pronunciation: "/ˈtempərət/", meaning: "ôn đới, ôn hòa", example: "Temperate climates have distinct four seasons.", emoji: "🍂" },
      { id: "wth46", word: "polar", pronunciation: "/ˈpəʊlə/", meaning: "thuộc về hai cực", example: "Polar regions remain frozen throughout the year.", emoji: "🐻‍❄️" },
      { id: "wth47", word: "mirage", pronunciation: "/ˈmɪrɑːʒ/", meaning: "ảo ảnh quang học", example: "Travelers in the desert saw a watery mirage.", emoji: "✨" },
      { id: "wth48", word: "sleet", pronunciation: "/sliːt/", meaning: "mưa tuyết lẫn hạt đá", example: "Driving was dangerous due to freezing sleet.", emoji: "🌨️" },
      { id: "wth49", word: "condensation", pronunciation: "/ˌkɒndenˈseɪʃn/", meaning: "sự ngưng tụ hơi nước", example: "Condensation formed on the cold glass surface.", emoji: "🪟" },
      { id: "wth50", word: "evaporate", pronunciation: "/ɪˈvæpəreɪt/", meaning: "bay hơi, bốc hơi", example: "Puddles of water evaporate under hot sunshine.", emoji: "♨️" }
    ]
  },
  {
    id: "emotions-feelings",
    name: "Cảm xúc & Tính cách",
    icon: "😊",
    color: "bg-pink-100 text-pink-800 border-pink-200",
    words: [
      { id: "emo1", word: "cheerful", pronunciation: "/ˈtʃɪəfl/", meaning: "vui tươi, phấn khởi", example: "She always greets people with a cheerful smile.", emoji: "😄" },
      { id: "emo2", word: "anxious", pronunciation: "/ˈæŋkʃəs/", meaning: "lo lắng, bồn chồn", example: "He felt anxious before the interview began.", emoji: "😰" },
      { id: "emo3", word: "furious", pronunciation: "/ˈfjʊəriəs/", meaning: "cực kỳ tức giận", example: "She was furious when her flight was cancelled.", emoji: "😡" },
      { id: "emo4", word: "optimistic", pronunciation: "/ˌɒptɪˈmɪstɪk/", meaning: "lạc quan yêu đời", example: "He maintains an optimistic attitude towards challenges.", emoji: "🌟" },
      { id: "emo5", word: "pessimistic", pronunciation: "/ˌpesɪˈmɪstɪk/", meaning: "bi quan", example: "Try not to be pessimistic about the new project.", emoji: "🌧️" },
      { id: "emo6", word: "compassionate", pronunciation: "/kəmˈpæʃənət/", meaning: "giàu lòng trắc ẩn", example: "The compassionate volunteer comforted the victims.", emoji: "💖" },
      { id: "emo7", word: "stubborn", pronunciation: "/ˈstʌbən/", meaning: "bướng bỉnh, cứng đầu", example: "He was too stubborn to admit he made an error.", emoji: "😤" },
      { id: "emo8", word: "empathetic", pronunciation: "/ˌempəˈθetɪk/", meaning: "biết thấu cảm, đồng cảm", example: "Good counselors are empathetic toward patient concerns.", emoji: "🫂" },
      { id: "emo9", word: "ambitious", pronunciation: "/æmˈbɪʃəs/", meaning: "đầy tham vọng, chí lớn", example: "She has ambitious career goals for the coming decade.", emoji: "🎯" },
      { id: "emo10", word: "grateful", pronunciation: "/ˈɡreɪtfl/", meaning: "biết ơn sâu sắc", example: "I am deeply grateful for your continuous help.", emoji: "🙏" },
      { id: "emo11", word: "envious", pronunciation: "/ˈenviəs/", meaning: "ghen tị, đố kỵ", example: "He felt envious of his friend's brand new car.", emoji: "😒" },
      { id: "emo12", word: "melancholic", pronunciation: "/ˌmelənˈkɒlɪk/", meaning: "u sầu, buồn man mác", example: "The rainy evening gave him a melancholic mood.", emoji: "🥀" },
      { id: "emo13", word: "irritable", pronunciation: "/ˈɪrɪtəbl/", meaning: "dễ cáu bẳn, gắt gỏng", example: "Working without rest makes anyone irritable.", emoji: "😣" },
      { id: "emo14", word: "ecstatic", pronunciation: "/ɪkˈstætɪk/", meaning: "vui sướng cực độ", example: "Fans were ecstatic when their team scored in overtime.", emoji: "🥳" },
      { id: "emo15", word: "resilient", pronunciation: "/rɪˈzɪliənt/", meaning: "kiên cường, bất khuất", example: "She showed a resilient spirit after the setback.", emoji: "🪴" },
      { id: "emo16", word: "introverted", pronunciation: "/ˈɪntrəvɜːtɪd/", meaning: "hướng nội", example: "Introverted learners often thrive in quiet environments.", emoji: "🤫" },
      { id: "emo17", word: "extroverted", pronunciation: "/ˈekstrəvɜːtɪd/", meaning: "hướng ngoại", example: "His extroverted nature helps him connect with audiences.", emoji: "🗣️" },
      { id: "emo18", word: "humble", pronunciation: "/ˈhʌmbl/", meaning: "khiêm tốn, nhún nhường", example: "Despite his fame, he remained remarkably humble.", emoji: "🙇" },
      { id: "emo19", word: "arrogant", pronunciation: "/ˈærəɡənt/", meaning: "kiêu ngạo, hống hách", example: "Nobody liked his arrogant remarks at the meeting.", emoji: "👑" },
      { id: "emo20", word: "courageous", pronunciation: "/kəˈreɪdʒəs/", meaning: "dũng cảm, quả cảm", example: "It was a courageous decision to speak out the truth.", emoji: "🦁" },
      { id: "emo21", word: "conscientious", pronunciation: "/ˌkɒnʃiˈenʃəs/", meaning: "tận tụy, có lương tâm", example: "A conscientious student never submits incomplete work.", emoji: "📋" },
      { id: "emo22", word: "thoughtful", pronunciation: "/ˈθɔːtfl/", meaning: "chu đáo, ân cần", example: "Sending flowers was a very thoughtful gesture.", emoji: "🎁" },
      { id: "emo23", word: "enthusiastic", pronunciation: "/ɪnˌθjuːziˈæstɪk/", meaning: "hào hứng, nhiệt huyết", example: "The children were enthusiastic about the zoo trip.", emoji: "🔥" },
      { id: "emo24", word: "bewildered", pronunciation: "/bɪˈwɪldəd/", meaning: "hoang mang, bỡ ngỡ", example: "The tourist stood bewildered at the crossroads.", emoji: "😵‍💫" },
      { id: "emo25", word: "apprehensive", pronunciation: "/ˌæprɪˈhensɪv/", meaning: "e sợ, hồi hộp lo lắng", example: "She was apprehensive before entering the surgery room.", emoji: "🫣" },
      { id: "emo26", word: "nostalgic", pronunciation: "/nɒˈstældʒɪk/", meaning: "hoài niệm quá khứ", example: "Listening to 90s songs made him feel nostalgic.", emoji: "📻" },
      { id: "emo27", word: "sincere", pronunciation: "/sɪnˈsɪə/", meaning: "chân thành, thật tâm", example: "He gave a sincere apology for his thoughtless remark.", emoji: "🤝" },
      { id: "emo28", word: "indifferent", pronunciation: "/ɪnˈdɪfrənt/", meaning: "thờ ơ, vô cảm", example: "He remained indifferent to their emotional plea.", emoji: "😐" },
      { id: "emo29", word: "courteous", pronunciation: "/ˈkɜːtiəs/", meaning: "lịch thiệp, nhã nhặn", example: "The front desk staff were courteous and helpful.", emoji: "🛎️" },
      { id: "emo30", word: "spontaneous", pronunciation: "/spɒnˈteɪniəs/", meaning: "tự phát, ngẫu hứng", example: "They booked a spontaneous weekend getaway.", emoji: "🎈" },
      { id: "emo31", word: "impatient", pronunciation: "/ɪmˈpeɪʃnt/", meaning: "nóng ruột, thiếu kiên nhẫn", example: "The driver grew impatient in the traffic jam.", emoji: "⏳" },
      { id: "emo32", word: "generous", pronunciation: "/ˈdʒenərəs/", meaning: "hào hiệp, rộng rãi", example: "Her generous donation helped build the clinic.", emoji: "🤲" },
      { id: "emo33", word: "diligent", pronunciation: "/ˈdɪlɪdʒənt/", meaning: "cần cù, siêng năng", example: "Through diligent study, he passed with flying colors.", emoji: "📖" },
      { id: "emo34", word: "timid", pronunciation: "/ˈtɪmɪd/", meaning: "nhút nhát, rụt rè", example: "The timid child clung to her mother's coat.", emoji: "🐕" },
      { id: "emo35", word: "jealous", pronunciation: "/ˈdʒeləs/", meaning: "ghen tuông mù quáng", example: "Jealous feelings ruined their peaceful friendship.", emoji: "💔" },
      { id: "emo36", word: "serene", pronunciation: "/səˈriːn/", meaning: "thanh bình, tĩnh tại", example: "She smiled with a serene expression on her face.", emoji: "🧘" },
      { id: "emo37", word: "astonished", pronunciation: "/əˈstɒnɪʃt/", meaning: "kinh ngạc, sửng sốt", example: "The audience was astonished by the magic illusion.", emoji: "😲" },
      { id: "emo38", word: "trustworthy", pronunciation: "/ˈtrʌstˌwɜːði/", meaning: "đáng tin cậy", example: "He has been a trustworthy accountant for thirty years.", emoji: "🛡️" },
      { id: "emo39", word: "curious", pronunciation: "/ˈkjʊəriəs/", meaning: "tò mò, hiếu kỳ", example: "Curious cats explored every corner of the house.", emoji: "🧐" },
      { id: "emo40", word: "affectionate", pronunciation: "/əˈfekʃənət/", meaning: "âu yếm, thiết tha", example: "The affectionate dog greeted its owner at the door.", emoji: "🫂" },
      { id: "emo41", word: "reckless", pronunciation: "/ˈrekləs/", meaning: "liều mạng, thiếu suy nghĩ", example: "Speeding in wet weather is extremely reckless.", emoji: "⚠️" },
      { id: "emo42", word: "considerate", pronunciation: "/kənˈsɪdərət/", meaning: "chu đáo, quan tâm người khác", example: "It was considerate of him to save a seat for me.", emoji: "🤫" },
      { id: "emo43", word: "grumpy", pronunciation: "/ˈɡrʌmpi/", meaning: "càu nhàu, khó tính", example: "He wakes up grumpy if he does not drink coffee.", emoji: "☕" },
      { id: "emo44", word: "charismatic", pronunciation: "/ˌkærɪzˈmætɪk/", meaning: "có sức lôi cuốn đặc biệt", example: "The charismatic leader inspired millions of people.", emoji: "🌟" },
      { id: "emo45", word: "vindictive", pronunciation: "/vɪnˈdɪktɪv/", meaning: "hiếu thù, muốn trả đũa", example: "Refusing to cooperate was a vindictive act.", emoji: "🐍" },
      { id: "emo46", word: "witty", pronunciation: "/ˈwɪti/", meaning: "dí dỏm, hóm hỉnh", example: "His witty commentary kept everyone entertained.", emoji: "💡" },
      { id: "emo47", word: "perplexed", pronunciation: "/pəˈplekst/", meaning: "bối rối, khó hiểu", example: "Detectives were perplexed by the missing clues.", emoji: "🤔" },
      { id: "emo48", word: "skeptical", pronunciation: "/ˈskeptɪkl/", meaning: "hoài nghi, nghi ngờ", example: "Experts were skeptical about the untested claims.", emoji: "🤨" },
      { id: "emo49", word: "overjoyed", pronunciation: "/ˌəʊvəˈdʒɔɪd/", meaning: "vui mừng khôn xiết", example: "She was overjoyed to receive the scholarship letter.", emoji: "🥳" },
      { id: "emo50", word: "passionate", pronunciation: "/ˈpæʃənət/", meaning: "đam mê, tâm huyết", example: "He is passionate about marine wildlife conservation.", emoji: "❤️‍🔥" }
    ]
  },
  {
    id: "sports-fitness",
    name: "Thể thao & Thể hình",
    icon: "⚽",
    color: "bg-emerald-100 text-emerald-800 border-emerald-200",
    words: [
      { id: "spo1", word: "tournament", pronunciation: "/ˈtʊənəmənt/", meaning: "giải đấu thể thao", example: "Sixteen top clubs competed in the summer tournament.", emoji: "🏆" },
      { id: "spo2", word: "referee", pronunciation: "/ˌrefəˈriː/", meaning: "trọng tài điều khiển trận", example: "The referee whistled a foul near the penalty area.", emoji: "🧑‍⚖️" },
      { id: "spo3", word: "athlete", pronunciation: "/ˈæθliːt/", meaning: "vận động viên", example: "The Olympic athlete trained six hours each day.", emoji: "🏃" },
      { id: "spo4", word: "marathon", pronunciation: "/ˈmærəθən/", meaning: "chạy ma-ra-tông đường trường", example: "Over ten thousand runners participated in the marathon.", emoji: "🏅" },
      { id: "spo5", word: "championship", pronunciation: "/ˈtʃæmpiənʃɪp/", meaning: "chức vô địch", example: "They won the national basketball championship.", emoji: "🥇" },
      { id: "spo6", word: "gymnastics", pronunciation: "/dʒɪmˈnæstɪks/", meaning: "thể dục dụng cụ", example: "Gymnastics develops core strength and balance.", emoji: "🤸" },
      { id: "spo7", word: "archery", pronunciation: "/ˈɑːtʃəri/", meaning: "môn bắn cung", example: "Archery requires absolute stillness and sharp aim.", emoji: "🏹" },
      { id: "spo8", word: "skateboarding", pronunciation: "/ˈskeɪtbɔːdɪŋ/", meaning: "môn trượt ván", example: "Skateboarding is popular among urban teenagers.", emoji: "🛹" },
      { id: "spo9", word: "badminton", pronunciation: "/ˈbædmɪntən/", meaning: "môn cầu lông", example: "We rented a court to play doubles badminton.", emoji: "🏸" },
      { id: "spo10", word: "tennis", pronunciation: "/ˈtenɪs/", meaning: "quần vợt", example: "She hit a brilliant forehand winner in tennis.", emoji: "🎾" },
      { id: "spo11", word: "basketball", pronunciation: "/ˈbɑːskɪtbɔːl/", meaning: "bóng rổ", example: "He scored thirty points in last night's basketball match.", emoji: "🏀" },
      { id: "spo12", word: "soccer", pronunciation: "/ˈsɒkə/", meaning: "bóng đá", example: "Millions of fans watched the soccer World Cup final.", emoji: "⚽" },
      { id: "spo13", word: "volleyball", pronunciation: "/ˈvɒlibɔːl/", meaning: "bóng chuyền", example: "The player jumped high to block the volleyball.", emoji: "🏐" },
      { id: "spo14", word: "stadium", pronunciation: "/ˈsteɪdiəm/", meaning: "sân vận động", example: "Cheering spectators packed the eighty-thousand-seat stadium.", emoji: "🏟️" },
      { id: "spo15", word: "defense", pronunciation: "/dɪˈfens/", meaning: "hàng phòng ngự", example: "A resilient defense prevented any further goals.", emoji: "🛡️" },
      { id: "spo16", word: "offense", pronunciation: "/əˈfens/", meaning: "hàng tấn công", example: "Their aggressive offense put immense pressure on the rival.", emoji: "⚔️" },
      { id: "spo17", word: "goalkeeper", pronunciation: "/ˈɡəʊlˌkiːpə/", meaning: "thủ môn", example: "The goalkeeper made an acrobatic flying fingertip save.", emoji: "🧤" },
      { id: "spo18", word: "trophy", pronunciation: "/ˈtrəʊfi/", meaning: "cúp quán quân", example: "The team proudly hoisted the silver trophy.", emoji: "🏆" },
      { id: "spo19", word: "coach", pronunciation: "/kəʊtʃ/", meaning: "huấn luyện viên", example: "The head coach formulated an effective match strategy.", emoji: "📋" },
      { id: "spo20", word: "penalty", pronunciation: "/ˈpenəlti/", meaning: "quả phạt đền", example: "He calmly converted the penalty kick in the 90th minute.", emoji: "🎯" },
      { id: "spo21", word: "cycling", pronunciation: "/ˈsaɪklɪŋ/", meaning: "môn đua xe đạp", example: "Cycling through steep mountain passes builds leg stamina.", emoji: "🚴" },
      { id: "spo22", word: "swimming", pronunciation: "/ˈswɪmɪŋ/", meaning: "bơi lội", example: "Swimming freestyle engages nearly every muscle group.", emoji: "🏊" },
      { id: "spo23", word: "surfing", pronunciation: "/ˈsɜːfɪŋ/", meaning: "lướt sóng", example: "Coastal beaches attract surfing enthusiasts all summer.", emoji: "🏄" },
      { id: "spo24", word: "kayaking", pronunciation: "/ˈkaɪækɪŋ/", meaning: "chèo thuyền kayak", example: "We spent the afternoon kayaking across the calm bay.", emoji: "🛶" },
      { id: "spo25", word: "mountaineering", pronunciation: "/ˌmaʊntɪˈnɪərɪŋ/", meaning: "leo núi mạo hiểm", example: "Mountaineering demands ropes, crampons, and endurance.", emoji: "🧗" },
      { id: "spo26", word: "fencing", pronunciation: "/ˈfensɪŋ/", meaning: "môn đấu kiếm", example: "Fencing combines agile footwork with rapid sword thrusts.", emoji: "🤺" },
      { id: "spo27", word: "wrestling", pronunciation: "/ˈreslɪŋ/", meaning: "môn đấu vật", example: "Both competitors grappled fiercely in the wrestling ring.", emoji: "🤼" },
      { id: "spo28", word: "boxing", pronunciation: "/ˈbɒksɪŋ/", meaning: "môn quyền anh", example: "The boxing champion defended his title for the third time.", emoji: "🥊" },
      { id: "spo29", word: "martial arts", pronunciation: "/ˌmɑːʃl ˈɑːts/", meaning: "võ thuật", example: "Practicing martial arts fosters discipline and self-defense.", emoji: "🥋" },
      { id: "spo30", word: "barbell", pronunciation: "/ˈbɑːbel/", meaning: "thanh tạ đòn", example: "He lifted the heavy barbell during his deadlift routine.", emoji: "🏋️" },
      { id: "spo31", word: "dumbbell", pronunciation: "/ˈdʌmbel/", meaning: "tạ tay", example: "Grab a pair of dumbbells to work on shoulder presses.", emoji: "🏋️" },
      { id: "spo32", word: "treadmill", pronunciation: "/ˈtredmɪl/", meaning: "máy chạy bộ", example: "She warmed up on the gym treadmill for twenty minutes.", emoji: "🏃" },
      { id: "spo33", word: "endurance", pronunciation: "/ɪnˈdjʊərəns/", meaning: "sức bền thể lực", example: "Triathlon athletes undergo grueling endurance training.", emoji: "⏱️" },
      { id: "spo34", word: "warmup", pronunciation: "/ˈwɔːmʌp/", meaning: "bài khởi động làm nóng người", example: "A dynamic warmup prevents muscle strains before sprints.", emoji: "🤸" },
      { id: "spo35", word: "stretching", pronunciation: "/ˈstretʃɪŋ/", meaning: "bài tập giãn cơ", example: "Post-workout stretching promotes flexibility and recovery.", emoji: "🧘" },
      { id: "spo36", word: "fitness", pronunciation: "/ˈfɪtnəs/", meaning: "thể lực, sự cân đối", example: "Eating well and exercising improves overall cardiovascular fitness.", emoji: "💪" },
      { id: "spo37", word: "workout", pronunciation: "/ˈwɜːkaʊt/", meaning: "buổi tập luyện", example: "An intensive full-body workout burns hundreds of calories.", emoji: "💦" },
      { id: "spo38", word: "stamina", pronunciation: "/ˈstæmɪnə/", meaning: "sức dẻo dai, thể lực bền", example: "Interval training builds up tremendous stamina over time.", emoji: "🫁" },
      { id: "spo39", word: "rival", pronunciation: "/ˈraɪvl/", meaning: "kình địch, đối thủ lớn", example: "The two tennis rivals have faced each other fifty times.", emoji: "🥊" },
      { id: "spo40", word: "amateur", pronunciation: "/ˈæmətə/", meaning: "nghiệp dư", example: "The tournament welcomes both amateur and seasoned players.", emoji: "🎽" },
      { id: "spo41", word: "professional", pronunciation: "/prəˈfeʃənl/", meaning: "chuyên nghiệp", example: "She became a professional golfer at age eighteen.", emoji: "💼" },
      { id: "spo42", word: "scoreboard", pronunciation: "/ˈskɔːbɔːd/", meaning: "bảng tỷ số", example: "Fans watched the digital scoreboard count down the seconds.", emoji: "🔢" },
      { id: "spo43", word: "spectator", pronunciation: "/spekˈteɪtə/", meaning: "khán giả cổ vũ", example: "Excited spectators waved flags and sang club anthems.", emoji: "👥" },
      { id: "spo44", word: "playoff", pronunciation: "/ˈpleɪɒf/", meaning: "loạt trận loại trực tiếp", example: "Both teams fought fiercely to reach the postseason playoffs.", emoji: "🎟️" },
      { id: "spo45", word: "golf", pronunciation: "/ɡɒlf/", meaning: "môn đánh gôn", example: "He spent Sunday morning playing eighteen holes of golf.", emoji: "⛳" },
      { id: "spo46", word: "snowboard", pronunciation: "/ˈsnəʊbɔːd/", meaning: "ván trượt tuyết", example: "He waxed his snowboard before hitting the alpine slopes.", emoji: "🏂" },
      { id: "spo47", word: "sprint", pronunciation: "/sprɪnt/", meaning: "chạy nước rút tốc lực", example: "She gave a final sprint and crossed the finish line first.", emoji: "⚡" },
      { id: "spo48", word: "substitute", pronunciation: "/ˈsʌbstɪtjuːt/", meaning: "cầu thủ dự bị", example: "The substitute entered in the second half and scored immediately.", emoji: "🔄" },
      { id: "spo49", word: "dribble", pronunciation: "/ˈdrɪbl/", meaning: "rê dắt bóng qua người", example: "The midfielder dribbled skillfully past three opposing defenders.", emoji: "⚽" },
      { id: "spo50", word: "tackle", pronunciation: "/ˈtækl/", meaning: "cú tranh chấp / xoạc bóng", example: "A clean sliding tackle dispossessed the attacking forward.", emoji: "🦶" }
    ]
  },
  {
    id: "music-entertainment",
    name: "Âm nhạc & Giải trí",
    icon: "🎵",
    color: "bg-violet-100 text-violet-800 border-violet-200",
    words: [
      { id: "mus1", word: "melody", pronunciation: "/ˈmelədi/", meaning: "giai điệu", example: "She played a hauntingly beautiful piano melody.", emoji: "🎶" },
      { id: "mus2", word: "rhythm", pronunciation: "/ˈrɪðəm/", meaning: "nhịp điệu bài hát", example: "The energetic drum rhythm got everyone dancing.", emoji: "🥁" },
      { id: "mus3", word: "symphony", pronunciation: "/ˈsɪmfəni/", meaning: "bản giao hưởng", example: "The orchestra performed Beethoven's monumental symphony.", emoji: "🎼" },
      { id: "mus4", word: "acoustic", pronunciation: "/əˈkuːstɪk/", meaning: "mộc, âm hưởng tự nhiên", example: "He performed an intimate acoustic version of his hit song.", emoji: "🎸" },
      { id: "mus5", word: "concert", pronunciation: "/ˈkɒnsət/", meaning: "buổi hòa nhạc", example: "Thousands of music fans bought tickets for the outdoor concert.", emoji: "🎤" },
      { id: "mus6", word: "orchestra", pronunciation: "/ˈɔːkɪstrə/", meaning: "dàn nhạc giao hưởng", example: "The conductor raised his baton before the orchestra.", emoji: "🎻" },
      { id: "mus7", word: "composer", pronunciation: "/kəmˈpəʊzə/", meaning: "nhà soạn nhạc", example: "The classical composer wrote numerous piano concertos.", emoji: "🧑‍🎨" },
      { id: "mus8", word: "vocalist", pronunciation: "/ˈvəʊkəlɪst/", meaning: "ca sĩ lĩnh xướng", example: "The lead vocalist gave an extraordinarily emotional performance.", emoji: "🎙️" },
      { id: "mus9", word: "lyrics", pronunciation: "/ˈlɪrɪks/", meaning: "lời bài hát", example: "The meaningful lyrics touched the hearts of the listeners.", emoji: "📜" },
      { id: "mus10", word: "album", pronunciation: "/ˈælbəm/", meaning: "album âm nhạc", example: "Their debut studio album topped global music charts.", emoji: "💿" },
      { id: "mus11", word: "tempo", pronunciation: "/ˈtempəʊ/", meaning: "tốc độ nhịp phách", example: "The song shifts from a slow intro into a rapid tempo.", emoji: "⏱️" },
      { id: "mus12", word: "rehearsal", pronunciation: "/rɪˈhɜːsl/", meaning: "buổi tổng duyệt, tập dượt", example: "Actors gathered on stage for their final dress rehearsal.", emoji: "🎭" },
      { id: "mus13", word: "festival", pronunciation: "/ˈfestɪvl/", meaning: "lễ hội âm nhạc biểu diễn", example: "Camping at the music festival was an unforgettable memory.", emoji: "🎪" },
      { id: "mus14", word: "cinema", pronunciation: "/ˈsɪnəmə/", meaning: "rạp chiếu phim", example: "We gathered at the cinema to watch the midnight premiere.", emoji: "🎬" },
      { id: "mus15", word: "theatre", pronunciation: "/ˈθɪətə/", meaning: "nhà hát kịch nghệ", example: "London's West End is famous for world-class theatre productions.", emoji: "🏛️" },
      { id: "mus16", word: "stage", pronunciation: "/steɪdʒ/", meaning: "sân khấu biểu diễn", example: "The rock band leaped onto the stage amid flashing fireworks.", emoji: "🌟" },
      { id: "mus17", word: "audition", pronunciation: "/ɔːˈdɪʃn/", meaning: "buổi thử vai, thử giọng", example: "Hundreds lined up outside to take part in the audition.", emoji: "🎟️" },
      { id: "mus18", word: "performance", pronunciation: "/pəˈfɔːməns/", meaning: "màn trình diễn nghệ thuật", example: "Her ballet performance earned a standing ovation.", emoji: "💃" },
      { id: "mus19", word: "genre", pronunciation: "/ˈʒɑ̃ːrə/", meaning: "thể loại nhạc / nghệ thuật", example: "Electronic dance music is a hugely popular youth genre.", emoji: "🎷" },
      { id: "mus20", word: "harmony", pronunciation: "/ˈhɑːməni/", meaning: "hòa âm, bè phối", example: "The vocal quartet blended together in heavenly harmony.", emoji: "🎵" },
      { id: "mus21", word: "chord", pronunciation: "/kɔːd/", meaning: "hợp âm đàn", example: "He strummed a minor chord on his wooden guitar.", emoji: "🎸" },
      { id: "mus22", word: "soundtrack", pronunciation: "/ˈsaʊndtræk/", meaning: "nhạc nền phim ảnh", example: "The orchestral movie soundtrack heightened dramatic tension.", emoji: "🎧" },
      { id: "mus23", word: "applause", pronunciation: "/əˈplɔːz/", meaning: "tràng vỗ tay tán thưởng", example: "Thunderous applause erupted as the final curtain fell.", emoji: "👏" },
      { id: "mus24", word: "broadcast", pronunciation: "/ˈbrɔːdkɑːst/", meaning: "chương trình phát sóng", example: "The live broadcast reached fifty million viewers worldwide.", emoji: "📡" },
      { id: "mus25", word: "premiere", pronunciation: "/ˈpremieə/", meaning: "buổi công chiếu đầu tiên", example: "Celebrities dressed elegantly for the world premiere.", emoji: "🎞️" },
      { id: "mus26", word: "comedian", pronunciation: "/kəˈmiːdiən/", meaning: "nghệ sĩ diễn hài", example: "The witty standup comedian had the whole club laughing.", emoji: "🃏" },
      { id: "mus27", word: "blockbuster", pronunciation: "/ˈblɒkˌbʌstə/", meaning: "phim bom tấn ăn khách", example: "The sci-fi action film became a global summer blockbuster.", emoji: "🍿" },
      { id: "mus28", word: "spotlight", pronunciation: "/ˈspɒtlaɪt/", meaning: "đèn chiếu điểm sân khấu", example: "The soloist stepped directly under the bright center spotlight.", emoji: "💡" },
      { id: "mus29", word: "improvisation", pronunciation: "/ˌɪmprəvaɪˈzeɪʃn/", meaning: "sự ngẫu hứng tức thì", example: "Jazz trumpeters often showcase spontaneous improvisation.", emoji: "🎺" },
      { id: "mus30", word: "instrument", pronunciation: "/ˈɪnstrəmənt/", meaning: "nhạc cụ biểu diễn", example: "Learning a musical instrument enhances cognitive skills.", emoji: "🎹" },
      { id: "mus31", word: "playlist", pronunciation: "/ˈpleɪlɪst/", meaning: "danh sách phát bài hát", example: "I saved a relaxing acoustic playlist for my evening commute.", emoji: "📱" },
      { id: "mus32", word: "headphone", pronunciation: "/ˈhedfəʊn/", meaning: "tai nghe âm thanh", example: "Put on studio headphones to hear every subtle instrument layer.", emoji: "🎧" },
      { id: "mus33", word: "saxophone", pronunciation: "/ˈsæksəfəʊn/", meaning: "kèn xắc-xô-phôn", example: "A smooth saxophone solo floated through the candlelit jazz lounge.", emoji: "🎷" },
      { id: "mus34", word: "trumpet", pronunciation: "/ˈtrʌmpɪt/", meaning: "kèn trôm-pét", example: "The brass trumpet player sounded a clear high note.", emoji: "🎺" },
      { id: "mus35", word: "flute", pronunciation: "/fluːt/", meaning: "ống sáo trúc / sáo bạc", example: "The gentle sound of the silver flute calmed the room.", emoji: "🪈" },
      { id: "mus36", word: "drum", pronunciation: "/drʌm/", meaning: "trống định âm", example: "He kept the beat steady with crisp drum strokes.", emoji: "🥁" },
      { id: "mus37", word: "violin", pronunciation: "/ˌvaɪəˈlɪn/", meaning: "đàn vĩ cầm", example: "She practiced intricate violin scales each morning.", emoji: "🎻" },
      { id: "mus38", word: "bass", pronunciation: "/beɪs/", meaning: "âm bass, bè trầm", example: "The bass line gave the funk track its irresistible groove.", emoji: "🎸" },
      { id: "mus39", word: "duet", pronunciation: "/djuːˈet/", meaning: "bài song ca hòa giọng", example: "The two vocalists sang an enchanting romantic duet.", emoji: "👫" },
      { id: "mus40", word: "encore", pronunciation: "/ˈɒŋkɔː/", meaning: "màn hát lại theo yêu cầu khán giả", example: "The crowd chanted loudly demanding an encore.", emoji: "📣" },
      { id: "mus41", word: "tuning", pronunciation: "/ˈtjuːnɪŋ/", meaning: "việc so dây chỉnh âm", example: "Accurate instrument tuning is essential before any concert.", emoji: "🔧" },
      { id: "mus42", word: "microphone", pronunciation: "/ˈmaɪkrəfəʊn/", meaning: "mi-crô thu âm", example: "The singer adjusted the microphone stand on stage.", emoji: "🎙️" },
      { id: "mus43", word: "documentary", pronunciation: "/ˌdɒkjuˈmentri/", meaning: "phim tài liệu thực tế", example: "We watched an eye-opening environmental documentary.", emoji: "📽️" },
      { id: "mus44", word: "animation", pronunciation: "/ˌænɪˈmeɪʃn/", meaning: "phim hoạt họa hoạt hình", example: "The studio created stunning hand-drawn 2D animation.", emoji: "🎨" },
      { id: "mus45", word: "celebrity", pronunciation: "/səˈlebrəti/", meaning: "người nổi tiếng", example: "Fans screamed when the movie celebrity arrived.", emoji: "⭐" },
      { id: "mus46", word: "sequel", pronunciation: "/ˈsiːkwəl/", meaning: "phần tiếp theo của phim", example: "The sequel proved even more thrilling than the original.", emoji: "🎬" },
      { id: "mus47", word: "subtitle", pronunciation: "/ˈsʌbˌtaɪtl/", meaning: "phụ đề phim", example: "Reading English subtitles helps expand conversational vocabulary.", emoji: "💬" },
      { id: "mus48", word: "episode", pronunciation: "/ˈepɪsəʊd/", meaning: "tập phim truyền hình", example: "They stayed up late to watch the next episode of the drama.", emoji: "📺" },
      { id: "mus49", word: "climax", pronunciation: "/ˈklaɪmæks/", meaning: "đỉnh điểm cao trào câu chuyện", example: "The film built toward an explosive emotional climax.", emoji: "⚡" },
      { id: "mus50", word: "audience", pronunciation: "/ˈɔːdiəns/", meaning: "khán thính giả", example: "A spellbound audience watched the entire two-hour spectacle.", emoji: "👏" }
    ]
  }
];
