import { Topic } from "./types";

export const specializedTopics: Topic[] = [
  {
    id: "specialized-fish",
    name: "Các loại cá",
    icon: "🐟",
    color: "bg-cyan-100 text-cyan-700 border-cyan-200",
    words: [
      { id: "fish_1", word: "salmon", pronunciation: "/ˈsæm.ən/", meaning: "cá hồi", example: "Grilled salmon is rich in omega-3 fatty acids.", emoji: "🍣" },
      { id: "fish_2", word: "tuna", pronunciation: "/ˈtʃuː.nə/", meaning: "cá ngừ", example: "Fresh tuna is often eaten as sashimi.", emoji: "🐟" },
      { id: "fish_3", word: "mackerel", pronunciation: "/ˈmæk.rəl/", meaning: "cá thu", example: "Mackerel has a distinct, rich oily flavor.", emoji: "🐟" },
      { id: "fish_4", word: "snakehead fish", pronunciation: "/ˈsneɪk.hed fɪʃ/", meaning: "cá lóc / cá quả", example: "Snakehead fish sour soup is a Vietnamese specialty.", emoji: "🐟" },
      { id: "fish_5", word: "carp", pronunciation: "/kɑːp/", meaning: "cá chép", example: "The carp is swimming peacefully in the garden pond.", emoji: "🐟" },
      { id: "fish_6", word: "grass carp", pronunciation: "/ɡrɑːs kɑːp/", meaning: "cá trắm", example: "Grass carp is widely farmed in freshwater ponds.", emoji: "🐟" },
      { id: "fish_7", word: "catfish", pronunciation: "/ˈkæt.fɪʃ/", meaning: "cá trê / cá nheo", example: "Catfish has long whiskers around its mouth.", emoji: "🐟" },
      { id: "fish_8", word: "basa fish", pronunciation: "/ˈbɑː.sə fɪʃ/", meaning: "cá basa", example: "Basa fish fillets are white, tender, and mild in taste.", emoji: "🐟" },
      { id: "fish_9", word: "cod", pronunciation: "/kɒd/", meaning: "cá tuyết", example: "Cod is the traditional fish used for fish and chips.", emoji: "🐟" },
      { id: "fish_10", word: "tilapia", pronunciation: "/tɪˈlæp.i.ə/", meaning: "cá rô phi", example: "Fried tilapia with sweet and sour fish sauce is delicious.", emoji: "🐟" },
      { id: "fish_11", word: "red tilapia", pronunciation: "/red tɪˈlæp.i.ə/", meaning: "cá diêu hồng", example: "Steamed red tilapia with ginger and scallions is popular.", emoji: "🐟" },
      { id: "fish_12", word: "barramundi", pronunciation: "/ˌbær.əˈmʌn.di/", meaning: "cá chẽm / cá vược", example: "Pan-seared barramundi has a delightfully crispy skin.", emoji: "🐟" },
      { id: "fish_13", word: "pomfret", pronunciation: "/ˈpɒm.frɪt/", meaning: "cá chim", example: "White pomfret is sweet and tender when deep-fried.", emoji: "🐟" },
      { id: "fish_14", word: "swordfish", pronunciation: "/ˈsɔːd.fɪʃ/", meaning: "cá kiếm", example: "Swordfish has a firm, meaty texture suitable for grilling.", emoji: "🗡️" },
      { id: "fish_15", word: "grouper", pronunciation: "/ˈɡruː.pər/", meaning: "cá mú", example: "Steamed grouper with soy sauce is a banquet favorite.", emoji: "🐟" },
      { id: "fish_16", word: "flounder", pronunciation: "/ˈflaʊn.dər/", meaning: "cá bơn", example: "Flounder is a flatfish that lies flat on the sea bottom.", emoji: "🐟" },
      { id: "fish_17", word: "halibut", pronunciation: "/ˈhæl.ɪ.bət/", meaning: "cá bơn lưỡi ngựa", example: "Halibut is one of the largest flatfish in the cold ocean.", emoji: "🐟" },
      { id: "fish_18", word: "stingray", pronunciation: "/ˈstɪŋ.reɪ/", meaning: "cá đuối", example: "Grilled stingray with chili salt is very popular in coastal towns.", emoji: "🐡" },
      { id: "fish_19", word: "sardine", pronunciation: "/sɑːˈdiːn/", meaning: "cá mòi", example: "Canned sardines in tomato sauce are great for breakfast.", emoji: "🐟" },
      { id: "fish_20", word: "herring", pronunciation: "/ˈher.ɪŋ/", meaning: "cá trích", example: "Fresh herring salad with herbs is a Phu Quoc specialty.", emoji: "🐟" },
      { id: "fish_21", word: "anchovy", pronunciation: "/ˈæn.tʃə.vi/", meaning: "cá cơm", example: "Traditional Vietnamese fish sauce is fermented from fresh anchovies.", emoji: "🐟" },
      { id: "fish_22", word: "eel", pronunciation: "/iːl/", meaning: "con lươn / cá chình", example: "Crispy fried eel vermicelli soup is fragrant and nourishing.", emoji: "🐍" },
      { id: "fish_23", word: "mud carp", pronunciation: "/mʌd kɑːp/", meaning: "cá trôi / cá linh", example: "Young mud carp cooked with sesbania flowers is a Mekong Delta treat.", emoji: "🐟" },
      { id: "fish_24", word: "snapper", pronunciation: "/ˈsnæp.ər/", meaning: "cá hồng", example: "Red snapper is prized for its delicate sweet meat.", emoji: "🐟" },
      { id: "fish_25", word: "parrotfish", pronunciation: "/ˈpær.ət.fɪʃ/", meaning: "cá mó", example: "Parrotfish has vibrant blue-green scales like feathers.", emoji: "🐠" },
      { id: "fish_26", word: "sea bass", pronunciation: "/siː bæs/", meaning: "cá vược biển", example: "Sea bass baked with sea salt retains all its natural moisture.", emoji: "🐟" },
      { id: "fish_27", word: "trout", pronunciation: "/traʊt/", meaning: "cá hồi chấm / cá hồi suối", example: "Freshwater trout lives in cool, clean mountain streams.", emoji: "🐟" },
      { id: "fish_28", word: "climbing perch", pronunciation: "/ˈklaɪ.mɪŋ pɜːtʃ/", meaning: "cá rô đồng", example: "Fried climbing perch simmered with ginger is a rustic comfort dish.", emoji: "🐟" }
    ]
  },
  {
    id: "specialized-veggies",
    name: "Các loại rau & Thảo mộc",
    icon: "🥬",
    color: "bg-emerald-100 text-emerald-700 border-emerald-200",
    words: [
      { id: "veg_1", word: "water spinach", pronunciation: "/ˈwɔː.tər ˈspɪn.ɪtʃ/", meaning: "rau muống", example: "Stir-fried water spinach with garlic is a classic Vietnamese dish.", emoji: "🥬" },
      { id: "veg_2", word: "Malabar spinach", pronunciation: "/ˈmæl.ə.bɑːr ˈspɪn.ɪtʃ/", meaning: "rau mồng tơi", example: "Malabar spinach crab soup cools you down on hot summer days.", emoji: "🍃" },
      { id: "veg_3", word: "sweet leaf", pronunciation: "/swiːt liːf/", meaning: "rau ngót", example: "Sweet leaf minced pork soup is light and nutritious.", emoji: "🌿" },
      { id: "veg_4", word: "jute leaves", pronunciation: "/dʒuːt liːvz/", meaning: "rau đay", example: "Jute leaves are cooked together with crab soup and sponge gourd.", emoji: "🌱" },
      { id: "veg_5", word: "bok choy", pronunciation: "/ˌbɒk ˈtʃɔɪ/", meaning: "cải thìa / cải thìa trắng", example: "Bok choy has crunchy stalks and soft dark leaves.", emoji: "🥬" },
      { id: "veg_6", word: "mustard greens", pronunciation: "/ˈmʌs.təd ɡriːnz/", meaning: "cải bẹ xanh / cải đắng", example: "Pickled mustard greens go wonderfully with braised pork belly.", emoji: "🥬" },
      { id: "veg_7", word: "choy sum", pronunciation: "/ˌtʃɔɪ ˈsʌm/", meaning: "cải ngọt", example: "Boiled choy sum dipped in egg sauce is simple and wholesome.", emoji: "🥬" },
      { id: "veg_8", word: "lettuce", pronunciation: "/ˈlet.ɪs/", meaning: "xà lách", example: "Crisp lettuce wraps are served with Vietnamese spring rolls.", emoji: "🥬" },
      { id: "veg_9", word: "spinach", pronunciation: "/ˈspɪn.ɪtʃ/", meaning: "rau chân vịt / rau bina", example: "Spinach is rich in iron, minerals, and dietary fiber.", emoji: "🥬" },
      { id: "veg_10", word: "celery", pronunciation: "/ˈsel.ər.i/", meaning: "cần tây", example: "Stir-fried beef with celery and onions smells appetizing.", emoji: "🥬" },
      { id: "veg_11", word: "dill", pronunciation: "/dɪl/", meaning: "thì là", example: "Dill is an essential herb for Chả cá Lã Vọng.", emoji: "🌿" },
      { id: "veg_12", word: "perilla", pronunciation: "/pəˈrɪl.ə/", meaning: "tía tô", example: "Purple perilla leaves lend a warm aroma to snail soup.", emoji: "🍃" },
      { id: "veg_13", word: "Vietnamese balm", pronunciation: "/ˌvjet.nəˈmiːz bɑːm/", meaning: "kinh giới", example: "Vietnamese balm is always served with bún đậu mắm tôm.", emoji: "🌿" },
      { id: "veg_14", word: "Vietnamese coriander", pronunciation: "/ˌvjet.nəˈmiːz ˌkɒr.iˈæn.dər/", meaning: "rau răm", example: "Rau răm is customarily paired with balut eggs and chicken salad.", emoji: "🌿" },
      { id: "veg_15", word: "sawtooth coriander", pronunciation: "/ˈsɔː.tuːθ ˌkɒr.iˈæn.dər/", meaning: "ngò gai / mùi tàu", example: "Sawtooth coriander elevates the broth of traditional beef phở.", emoji: "🌱" },
      { id: "veg_16", word: "cilantro", pronunciation: "/sɪˈlæn.trəʊ/", meaning: "ngò rí / rau mùi", example: "Garnish the noodle bowl with freshly chopped cilantro.", emoji: "🌿" },
      { id: "veg_17", word: "Thai basil", pronunciation: "/taɪ ˈbæz.əl/", meaning: "húng quế", example: "Pluck a few Thai basil leaves to add into your hot noodle bowl.", emoji: "🌿" },
      { id: "veg_18", word: "mint", pronunciation: "/mɪnt/", meaning: "húng lủi / bạc hà", example: "Fresh mint leaves give a cooling sensation in fresh summer rolls.", emoji: "🍃" },
      { id: "veg_19", word: "fish mint", pronunciation: "/fɪʃ mɪnt/", meaning: "rau diếp cá", example: "Fish mint has a distinctive herbal tang and cooling health benefits.", emoji: "🍀" },
      { id: "veg_20", word: "bitter melon", pronunciation: "/ˈbɪt.ə ˌmel.ən/", meaning: "khổ qua / mướp đắng", example: "Stuffed bitter melon soup with pork is a Lunar New Year symbol of hope.", emoji: "🥒" },
      { id: "veg_21", word: "sponge gourd", pronunciation: "/spʌndʒ ɡʊəd/", meaning: "mướp hương", example: "Sponge gourd cooked with shrimp creates a naturally sweet broth.", emoji: "🥒" },
      { id: "veg_22", word: "asparagus", pronunciation: "/əˈspær.ə.ɡəs/", meaning: "măng tây", example: "Tender asparagus spears are sautéed lightly with butter and garlic.", emoji: "🎋" },
      { id: "veg_23", word: "watercress", pronunciation: "/ˈwɔː.tə.kres/", meaning: "cải xoong", example: "Beef salad tossed with crisp watercress and vinegar dressing.", emoji: "🥬" },
      { id: "veg_24", word: "piper lolot leaves", pronunciation: "/ˈpaɪ.pər ˈləʊ.lɒt liːvz/", meaning: "lá lốt", example: "Minced beef wrapped in piper lolot leaves is grilled over charcoal.", emoji: "🍃" },
      { id: "veg_25", word: "banana blossom", pronunciation: "/bəˈnɑː.nə ˈblɒs.əm/", meaning: "hoa chuối / bắp chuối", example: "Shredded banana blossom salad with chicken and peanuts.", emoji: "🌸" },
      { id: "veg_26", word: "artichoke", pronunciation: "/ˈɑː.tɪ.tʃəʊk/", meaning: "bông atisô", example: "Da Lat is famous for cooling herbal teas brewed from artichoke blossoms.", emoji: "🌱" },
      { id: "veg_27", word: "chives", pronunciation: "/tʃaɪvz/", meaning: "hẹ / lá hẹ", example: "Fresh chives are paired with tofu and river shrimp soup.", emoji: "🌿" },
      { id: "veg_28", word: "bamboo shoots", pronunciation: "/bæmˈbuː ʃuːts/", meaning: "măng tươi / măng tre", example: "Duck noodle soup with fresh sour bamboo shoots is irresistible.", emoji: "🎋" }
    ]
  },
  {
    id: "specialized-snails",
    name: "Các loại ốc & Sò biển",
    icon: "🐚",
    color: "bg-amber-100 text-amber-800 border-amber-200",
    words: [
      { id: "snail_1", word: "sweet snail", pronunciation: "/swiːt sneɪl/", meaning: "ốc hương", example: "Sweet snails stir-fried with salted egg yolk sauce are heavenly.", emoji: "🐚" },
      { id: "snail_2", word: "razor clam", pronunciation: "/ˈreɪ.zər klæm/", meaning: "ốc móng tay", example: "Razor clams sautéed with water spinach and garlic are popular on street stalls.", emoji: "🐚" },
      { id: "snail_3", word: "mud creeper snail", pronunciation: "/mʌd ˈkriː.pər sneɪl/", meaning: "ốc len", example: "Mud creeper snails stewed in rich coconut cream (ốc len xào dừa).", emoji: "🐚" },
      { id: "snail_4", word: "apple snail", pronunciation: "/ˈæp.əl sneɪl/", meaning: "ốc bươu", example: "Large apple snails steamed with lemongrass leaves and ginger.", emoji: "🐌" },
      { id: "snail_5", word: "freshwater snail", pronunciation: "/ˈfreʃˌwɔː.tər sneɪl/", meaning: "ốc mít / ốc vặn", example: "Boiled freshwater snails dipped in fiery ginger fish sauce.", emoji: "🐌" },
      { id: "snail_6", word: "moon snail", pronunciation: "/muːn sneɪl/", meaning: "ốc mỡ", example: "Moon snails stir-fried with sweet tamarind sauce (ốc mỡ xào me).", emoji: "🐚" },
      { id: "snail_7", word: "whelk", pronunciation: "/welk/", meaning: "ốc bulot / ốc biển lớn", example: "Steamed whelks with black pepper sauce have a crunchy, sweet texture.", emoji: "🐚" },
      { id: "snail_8", word: "bailer snail", pronunciation: "/ˈbeɪ.lər sneɪl/", meaning: "ốc giác", example: "Thin slices of boiled bailer snail tossed in mango and herb salad.", emoji: "🐚" },
      { id: "snail_9", word: "jumping snail", pronunciation: "/ˈdʒʌm.pɪŋ sneɪl/", meaning: "ốc nhảy", example: "Fresh jumping snails boiled simply with lime leaves are Nha Trang's pride.", emoji: "🐚" },
      { id: "snail_10", word: "spiny snail", pronunciation: "/ˈspaɪ.ni sneɪl/", meaning: "ốc gai", example: "Spiny snails grilled with scallion oil over hot embers.", emoji: "🐚" },
      { id: "snail_11", word: "blood cockle", pronunciation: "/blʌd ˈkɒk.əl/", meaning: "sò huyết", example: "Blood cockles stir-fried with garlic or roasted with tamarind (sò huyết xào me).", emoji: "🦪" },
      { id: "snail_12", word: "hairy cockle", pronunciation: "/ˈheə.ri ˈkɒk.əl/", meaning: "sò lông", example: "Hairy cockles grilled with fragrant scallion oil and crushed roasted peanuts.", emoji: "🦪" },
      { id: "snail_13", word: "scallop", pronunciation: "/ˈskɒl.əp/", meaning: "sò điệp", example: "Scallops grilled with cheese or garlic butter melt in your mouth.", emoji: "🦪" },
      { id: "snail_14", word: "oyster", pronunciation: "/ˈɔɪ.stər/", meaning: "con hàu", example: "Fresh oysters eaten raw with lime and wasabi or grilled with cheese.", emoji: "🦪" },
      { id: "snail_15", word: "clam", pronunciation: "/klæm/", meaning: "nghêu / ngao", example: "Steamed clams with lemongrass, chili, and Thai basil (nghêu hấp sả).", emoji: "🐚" },
      { id: "snail_16", word: "carpet clam", pronunciation: "/ˈkɑː.pɪt klæm/", meaning: "ngao hoa / chíp chíp", example: "Carpet clams steamed with beer have a clean, sweet taste.", emoji: "🐚" },
      { id: "snail_17", word: "two-shell clam", pronunciation: "/tuː ʃel klæm/", meaning: "ngao hai cồi", example: "Two-shell clams are large, juicy, and perfect for hotpot.", emoji: "🐚" },
      { id: "snail_18", word: "geoduck", pronunciation: "/ˈɡuː.i.dʌk/", meaning: "tu hài / ốc vòi voi", example: "Steamed geoduck with glass noodles and scallions is a prized delicacy.", emoji: "🐚" },
      { id: "snail_19", word: "mussel", pronunciation: "/ˈmʌs.əl/", meaning: "con vẹm / chem chép", example: "New Zealand green-lipped mussels steamed in white wine sauce.", emoji: "🦪" },
      { id: "snail_20", word: "green-lipped mussel", pronunciation: "/ɡriːn lɪpt ˈmʌs.əl/", meaning: "vẹm xanh", example: "Green-lipped mussels grilled with chili butter are rich and savory.", emoji: "🦪" },
      { id: "snail_21", word: "pen shell", pronunciation: "/pen ʃel/", meaning: "sò mai / biên mai", example: "Grilled pen shell muscle skewers are a famous treat on Phu Quoc Island.", emoji: "🦪" },
      { id: "snail_22", word: "canarium snail", pronunciation: "/kəˈneə.ri.əm sneɪl/", meaning: "ốc cà na", example: "Canarium snails roasted with sea salt and chili (ốc cà na rang muối).", emoji: "🐚" },
      { id: "snail_23", word: "finger snail", pronunciation: "/ˈfɪŋ.ɡər sneɪl/", meaning: "ốc ngón tay", example: "Finger snails sautéed with garlic butter are quick and flavorful.", emoji: "🐚" },
      { id: "snail_24", word: "river snail", pronunciation: "/ˈrɪv.ər sneɪl/", meaning: "ốc đồng", example: "Bún ốc with piping hot, tangy broth made from fermented rice wine.", emoji: "🐌" }
    ]
  },
  {
    id: "specialized-seafood",
    name: "Các loại hải sản",
    icon: "🦞",
    color: "bg-blue-100 text-blue-700 border-blue-200",
    words: [
      { id: "sea_1", word: "lobster", pronunciation: "/ˈlɒb.stər/", meaning: "tôm hùm", example: "Steamed rock lobster with melted garlic butter is a luxury dish.", emoji: "🦞" },
      { id: "sea_2", word: "black tiger shrimp", pronunciation: "/blæk ˈtaɪ.ɡər ʃrɪmp/", meaning: "tôm sú", example: "Grilled black tiger shrimp with chili salt over open charcoal.", emoji: "🦐" },
      { id: "sea_3", word: "whiteleg shrimp", pronunciation: "/ˈwaɪt.leɡ ʃrɪmp/", meaning: "tôm thẻ", example: "Sweet whiteleg shrimp boiled with fresh coconut water.", emoji: "🦐" },
      { id: "sea_4", word: "giant freshwater prawn", pronunciation: "/ˈdʒaɪ.ənt ˈfreʃˌwɔː.tər prɔːn/", meaning: "tôm càng xanh", example: "Giant freshwater prawns baked with savory head roe butter.", emoji: "🦐" },
      { id: "sea_5", word: "mantis shrimp", pronunciation: "/ˈmæn.tɪs ʃrɪmp/", meaning: "tôm tít / bề bề", example: "Steamed mantis shrimp with beer and dip in lime-pepper salt.", emoji: "🦐" },
      { id: "sea_6", word: "sea crab", pronunciation: "/siː kræb/", meaning: "cua biển / cua Cà Mau", example: "Ca Mau sea crabs are famous for their firm, naturally sweet meat.", emoji: "🦀" },
      { id: "sea_7", word: "blue swimming crab", pronunciation: "/bluː ˈswɪm.ɪŋ kræb/", meaning: "ghẹ xanh", example: "Steamed Ham Ninh blue swimming crabs are sweet and fragrant.", emoji: "🦀" },
      { id: "sea_8", word: "king crab", pronunciation: "/kɪŋ kræb/", meaning: "cua hoàng đế / cua Alaska", example: "Giant Alaskan king crab legs steamed with lemongrass.", emoji: "🦀" },
      { id: "sea_9", word: "soft-shell crab", pronunciation: "/sɒft ʃel kræb/", meaning: "cua lột", example: "Deep-fried crispy soft-shell crabs served with sweet chili dip.", emoji: "🦀" },
      { id: "sea_10", word: "squid", pronunciation: "/skwɪd/", meaning: "mực ống", example: "Stir-fried fresh squid with celery, pineapples, and tomatoes.", emoji: "🦑" },
      { id: "sea_11", word: "cuttlefish", pronunciation: "/ˈkʌt.əl.fɪʃ/", meaning: "mực nang", example: "Grilled cuttlefish patties (chả mực Hạ Long) are delightfully bouncy.", emoji: "🦑" },
      { id: "sea_12", word: "bigfin reef squid", pronunciation: "/ˈbɪɡ.fɪn riːf skwɪd/", meaning: "mực lá", example: "Thick, tender bigfin reef squid grilled with satay sauce.", emoji: "🦑" },
      { id: "sea_13", word: "baby squid", pronunciation: "/ˈbeɪ.bi skwɪd/", meaning: "mực sim / mực cơm", example: "Steamed baby squid with ginger retains its sweet inner roe.", emoji: "🦑" },
      { id: "sea_14", word: "octopus", pronunciation: "/ˈɒk.tə.pəs/", meaning: "bạch tuộc", example: "Spicy grilled octopus skewers on charcoal grill.", emoji: "🐙" },
      { id: "sea_15", word: "jellyfish", pronunciation: "/ˈdʒel.i.fɪʃ/", meaning: "sứa biển", example: "Crisp jellyfish salad with carrots, fresh mint, and toasted sesame.", emoji: "🪼" },
      { id: "sea_16", word: "abalone", pronunciation: "/ˌæb.əˈləʊ.ni/", meaning: "bào ngư", example: "Braised premium abalone soup with shiitake mushrooms.", emoji: "🐚" },
      { id: "sea_17", word: "sea cucumber", pronunciation: "/siː ˈkjuː.kʌm.bər/", meaning: "hải sâm", example: "Sea cucumber braised with Chinese herbs nourishes the body.", emoji: "🥒" },
      { id: "sea_18", word: "sea urchin", pronunciation: "/siː ˈɜː.tʃɪn/", meaning: "cầu gai / nhím biển", example: "Grilled sea urchin with scallion oil and raw quail egg inside.", emoji: "🦔" },
      { id: "sea_19", word: "caviar", pronunciation: "/ˈkæv.i.ɑːr/", meaning: "trứng cá muối", example: "Black sturgeon caviar is served chilled on small mother-of-pearl spoons.", emoji: "🐟" },
      { id: "sea_20", word: "shark fin", pronunciation: "/ʃɑːk fɪn/", meaning: "vi cá", example: "Shark fin soup was traditionally served at royal feasts.", emoji: "🦈" },
      { id: "sea_21", word: "dried squid", pronunciation: "/draɪd skwɪd/", meaning: "mực khô", example: "Charcoal-grilled dried squid shredded and dipped in spicy chili paste.", emoji: "🦑" },
      { id: "sea_22", word: "seaweed", pronunciation: "/ˈsiː.wiːd/", meaning: "rong biển / tảo biển", example: "Toasted crispy seaweed sprinkled with sesame and sea salt.", emoji: "🌿" }
    ]
  },
  {
    id: "specialized-mushrooms",
    name: "Các loại nấm & Thảo mộc quý",
    icon: "🍄",
    color: "bg-orange-100 text-orange-800 border-orange-200",
    words: [
      { id: "mush_1", word: "shiitake mushroom", pronunciation: "/ʃiːˈtɑː.keɪ ˈmʌʃ.ruːm/", meaning: "nấm hương / nấm đông cô", example: "Shiitake mushrooms impart an earthy aroma to broths and stews.", emoji: "🍄" },
      { id: "mush_2", word: "enoki mushroom", pronunciation: "/eˈnəʊ.ki ˈmʌʃ.ruːm/", meaning: "nấm kim châm", example: "Thin beef rolls wrapped around crisp enoki mushrooms for hotpot.", emoji: "🍄" },
      { id: "mush_3", word: "king oyster mushroom", pronunciation: "/kɪŋ ˈɔɪ.stər ˈmʌʃ.ruːm/", meaning: "nấm đùi gà", example: "King oyster mushrooms have a thick, pleasantly chewy stem like scallops.", emoji: "🍄" },
      { id: "mush_4", word: "straw mushroom", pronunciation: "/strɔː ˈmʌʃ.ruːm/", meaning: "nấm rơm", example: "Straw mushrooms are commonly braised with tofu in vegetarian dishes.", emoji: "🍄" },
      { id: "mush_5", word: "wood ear mushroom", pronunciation: "/wʊd ɪər ˈmʌʃ.ruːm/", meaning: "mộc nhĩ / nấm mèo", example: "Finely sliced wood ear mushrooms add crunchy texture to spring rolls.", emoji: "🍄" },
      { id: "mush_6", word: "oyster mushroom", pronunciation: "/ˈɔɪ.stər ˈmʌʃ.ruːm/", meaning: "nấm bào ngư", example: "Crispy fried oyster mushrooms seasoned with lemongrass and chili.", emoji: "🍄" },
      { id: "mush_7", word: "snow fungus", pronunciation: "/snəʊ ˈfʌŋ.ɡəs/", meaning: "nấm tuyết / ngân nhĩ", example: "Snow fungus sweet soup with lotus seeds and red dates cools the skin.", emoji: "🍄" },
      { id: "mush_8", word: "termite mushroom", pronunciation: "/ˈtɜː.maɪt ˈmʌʃ.ruːm/", meaning: "nấm mối", example: "Wild termite mushrooms harvested after rain are exceptionally sweet.", emoji: "🍄" },
      { id: "mush_9", word: "reishi mushroom", pronunciation: "/ˈreɪ.ʃi ˈmʌʃ.ruːm/", meaning: "nấm linh chi", example: "Reishi mushroom tea boosts natural immunity and liver health.", emoji: "🍄" },
      { id: "mush_10", word: "button mushroom", pronunciation: "/ˈbʌt.ən ˈmʌʃ.ruːm/", meaning: "nấm mỡ", example: "White button mushrooms sautéed in garlic butter and herbs.", emoji: "🍄" },
      { id: "mush_11", word: "truffle", pronunciation: "/ˈtrʌf.əl/", meaning: "nấm cục / nấm truffle", example: "Fresh black truffle shavings elevate handmade pasta dishes.", emoji: "🍄" },
      { id: "mush_12", word: "shimeji mushroom", pronunciation: "/ʃɪˈmeɪ.dʒi ˈmʌʃ.ruːm/", meaning: "nấm linh chi nâu / nấm ngọc châm", example: "Shimeji mushrooms keep their firm crunch when boiled in hot soup.", emoji: "🍄" }
    ]
  }
];
